### ISSUE TITLE
Build status does not appear on PyPi page

### ISSUE THREAD

**Issue by guberti** [psf/black#1021]
The TravisCI build status shield [on PyPI](https://pypi.org/project/black/) shows as "build: unknown". This is likely because the shield points to https://travis-ci.org/ambv/black, when it should point to https://travis-ci.com/psf/black.

Note that the Travis CI shield for the README of this GitHub repo works properly - the only thing that's broken is the shield at https://pypi.org/project/black/. Screenshot below as of 9/14/2019 12:02 AM GMT:

![image](https://user-images.githubusercontent.com/3069006/64915007-d89b8f00-d711-11e9-98e5-c21671d409b8.png)

**Comment by hugovk** [comment]
The badge was fixed in master in 
https://github.com/psf/black/commit/77b6ed1b70bd07f058bc551906bc880022847964 and https://github.com/psf/black/pull/939, a release is needed to fix it on PyPI. 

See https://github.com/psf/black/issues/517 for the (one-year old! 🎂) release discussion. Of course, a beta/RC release would also fix it.
