### ISSUE TITLE
newline inside bracket?

### ISSUE THREAD

**Issue by makslevental** [psf/black#1048]
```python
    sr = (out.squeeze(0).permute((1, 2, 0)).cpu().numpy()) + numpy.asarray(r2(image))[
        :, :, :3
    ] / 255
```
any way to avoid this?

**Comment by zsol** [comment]
You can try putting the entire bracketed expression inside parenthesis like so:
```
sr = (
    (out.squeeze(0).permute((1, 2, 0)).cpu().numpy())
    + numpy.asarray(r2(image))[:, :, :3]
) / 255
```

But maybe the best think for this piece of code would be to extract some sub-expressions to locals. Even with the above formatting it's hard to tell what's going on.

**Comment by makslevental** [comment]
>But maybe the best thing for this piece of code would be to extract some sub-expressions to locals.

i mean that's for me to decide isn't it? my point is why would black format in this way.

**Comment by zsol** [comment]
Yes, it's absolutely up to you. Black formats it this way currently because of the algorithm that's explained in the readme (right hand splitting - it starts from the right side of the expression and breaks it up).

My point with that sentence was that I don't believe there _is_ a good way of formatting that expression as it is.
