### ISSUE TITLE
Unstable formatting with "# type: ignore" comment

### ISSUE THREAD

**Issue by The-Compiler** [psf/black#1061]
Operating system: Arch Linux
Python version: 3.7
*Black* version: 19.3b0, 19.3b1.dev96+g57ab909
Does also happen on master: yes

I think I'm seeing a "NTERNAL ERROR: Black produced different code on the second pass of the formatter." which is different from others I find here (#954, #1042, #1044).

With this code:

```python
class Test:
    def _init_host(self, parsed) -> None:
        if (parsed.hostname is None or  # type: ignore
                not parsed.hostname.strip()):
            pass
```

I get this diff:

```diff
--- source
+++ first pass
@@ -1,6 +1,8 @@
 class Test:
     def _init_host(self, parsed) -> None:
-        if (parsed.hostname is None or  # type: ignore
-                not parsed.hostname.strip()):
+        if (
+            parsed.hostname is None
+            or not parsed.hostname.strip()  # type: ignore
+        ):
             pass
 
```

```diff
--- first pass
+++ second pass
@@ -1,8 +1,7 @@
 class Test:
     def _init_host(self, parsed) -> None:
         if (
-            parsed.hostname is None
-            or not parsed.hostname.strip()  # type: ignore
+            parsed.hostname is None or not parsed.hostname.strip()  # type: ignore
         ):
             pass
 
```

**Comment by JelleZijlstra** [comment]
@msullivan is this related to any of the changes you made recently?

**Comment by The-Compiler** [comment]
I was able to bisect this to ca9ad698ef75736828b644678eba2f4836db6277.

**Comment by msullivan** [comment]
Not related to any of the changesI made recently but I've looked into it.

The issue here is that the `# type: ignore` attached to the end of the original line prevents everything from getting collapsed onto one line (since it is a type comment in the "middle" of a potential line), but it is still attached to the `or` and so it gets moved down to the second line.

But then on the second run, it's not in the middle anymore, so black thinks it is safe to collapse everything onto one line.

One fix to this would be to not have internal `type: ignore` comments prevent merging lines. This fixes the issue here, but I'm not totally confident it fixes the issue always. It also changes some behavior and will make it harder to ignore a specific argument to a function without ignoring the whole call in some cases.

Another possibility could be to go the other direction and consider a type comment (just an ignore?) at the *end* uncollapsable also, so we stick with the version split on two lines?

**Comment by IIBenII** [comment]
I open an issue on mypy https://github.com/python/mypy/issues/7762 because when I use black + mypy and `# type: ignore`, black uncollapse the line and mypy ignore the comment, so it raise an error. It's possible to not uncollapse line when they are `# type: ignore`?

**Comment by JelleZijlstra** [comment]
@IIBenII the next release of Black will be better at keeping `# type: ignore` lines in the right place. I'm not sure whether it will cover your exact use case though.

**Comment by IIBenII** [comment]
@JelleZijlstra Thanks, I will wait :)
