### ISSUE TITLE
Invalid code with long index expression

### ISSUE THREAD

**Issue by JelleZijlstra** [psf/black#1080]
Current master produces invalid code in a very long index expression:
```
$ cat bltest.py 
def xxxxxxxxxxxxxxxxxxxxxxxxxxxx() -> Set[
    "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
]:
    pass
$ black --diff bltest.py 
error: cannot format bltest.py: INTERNAL ERROR: Black produced code that is not equivalent to the source.  Please report a bug on https://github.com/psf/black/issues.  This diff might be helpful: /tmp/blk_zj5v4v59.log
Oh no! 💥 💔 💥
1 file failed to reformat.
```
This is a likely result of #826.

**Comment by qualname** [comment]
Hi!

Just wanted to note that this is present on 84e22b75c6baeb231dee52b7bd086f547063e0e4 too (So it wasn't introduced by #826 ).

The issue seems to be that empty (parameterless) parentheses are ignored/skipped by [left_hand_split](https://github.com/psf/black/blob/14b28c89c22659e1f935bc0ac22ee03d90bcc290/black.py#L2452), so `Set`'s square brackets are the first matching pair (and then a [comma is inserted](https://github.com/psf/black/blob/14b28c89c22659e1f935bc0ac22ee03d90bcc290/black.py#L2613) after `"xxx...x"` that turns the type into a set of tuples).

**Comment by JelleZijlstra** [comment]
Both of these are fixed on master. We're planning to have a release very soon now.

**Comment by JelleZijlstra** [comment]
Sorry, wrong issue.

**Comment by JelleZijlstra** [comment]
Right. It looks like this was introduced by #891, which changed the condition right above the code you linked at https://github.com/psf/black/blob/14b28c89c22659e1f935bc0ac22ee03d90bcc290/black.py#L2613. I submitted a fix.
