### ISSUE TITLE
Black should leave formfeeds alone, but eats them instead

### ISSUE THREAD

**Issue by ryanprior** [psf/black#1100]
**Describe the bug** 

When Black encounters a formfeed character alone on a line, it removes the character. It would be preferable to leave such a line alone, as it's useful in text editors to use formfeeds to separate code into pages (eg https://www.gnu.org/software/emacs/manual/html_node/emacs/Pages.html)

**To Reproduce** Steps to reproduce the behavior:

1. Take this file:

```python

## Note form feed character on previous line

print("hello Black issue tracker!")

## Note form feed character on previous line
```

2. Run _Black_ on it with no arguments
3. Observe that Black has eaten our innocent formfeeds :(

**Expected behavior** A clear and concise description of what you expected to happen.

Formfeeds are left alone >:3

**Environment (please complete the following information):**

- Version: 19.3b0
- OS and Python version: Linux/Python 3.7.0

**Does this bug also happen on master?**

Yes ([see result](https://black.now.sh/?version=master&state=_Td6WFoAAATm1rRGAgAhARYAAAB0L-Wj4ADLAINdAD2IimZxl1N_Wk6nPtbdt-WcrG23kHUogadGkXuL8zw6EORFHkzlMIkRwmCm2mrfq4zoqUrHUGTtg2BQtdbr3t8RU9_ynX8S4PLYJXX0uXQ1Re94dteyen96ylOthccJtytkrotPfmq4gRbAAzVycV_tb5Zyi9f1xy4GJKQAhLUNe4CVAAD7NvOt65WuUAABnwHMAQAAcmJcL7HEZ_sCAAAAAARZWg==))

**Additional context**

Python treats formfeeds as whitespace characters, but they aren't fungible with other whitespace because they have a semantic meaning in some text editors.

**Comment by ambv** [comment]
I'm not opposed to having this but it requires specialized support. For that to happen we'll need some more infromation first.
- how does flake8 perceive formfeeds (do they count as a single newline?)
- how do other formatters treat formfeeds
- how do I even input formfeeds and how do I make them visible
- is it fine to remove leading and trailing whitespace on the same line as the formfeed?

**Comment by ryanprior** [comment]
Thank you for the quick reply! I am researching your questions.

> how does flake8 perceive formfeeds (do they count as a single newline?)

I am looking into this.

> how do other formatters treat formfeeds

I haven't used any other formatters, which one(s) should I look at?
> how do I even input formfeeds and how do I make them visible

In Vim: Ctrl+V, Ctrl+L
In Emacs: Ctrl+Q, Ctrl+L
Other editors may have other entry mechanisms. Formfeed's ASCII is value 12 or 0x0C if that helps.

To make them visible, make sure your editor is configured to display whitespaces explicitly. (I think Emacs and Vim display formfeeds by default, but other editors maybe hide non-printable characters?)

> is it fine to remove leading and trailing whitespace on the same line as the formfeed?

Yes, that would be fine.

**Comment by JelleZijlstra** [comment]
Other formatters to look at could include yapf for Python and formatters for other languages, such as prettier (JS, yaml), gofmt (golang), clang-format (C/C++).

**Comment by jrosdahl** [comment]
> gofmt (golang)

Go does not accept form feeds in source code at all.

> clang-format (C/C++)

clang-format removes form feeds (tested with version 8.0.0).

**Comment by calpaterson** [comment]
One workaround for this problem that may help people: disable black using `fmt:` comments **and include a legal python expression or statement**, eg:

```
# fmt: off
# DB layer  (^L appears just before this)
...
# fmt: on
```

It's important that you include a python expression (in this case, [Ellipsis](https://docs.python.org/3/library/constants.html#Ellipsis)) or else black won't disable formatting for some reason.  Perhaps that should be the subject of a separate issue.

To the authors of black: ^L's used to be a fairly common idiom and some people do still use it (for example when you want everything in one file but still want to have a way to divide it up) - it would be great if you could add an option not to remove them :)

**Comment by tungol** [comment]
I created a series of test cases to see how flake8 treats formfeeds. I used a line with a "#" on either side as bookends. I'll use \n and \f for newlines and form feed characters for clarity.

flake8 has no complaints about these:

`#\n\f\n#\n`
`#\n\n\f\n#\n`
`#\n\f\n\n#\n`

These all produce "E303 too many blank lines (3)":
`#\n\n\n\f\n#\n`
`#\n\f\n\n\n#\n`
`#\n\n\f\n\n#\n`

Which is interesting. It seems that it's not counting the line `\f\n` as a blank line, but it doesn't cause it to reset the "how many blank lines in a row" counter either.

If there's no newline after the \f, as in `#\n\n\f#\n` I get two errors:
E114 indentation is not a multiple of 4 (comment)
E116 unexpected indentation (comment)

Removing the newline before the \f (`#\f\n#\n`) gives "E265 block comment should start with '# '".

Inserting the space (`# \f\n#\n`) makes it "W291 trailing whitespace" instead.

As for YAPF, it currently removes the character as well.

One other note, I think that correct style would be to only allow the character as part of the sequence `\n\f\n`. That was how it was used in cpython source code, prior to all instances being removed. GNU coding standard has this to say about formfeeds:

https://www.gnu.org/prep/standards/standards.html#index-control_002dL
> The formfeeds should appear alone on lines by themselves. 

and I think that statement implies `\n\f\n` as well. (I find "line" to be a little ambiguous when discussing formfeed characters, since at least some editors render a formfeed as a newline.)

**Comment by mcarmosi** [comment]
As an emacs user getting into Python for scikit-learn, I would be very happy to see this fixed. I often use form-feeds to break my code (GNU R and emacs lisp) into logical "pages" and then use the commands `forward-page` and `backward-page` to navigate and `narrow-to-page` to show just one page.

This is particularly helpful when I screen share to discuss my code; it breaks a file up into "slides" that focus the conversation. Currently I have to put in linefeeds and then turn off black before these calls if I want to use my presentation mode.

**Comment by ryanprior** [comment]
@tungol & @JelleZijlstra you're champions for making this happen! Many thanks ❤️
