### ISSUE TITLE
Neovim version error.

### ISSUE THREAD

**Issue by dgnsrekt** [psf/black#1149]
**Describe the bug** A clear and concise description of what the bug is.

There is an error in the black.vim plugin which doesn't check which type of vim is being run only the version of vim. I am using neovim which is currently on the stable version 0.4.3. The black.vim plugin is checking for a vim version of over 7. The plugin seems to work fine on nvim version 0.3.8 other than this annoying echo before opening every python file.

**To Reproduce** Steps to reproduce the behavior:

Within a pipenv venv.
```
➜ nvim
This script requires vim7.0+ with Python 3.6 support.
Press ENTER or type command to continue
```
**Expected behavior** A clear and concise description of what you expected to happen.

Opening a python file in nvim and not getting the echoed error.

**Environment (please complete the following information):**

- Version: [19.10b0]
- Python: 3.7.5rc1
- OS: Ubuntu 19.10 eoan
- Kernel: x86_64 Linux 5.3.0-20-generic
- Neovim: v0.3.8

**Does this bug also happen on master?** To answer this, you have two options:

The following line shows the bug clearly happens on the master branch.
https://github.com/psf/black/blob/master/plugin/black.vim#L16
I suggest a conditional be added which checks for the type of vim being run. vim vs nvim before checking the version.  

**Additional context** Add any other context about the problem here.

**Comment by dgnsrekt** [comment]
After doing some research into .vim plugins it appears there is no issue with the black.vim plugin code. The issue seems to be with the venv and vim.

**Comment by olirice** [comment]
for others who wind up here:

Unlike vim, neovim supports python via remote plugins. Make sure you have the python package "neovim" installed in your current environment i.e.


`pip install neovim`

for more information, the documentation explaining python integration is available at neovim help page `:help provider-python`

**Comment by uriva** [comment]
Consider adding this to the readme.

**Comment by erikr** [comment]
Per `:help provider-python`, `pip install pynvm` should get `black` working after a fresh install of `neovim` (rather than `pip install neovim`:

https://github.com/neovim/neovim/blob/e43dbfdd05d09e28ee0468f1cd1808f859807606/runtime/doc/provider.txt#L32

The [README](https://github.com/psf/black/blob/main/README.md) does not yet have this information. However, info on how to set up `black` for every type of editor may be too detailed.

However, [Getting Started](https://black.readthedocs.io/en/stable/getting_started.html) in the more detailed documentation could be an appropriate place for such content.

Any thoughts?
