### ISSUE TITLE
Don’t have a nazi symbol as default length

### ISSUE THREAD

**Issue by Gallaecio** [psf/black#1191]
> Black defaults to 88 characters per line, which happens to be 10% over 80.

[It also happens to be a nazi symbol](https://www.adl.org/education/references/hate-symbols/88).

While having a nazi symbol in a project called “black” may sound funny to some, me included, I suggest switching to something else, even if it’s just `87` or `89`.

**Comment by hugovk** [comment]
Also from https://www.adl.org/education/references/hate-symbols/88:

> It should be noted that 88 can be found in non-extremist contexts. The number is used by ham radio operators to mean "hugs" or "hugs and kisses." Also, a number of NASCAR drivers, including several very well-known ones, have used the number 88, resulting in various automobile stickers and other forms of merchandise sporting that number.

**Comment by noviluni** [comment]
I also feel uncomfortable using 88... Why not to use 90 as default?

**Comment by onlinejudge95** [comment]
Whaaaaaaatttttttt!!!!!!!!!!!
My 2 cents, PEP recommendation over any symbolic meanings. All of us are here to use black for linting our code. If someone thinks that line length of 88 is a remark for any social issue, then they are simply overthinking stuff. I mean i can be wrong but this seems more of a social issue than any programming issue and are we so insecure to allow these messed up thoughts seep into the ART of PROGRAMMING 🤐

**Comment by knyghty** [comment]
@onlinejudge95 the problem here is not "people overthinking stuff" but people having an immediate and perhaps involuntary discomfort seeing the number.

I don't really have a problem with it either way, but I think overreacting to other people's feelings isn't helpful either.

Personally, I think PEP8 is great, but it's not the bible, it's not some inevitable truth, it was written in a time of smaller screens and in particular, standard character widths for terminals, something that doesn't exist anymore, and while I still find short line lengths good for readability, I don't see much of a difference.

Also, if you actually read PEP8, you'd know that line length is NOT 88, it's 79. The reason 88 is chosen is because it's 80 chars + 10%, which is just as arbitrary as using PEP8 + 10% = ~87, or just rounding to 90.

**Comment by onlinejudge95** [comment]
@knyghty it's the reason that matters, altering the length by giving the argument of screen size is **1000%** acceptable. Why? Because it is driven by circumstances related to Programming, which in my opinion should be the only reason that should matter.
Don't take it in any other sense I have read **PEP8** enough to know that line length _SHOULD_ be 79(or 120 as the current trends are going on) but you are missing my point completely, my assertion was that any such decision should come out due to logical arguments, not emotional ones.
Imagine both of us fighting with **PSF** that we want switch statement because we FEEL so.
Anyways it's just my opinion and nothing else. Peace out and good day to you all ☺️

**Comment by knyghty** [comment]
I'm not very convinced by your argument. First of all, 88 is quite arbitrary. It's not really related to PEP8. In fact, the readme says that "90ish" is about right. So why not just make it 90? To directly address your concern: there is no "programming" circumstance for a line length of 88 as opposed to 90.

There is a perfectly logical argument, and that is, why use a number that might make people comfortable when we can be more inclusive (this is a good thing, no?) by simply choosing a less arbitrary (at least in base 10) number such as 90? I don't see why "emotions" and "logic" have to be separated. I can make many logical arguments for taking people's emotions into consideration. For example, the community being more welcoming (Python is already extremely good here, relative to other languages and technical communities), which in turn incentivises people to be involved with Python, which means, even in terms of raw numbers, more packages, more committers, more maintainers, etc. And outside of raw numbers, increasing the diversity of the community has the potential to remove programming biases (see this talk from DjangoCon Europe last year: https://pyvideo.org/djangocon-europe-2018/its-not-a-bug-its-a-bias.html).

Moreover, there are two reasons why this seems like an acceptable change to me.

1. The one thing black does compromise on is line-length, if you are particularly wedded to 88 for some reason, nothing is stopping you.
2. As black is not quite out of beta, this is a reasonable time to change it. It's just a default after all, nobody is forcing your lines to be a particular length.

One thing you seem to forget is that different types of feelings are... different. There is a difference between "feeling" python should have a switch statement and "feeling" involuntarily uncomfortable with seeing a certain symbol.

**Comment by zsol** [comment]
Thank you for highlighting this unfortunate coincidence. At this point Black is deployed to a large number of projects so it's unlikely we're going to change such a core aspect of the formatting.

If it's any consolation, none of the core contributors meant the default line length to signify anything other than a practical upper limit on the number of characters in a line that makes python code readable for the majority of people using Black.
