### ISSUE TITLE
black `19.10b0` errors on the wrong line

### ISSUE THREAD

**Issue by samuel-massinon** [psf/black#1263]
**Describe the bug** A clear and concise description of what the bug is.
black is erroring on the wrong line. 

**To Reproduce** Steps to reproduce the behavior:
1. Take this file '...'
```python
def bar():
    f""

def foo(aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa="", b):
    return a, b
```
2. Run _Black_ on it with these arguments '....'
`
black test.py --check --line-length 88 --target-version py36
`
3. See error
```
error: cannot format test.py: cannot use --safe with this file; failed to parse source file.  AST error message: invalid syntax (<unknown>, line 2)
Oh no! 💥 💔 💥
1 file would fail to reformat.
```
**Expected behavior** A clear and concise description of what you expected to happen.
To throw this error (which black version `19.3b0` does)
```
error: cannot format test.py: cannot use --safe with this file; failed to parse source file with Python 3.6's builtin AST. Re-run with --fast or stop using deprecated Python 2 syntax. AST error message: non-default argument follows default argument (<unknown>, line 4)
All done! 💥 💔 💥
1 file would fail to reformat.
```
**Environment (please complete the following information):**

- Version:`19.10b0`
- OS and Python version: Linux/Python 3.6.9

**Does this bug also happen on master?** To answer this, you have two options:
It does not happen on master.

**Additional comments**
I think this is similar to https://github.com/psf/black/issues/1262

**Comment by ichard26** [comment]
So this is a variation of #423. The problem is that the `assert_equivalent` check will fail to parse the source multiple times (on each time a `SyntaxError` is raised), leaving the function to try parsing using Python27 grammar as a last resort which of course doesn't understand the `f` string prefix. (maybe the `SyntaxError` is because of something else, I really don't know `Python27` well)

**Warning:** my terminology is probably quite wrong. Feel free to have a good laugh :)

Here's a brief rundown of what is happening in order:
1. _Black_ is run with no arguments other than the file to format. This sets `fast=False`.
2. After some function hopping, we land on `format_file_contents` which formats the code without complaining. Interestingly it doesn't fail to parse the code here. 
3. Then after formatting the source code, it checks whether the source and formatted code have equivalent ASTs (and that formatting is stable) since `fast=False`. This is to check if _Black_ had made an unsafe code change.
```py3
    if not fast:
        assert_equivalent(src_contents, dst_contents)
        assert_stable(src_contents, dst_contents, mode=mode)  # not important here
```

4. `assert_equivalent` is called which then calls `parse_ast(src)` (`src` is the original code)
```py3
    try:
        src_ast = parse_ast(src)
    except Exception as exc:
        raise AssertionError(
            "cannot use --safe with this file; failed to parse source file.  AST"
            f" error message: {exc}"  # we will land here soon
        )
```

5. Since I'm on `Python 3.8.1`, `parse_ast` will try to parse `src` using Python38 grammar, which fails with a `non-default argument follows default argument` `SyntaxError`. Then it tries again using Python37 and Python36 grammar which both fail with the same exception as Python38. Then it tries Python35 which certainly fails since f-strings weren't available in Python35.

```py3
if sys.version_info >= (3, 8):
        # TODO: support Python 4+ ;)
        for minor_version in range(sys.version_info[1], 4, -1):
            try:
                return ast.parse(src, filename, feature_version=(3, minor_version))
            except SyntaxError as e:
                print(e)  # my debugging print function :D
                continue
```
And here's the command line output at this point. **Bare in mind that every `SyntaxError` encountered while parsing in the code above will be printed since of the rogue little print function I added :-)**
```
PS R:\Programming\black> black test.py
non-default argument follows default argument (<unknown>, line 4)  # error using Python38 grammar
non-default argument follows default argument (<unknown>, line 4)  # then Python37
non-default argument follows default argument (<unknown>, line 4)   # then Python36
Format strings are only supported in Python 3.6 and greater (<unknown>, line 2)   # then Python35
```
6. Afterwards, since all of those parse attempts failed, `parse_ast` will try parse with Python27 grammar -> `return ast27.parse(src)` which chokes on the f-string... *I think*.
7. Since the last parsing attempt was with Python27 grammar, the `SyntaxError` exception by `ast27.parse(src)` gets caught in the  try except` block in the code from number 4 and becomes the error message visible to the user:
```
error: cannot format test.py: cannot use --safe with this file; failed to parse source file.  AST error message: invalid syntax (<unknown>, line 2)
```

A (probably horrible) summary:
* _Black_ experiences five different parsing errors while using Python38 to Python35 grammar and then Python27 grammar in my case:
  * non-default argument follows default argument (<unknown>, line 4)
  * non-default argument follows default argument (<unknown>, line 4)
  * non-default argument follows default argument (<unknown>, line 4)
  * Format strings are only supported in Python 3.6 and greater (<unknown>, line 2)
  * invalid syntax (<unknown>, line 2)
* The Python27 grammar based and wrong error is outputted to the user since it's the last error to occur in the chain. That's just how _Black_ works, when _Black_ encounters a `SyntaxError` while parsing, it tries a different grammar, with Python27 as the last one.
* **The problem is deciding which error is the most correct. How is _Black_ supposed to know which error is the true error without knowing the Python version?** If you want a better explanation of this point, read [this comment by ambv](https://github.com/psf/black/issues/423#issuecomment-413882929) on #423.

Yes, we could use the `--target-version` option to help _Black_ choose the proper error. Except, 1. we would need to pass an option around even more which isn't ideal and 2. not everyone defines `--target-version` so they are still out of luck.

**Environment:**

* _Black_ version: `19.10b1.dev87+g4501f22`
* OS: `Windows 10 Home Edition Build 18363`
* Python version: `Python 3.8.1`

**Comment by ThatXliner** [comment]
bump

**Comment by hauntsaninja** [comment]
This appears fixed, probably as part of dropping Python 2 support
