### ISSUE TITLE
Long arrays wrapped unnecessarily on multiple lines

### ISSUE THREAD

**Issue by Fhyarnir** [psf/black#1281]
**Versioning**
Black `19.10b0`, OS `Windows 10 1803` and Python `3.7.2`.

**Is your feature request related to a problem? Please describe.**
The problem is related to how black currently wraps arrays. For instance, smaller arrays such as `[1,2,3]` formats correctly to `[1, 2, 3]` while staying on a single line. Longer arrays, such as
![image](https://user-images.githubusercontent.com/40139671/75099110-2d470e00-55be-11ea-82e8-2014bdade5e9.png)
becomes
![image](https://user-images.githubusercontent.com/40139671/75099106-1a343e00-55be-11ea-9014-ccae76de6a3a.png)
Which uses too many lines. Note how a comma `,` is automatically added at the end of the array, thus likely triggering a phenomenon of [this](https://github.com/psf/black/issues/1184) type. Removing the comma changes nothing, as it simply comes back. See ie. [the black playground](https://tinyurl.com/black-playground).

**Describe the solution you'd like.** I wish to use `black` for formatting, but with wrapping behavior similar to (or equal to) that of `autopep8`'s formatting for such arrays as described. Which gives:
![image](https://user-images.githubusercontent.com/40139671/75099705-f9231b80-55c4-11ea-8143-a5d8e1a786c8.png)

**Describe alternatives you've considered**

- Use `# fmt: off` before a code block, and `# fmt: on` after.  While this works, the array a) remains unformatted and b) stays only on one line that introduces a scrollbar which must be used to check the full content
- Use Excel file to store longer numbered arrays, and importing them with ie. pandas to keep data entry on 1-2 lines. I find this option inconvenient for arrays of intermediate lengths (such as the longer array displayed) that a) does not fit on a single line and b) are too short for it to make sense to store it in an Excel file (ie. when setting up test arrays on-the-fly)
- Reverting back to version `18.4a0` appear to be equivalent to `fmt` effect, primarily because formatting then appears to not be applied at all. I have not explored the consequences this has with other formatting behavior not related to this test case. The next version, `18.4a1`, produces the exact same behavior as the behavior of `19.10b0` (also with the extra comma at the end of the then vertically formatted array)

**settings.json**
```C#
{
    "python.pythonPath": ".venv\\Scripts\\python.exe",
    "editor.acceptSuggestionOnEnter": "off",
    "python.formatting.provider": "black",
    //"python.formatting.provider": "autopep8",
    "editor.formatOnSave": true,
    "python.formatting.blackArgs": [
        "--line-length",
        "88"
    ],
    "python.formatting.autopep8Args": [
        "--max-line-length",
        "88",
        "--experimental"
    ]
}
```

**Comment by joaoe** [comment]
I kind of agree with this. I wish long lists of scalar values would just wrap instead of being expended one item per line. But that's what fmt:on/off is for. So trying to introduce heuristics to format lists in many different ways is perhaps complexity black should not have,

**Comment by iago-lito** [comment]
Maybe a simple threshold would be enough? Like "`wrap to one line per item` iif the `wrap to the fewest lines needed` would make the max number of items per lines less than \<N>" with N=5 or 6?

This way we would have:
```python
numbers = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 1, 2 ,3 ,4,
           5, 6, 7, 8, 9, 10, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
```
with longest line containing 16 items > N, but since

```python
long_items = ["long_item_number_1", "long_item_number_2",
              "long_item_number_3", "long_item_number_4"]
]
```
has longest line only 2 items long < N, it would becomes

```python
long_items = [
    "long_item_number_1",
    "long_item_number_2",
    "long_item_number_3",
    "long_item_number_4",
]
```
instead?

**Comment by PravinthR** [comment]
I'm going to try and work on this issue. My solution will split the list on the least amount of lines possible while meeting the pycodestyle standards, similar to what @iago-lito suggested.

**Comment by joaoe** [comment]
Btw, this is not black's style
```
array = [ 1, 2, 3
          4, 5, 6
]
```
This is
```
array = [
    1, 2, 3, 4, 5, 6
]

**Comment by iago-lito** [comment]
@PravinthR Splitting to "the least amount of lines possible" leads to transforming

```python
long_items = [
    "long_item_number_1",
    "long_item_number_2",
    "long_item_number_3",
    "long_item_number_4",
]
```

into

```python
long_items = ["long_item_number_1", "long_item_number_2",
              "long_item_number_3", "long_item_number_4"]
```
.. right? I think we want it the other way round :\

**Comment by PravinthR** [comment]
@iago-lito good point, I forgot to add that I'd be following your idea of fewest line constraints in my implementation (where if splitting to the least amount of lines possible results in < N lines, then it will just put each item on a separate line)

**Comment by saroad2** [comment]
I kind of like the way *Black* format list at the moment, but I agree that once you have a long list, it should wrap it.

In order to achieve that, I suggest adding a `--list-line-length` variable that indicates what is the maximum number of items that should be on each row. By default, this is set to `1` (keeping the existing behavior of *Black*)

For example:

Runnin `black --list-line-length=8` on:
```python
a = [1, 2, 3, 4, 5, 6, 7]
b = [1, 2, 3, 4, 5, 6, 7, 8]
```
Would keep it the same, but running on:
```python
c = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]
```
Would format it into:
```python
c = [
   1, 2, 3, 4, 5, 6, 7, 8,
   9, 10, 11
]
```

What do you think?

**Comment by iago-lito** [comment]
@saroad2 Would this interact with [this former suggestion](https://github.com/psf/black/issues/1281#issuecomment-593399476)? Or should only one be picked?

**Comment by saroad2** [comment]
@iago-lito If I understand you correctly you suggest going the other way around: Wrap in one line as many elements as you can, and split to different lines if the number of elements is too small?

**Comment by iago-lito** [comment]
@saroad2 Yes. I am not sure the two ideas are completely opposite, tought :) For instance (correct if I'm wrong), with the min-max N=8, the following
```python
long_items = [
    "item_n_1", "item_n_2", "item_n_3", "item_n_4", "item_n_5", "item_n_6", "item_n_7",
    "item_n_8", "item_n_9", "item_n10",
]
```
is not good, because it only has 7 items on its longest line,
so it would be reformatted to:
```python
long_items = [
    "item_n_1",
    "item_n_2",
    "item_n_3",
    "item_n_4",
    "item_n_5",
    "item_n_6",
    "item_n_7",
    "item_n_8",
    "item_n_9",
    "item_n10",
]
```
if `--list-line-length=1`, but to 
```python
long_items = [
    "item_n_1", "item_n_2",
    "item_n_3", "item_n_4",
    "item_n_5", "item_n_6",
    "item_n_7", "item_n_8",
    "item_n_9", "item_n10",
]
```
if `--list-line-length=2`, right?

Put it another way, I see the \<N\> solution useful to decide whether or not to split into many lines, and the `--list-line-length` option useful to decide how many items per line to have then.

---

I'll formulate this yet another way. Let us first distinguish between the line "length" (number of characters) and the line, say, "weight" (number of items).

- If all items fit in one line, then keep as-is, to encourage
```python
small_list = ["a", "b", "c"]
```
- If items don't all fit in one line, then the line is too "heavy".
- As a first attempt to solve it, **wrap into heavy lines**, *i.e.* as few lines as possible.
- If the heaviest resulting line is heavy enough (N items at least), then keep as-is to encourage

```python
numbers = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 1, 2 ,3 ,4,
           5, 6, 7, 8, 9, 10, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
```
- But if the heaviest resulting line is too light (less than N items long), then:
- Naively **wrap into light lines** instead, *i.e.* as many lines as possible. And each line (but the last one) is exactly `--list-line-length`-long. This is to encourage either
```python
long_items = [
    "item_n_1",
    "item_n_2",
    "item_n_3",
    "item_n_4",
    "item_n_5",
    "item_n_6",
    "item_n_7",
    "item_n_8",
    "item_n_9",
]
```
(by default), or
```python
long_items = [
    "item_n_1", "item_n_2",
    "item_n_3", "item_n_4",
    "item_n_5", "item_n_6",
    "item_n_7", "item_n_8",
    "item_n_9",
]
```
depending on user's preferences.

What do you think?

---

(As a personal position, I suspect I would always prefer `--list-line-length=1` for it eases reordering. But this opinion may not be shared.)

**Comment by saroad2** [comment]
Your breakdown of the process is awesome! It is really making sense of everything.
Hope this would give the owners a few ideas for the future.

**Comment by AlexVillarra** [comment]
Any updates? I think this feature is a great idea, I've been struggling with some arrays splitting into a lot of ugly lines =(

**Comment by PetrochukM** [comment]
For machine learning code, I'd love to see this added to `Black`! In ML, there are a lot of arrays with lists of numbers and it'd be awesome to have a compact formatting!

**Comment by ichard26** [comment]
More possibly interesting discussion: https://github.com/psf/black/issues/2006

**Comment by felix-hilden** [comment]
We'll not be supporting this style unfortunately.

**Comment by ichard26** [comment]
Just to elaborate a bit more into why, this would introduce another way to tweak Black's style and that goes against the goals of the project. If there's a way to make this work without introducing another option, we could maybe discuss it further but we are also hesistant to rely on pre-existing formatting as it's unconsistent and unstable.

**Comment by iago-lito** [comment]
@ichard26 One way to make it work without introducing another option is to set a hardcoded value for that option, right?

**Comment by harmbuisman** [comment]
The current formatting rule changes a single too long line to a huge amount of lines. This is suboptimal for coding purposes, since it limits the navigation possibilities in my editor. It is harder to scroll through the file as the resolution of the scroll bar goes down inversely with the amount of lines. I guess the reason why this formatting rule is there is readability of the arguments in a method call, but in this case it actually go against the readability of the file itself. 
I would like to have an option to overrule this behaviour and instead be able to set it to "least lines possible, while preserving max line length".

E.g. what @iago-lito suggested would then be the output, which to me in most cases is not a problem:
long_items = ["long_item_number_1", "long_item_number_2",
              "long_item_number_3", "long_item_number_4"]

Thanks for considering.

**Comment by ip1981** [comment]
> So trying to introduce heuristics to format lists in many different ways is perhaps complexity black should not have

Note that GNU fmt (in general) and GNU indent (for C) both have such heuristics.

**Comment by danielcs88** [comment]
This is the only pain point I have with Black. Everything else is flawless. My workaround is a bit consulted, but here goes.

1. I minify the long list using a Minifier, I use [Python Minifier](https://python-minifier.com/) and I untick **Hoist Literals**, **Rename Locals**, and **Rename Globals**.
2. I paste the one line into my Python file or a random Python file.
3. I run [`yapf`](https://github.com/google/yapf) on the file to get the list nice and neat.
4. Lastly I paste the tag `fmt: off` before the neat list and `fmt:on` afterwards.

Yes this is too much work, but at least it gets it done.
