### ISSUE TITLE
Black produced code that is not equivalent to the source...

### ISSUE THREAD

**Issue by oefd** [psf/black#1287]
**To Reproduce** Steps to reproduce the behavior:

1. Take this minimal example

```python
(
    #
    x  # type: ignore
)
```

2. Run _Black_ on it 
3. See error

- Version:  19.10b0
- OS and Python version: Linux/Python 3.8.1

**Does this bug also happen on master?**

Yes. https://black.now.sh/?version=master&state=_Td6WFoAAATm1rRGAgAhARYAAAB0L-Wj4ABqAExdAD2IimZxl1N_WhQxS683ClvyBavv4tSaxAL4IV3VBMlRqqX_lEYQQZnJZ5BtKF-lTOZpqfjc_-YyzSQI57qN_mzLNRO-RIm4IT45L7kArvFYDO6bkbwAAWhrVOzCVx-2830BAAAAAARZWg==

**Additional context** Add any other context about the problem here.

As far as I can tell the second comment has to be `# type: ignore`

**Comment by williamfzc** [comment]
after a quick view, I think it was caused by some rules conflict. Error started from here:
https://github.com/psf/black/blob/991f19031cc66dbaa62384a6f7387a3db5c58335/black.py#L798

if your code is:

```
(
    #
    x  #
)
```

it should left unchanged. But if you add type ignore tag, result of split_line will become:

```python
(
    # x  # type: ignore
)
``` 

Obviously it is wrong. Maybe I will create a PR to fix this when I am not so busy ...
You can check the rules here: https://github.com/psf/black/blob/991f19031cc66dbaa62384a6f7387a3db5c58335/black.py#L2446
