### ISSUE TITLE
Black doesn't delete trailing comma in function args list when it could to save newlines

### ISSUE THREAD

**Issue by Mattwmaster58** [psf/black#1298]
**Describe the style change** Black will currently (`master` branch at the time of writing) not elect to  remove useless (IMO) trailing commas where they could save 2 newlines when the comma causes the line to exceed the line length limit. 

**Examples in the current _Black_ style**:
Note: these examples don't exceed the line length limit in isolation, but they do with indentations
```python
self._client.send(
    'Runtime.evaluate', {'expression': expression, 'contextId': event['executionContextId']},
)
```

**Desired style** How do you think _Black_ should format the above snippets:

```python
self._client.send('Runtime.evaluate', {'expression': expression, 'contextId': event['executionContextId']})
```

**Additional context** Add any other context about the problem here.

**Comment by davesque** [comment]
Hadn't you intended for the code snippet in the "Desired style" section to look like this?
```python
self._client.send('Runtime.evaluate', {'expression': expression, 'contextId': event['executionContextId']})
                                                         # No trailing comma ----------------------------^^
```

**Comment by Mattwmaster58** [comment]
@davesque You're absolutely correct. Fixed.

**Comment by OJFord** [comment]
I've also hit this several times, but I think the issue is more general (and I'm surprised if an issue on it doesn't exist, but this was the closest I could find): when black formats to a multi-argument function call over three lines*, it doesn't reformat (unless it changes line length agreement as described here) if you add or remove a trailing comma, it's happy with or without.

e.g.

```python
self._client.send(
    shorter, than, OP, butlongenoughforthreelines
)


self._client.send(
    shorter, than, OP, butlongenoughforthreelines,
)
```


\* NB: a style I really dislike, and wish it just put each argument on its own line, but that's not the point

**Comment by JelleZijlstra** [comment]
I think you've hit the _magic trailing comma_, which is now a documented part of Black's style: https://github.com/psf/black/blob/master/docs/the_black_code_style.md#trailing-commas.

**Comment by OJFord** [comment]
I am _very_ happy to read about that! We must be using an out of date version.
