### ISSUE TITLE
Black exceeds maximum line length even if it could easily fit

### ISSUE THREAD

**Issue by aklajnert** [psf/black#1346]
**Black v19.10b0**

[Playground link](https://black.now.sh/?version=stable&state=_Td6WFoAAATm1rRGAgAhARYAAAB0L-Wj4AFXALZdAD2IimZxl1N_WlXnON2nzNKQSFUIrBm6Yf_MOHVNpKZ8fu1UKZ4bQToKtPTBDM_MXd_41lAudhexbpQ34_fWSov0lXnMaMzP6xtbT3E4TkMZEnZJW3g_eWGsQZasPFPhFf04r5q2lo-bvDgaMjzOl3ICf3kLZ1JX0zq5Xw9Aq_rAK_6_yfrnFQbGCDmO6zw6mXzGZlP0GHjG7SXTKCWS2ryMNmYva2COG7UpVsjHya1sza5RiUkKAAAA-8e9tjdiwLoAAdIB2AIAAFEFp0GxxGf7AgAAAAAEWVo=)

## Options

`--line-length=110`

## Input

Longest line: 124 characters.

```python
class Command(BaseCommand):
    def execute(self, project_data):
        enterprise, _ = Enterprise.objects.get_or_create(name=project_data.get("enterprise"))
        project, _ = Project.objects.get_or_create(name=project_data.get("name"), enterprise=enterprise)

```

## Output

No change.

```python
class Command(BaseCommand):
    def execute(self, project_data):
        enterprise, _ = Enterprise.objects.get_or_create(name=project_data.get("enterprise"))
        project, _ = Project.objects.get_or_create(name=project_data.get("name"), enterprise=enterprise)

```

## Expected
```python
class Command(BaseCommand):
    def execute(self, project_data):
        enterprise, _ = Enterprise.objects.get_or_create(
            name=project_data.get("enterprise")
        )
        project, _ = Project.objects.get_or_create(
            name=project_data.get("name"), enterprise=enterprise
        )
```

Even if I'll change the line breaks to fit the desired line length, black changes it back (happens also on master).

**Comment by ichard26** [comment]
According to Visual Studio Code and Notepad++, the longest line in the example you provided is 105 characters long. That would explain why *Black* 'reverts' your changes since `--line-length` is set to `110`.

![codelengthexample_vscode](https://user-images.githubusercontent.com/63936253/80317412-a850be80-87d1-11ea-9156-53442101ea19.png)
![codelengthexample_notepad++](https://user-images.githubusercontent.com/63936253/80317414-ac7cdc00-87d1-11ea-819d-7efe1e1c01ba.png)

**Comment by aklajnert** [comment]
Whoa, I don't know how I did such a mistake. I was sure that the line length was longer. Thanks for pointing that out.
