### ISSUE TITLE
aiohttp-cors dependency

### ISSUE THREAD

**Issue by Alessandro-Barbieri** [psf/black#1365]
The aiohttp-cors dependency is problematic, currently it isn't python3.8 ready but black needs it to run tests.

**Comment by hugovk** [comment]
What's the problem?

aiohttp-cors 0.7.0 is installed and used for Black's tests with Python 3.8:

* https://github.com/psf/black/runs/614035867?check_suite_focus=true

**Comment by Alessandro-Barbieri** [comment]
The problem is that aiohttp-cors is unmaintained, doesn't officially support python3.7+ and have broken tests in python3.7+

**Comment by JelleZijlstra** [comment]
What's the concrete problem here? Our tests appear to pass with 3.8 and 3.9.

**Comment by Alessandro-Barbieri** [comment]
https://twitter.com/mgorny_gentoo/status/1406910910053093382?s=19

**Comment by ichard26** [comment]
Yes we understand that using a unmaintained dependency is a bad idea, but the thing is that it will be harder to convince us to invest the effort moving blackd to an alternative when to us, it's fine (TM). OK, aiohttp-cors's test suite doesn't pass Python 3.7 or 3.8, etc., but is there any concrete issues for users of blackd because of aiohttp-cors?

**Comment by cooperlees** [comment]
I’m all ears for a proposal to replace it with a maintained dependency and would accept a well tested PR.

Maybe we should write an integration test for the current implementation and then move to a new dependency to ensure minimal risk of missing a key element of functionality.
