### ISSUE TITLE
Bring pylint to its senses with a .pylintrc

### ISSUE THREAD

**Issue by mastergibber** [psf/black#1366]
Black is better than pylint. It solves problems instead of just pointing them out. But pylint whines whenever black makes better choices. Can we get a sample .pylintrc file that will make pylint accept the wisdom of black's choices?

**Comment by ichard26** [comment]
Oh boy, I haven't used `pylint` for ages, but from some basic research this config should be enough:
```cfg
[MESSAGES CONTROL]

disable=bad-continuation,bad-whitespace

[format]

max-line-length=88
```
A few notes:
1. You should name the file `pylintrc` and not `.pylintrc` since Pylint seems to crash when the latter is present in the current working directory
2. I would recommend running *Black* with `--safe` because *Black* is still a beta product and sometimes makes unsafe code change.

**Comment by sezanzeb** [comment]
> Black is better than pylint

pylint does different things than black.

> It solves problems instead of just pointing them out

black cannot generate docstrings for you, which is what pylint is telling you among many other things
