### ISSUE TITLE
Broken badge, links, and missing maintainer on PyPI project description

### ISSUE THREAD

**Issue by ichard26** [psf/black#1396]
***Mostly likely should be dealt with the next release of _Black_**

Howdy, I was just looking at the [PyPI project description](https://pypi.org/project/black/) for _Black_ because of an unrelated issue and looks like a bit upkeep is due.

1. The PyPI version badge is broken... I think there was a related issue some time back where the readme.md page had a broken badge, can't find it though.
![image](https://user-images.githubusercontent.com/63936253/81437108-9f001400-9138-11ea-8cb2-ac55c051be7d.png)
Regardless, this seems to be the right link for a [non-broken badge](https://img.shields.io/pypi/v/black). 

2. The `More details can be found in CONTRIBUTING` link on PyPI is now a `404 Page Not Found` link. I guess that the best next choice is [this](https://github.com/psf/black/blob/master/CONTRIBUTING.md).

3. Probably not important, but the link for Spyder IDE in the changes section on PyPI and [CHANGES.md](https://github.com/psf/black/blob/master/CHANGES.md/#189b0) is now a dead link. Could be changed to [this](https://www.spyder-ide.org/).

4. Where is @cooperlees on the maintainer list? Here's his [PyPI account](https://pypi.org/user/cooperlees/).
![image](https://user-images.githubusercontent.com/63936253/81438253-724cfc00-913a-11ea-853a-3214b090d831.png)
![image](https://user-images.githubusercontent.com/63936253/81438293-842e9f00-913a-11ea-9f98-069fdf89ef9a.png)

**Comment by hugovk** [comment]
1. will be fixed when Black is next released. It uses the README.md of the release, and the README.md in this repo has a working badge.

2. will happen also in the next release, if nothing is changed, plus the CHANGES link, because they're relative links in this repo which of course don't work at PyPI:

```md
More details can be found in [CONTRIBUTING](CONTRIBUTING.md).

## Change Log

The log's become rather long. It moved to its own file.

See [CHANGES](CHANGES.md).
```

One idea may be to preprocess the Markdown in `setup.py`, detect relative links, and prepend `https://github.com/psf/black`. Or easier, replace them with absolute links. I think the latter makes more sense, and is already done with the licence badge. I'll make a PR for this.

3. Good idea, I'll include it in the PR.

**Comment by ichard26** [comment]
Yeah, I just realized that. Good idea for dealing with bad links; I didn't think about relative links.

**Comment by hugovk** [comment]
Please see PR #1397.

**Comment by ichard26** [comment]
Black `20.08b1` has been released so this is now resolved!

*also yeah a lot my past naivety shows through this issue 😅*
