### ISSUE TITLE
Documentation: git's ignore-revs-file feature

### ISSUE THREAD

**Issue by Cheaterman** [psf/black#1408]
Everything is in the title. I think I first heard of this from Łucasz conference about Black, but then had a very hard time finding the information again when looking on Google (although I did find Łucasz's Tweet on the subject: https://twitter.com/llanga/status/1163767833706323970 )

Can you please make this part of Black's documentation? I think it would put people at ease regarding using Black on older projects.

Thanks!

**Comment by ichard26** [comment]
I am currently working on my rough draft for this. The only roadblock is that I frankly don't know where I would put in the README. Maybe under `Installation and usage` or somewhere near `Version control integration`? Suggestions are welcomed!

---

<details>
<summary>Rough draft</summary>

### Migrating your code style to _Black_

Since `git` version 2.23, git natively supports
[ignoring revisions in blame](https://git-scm.com/docs/git-blame#Documentation/git-blame.txt---ignore-revltrevgt)
with the `--ignore-rev` option. The changes made by the revision will be ignored when assigning
blame. Lines modified by an ignored revision will be blamed on the previous revision that
modified those lines. You can also pass a file listing the revisions to ignore using the
`--ignore-revs-file` option.

So when migrating your Python project's code style to _Black_, just reformat everything with
_Black_ in a single commit. Then put the full 40 characters checksum of that commit into a file
(usually called '.git-blame-ignore-revs' by convention).

```
# Migrate code style to Black
5b4ab991dede475d393e9d69ec388fd6bd949699

# Some other commit to ignore
af0ee6b016ee0f90cabc18b71ced291f6bee18d9
```

Then, you can pass that file to `git blame` and see meaningful blame infomation and not
just a 'reformat commit'.

```shell
$ git blame important.py --ignore-revs-file .git-blame-ignore-revs
7a1ae265 (John Smith 2019-04-15 15:55:13 -0400 1) def very_important_function(text, file, upper_case):
abdfd8b0 (Alice Doe  2019-09-23 11:39:32 -0400 2)     text = text.lstrip()
7a1ae265 (John Smith 2019-04-15 15:55:13 -0400 3)     with open(file, "w+") as f:
7a1ae265 (John Smith 2019-04-15 15:55:13 -0400 4)         f.write(formatted)
```

You can even configure `git` to automatically ignore revisions listed in a file on every
call to `git blame`.

```shell
$ git config blame.ignoreRevsFile .git-blame-ignore-revs
```

The one caveat is that GitHub and GitLab do not **yet** support `--ignore-rev` or
`--ignore-revs-file` in their native UI of blame.

</details>

---

Regardless, I'll finish this once I have some more free time :)

**Comment by Cheaterman** [comment]
Your draft is awesome, thank you! I personally think it's part of
installation and usage, but being git-specific I see how that's
questionable. Thanks again!
