### ISSUE TITLE
Stable docs have broken links

### ISSUE THREAD

**Issue by louwers** [psf/black#1428]
https://black.readthedocs.io/en/stable/version_control_integration.html

"See Black’s own pyproject.toml for an example."

Link is broken.

**Comment by hugovk** [comment]
This has been fixed in the latest version (https://github.com/psf/black/pull/1152):

https://black.readthedocs.io/en/latest/version_control_integration.html

**Comment by zsol** [comment]
Those URLs should probably be rewritten at generation time to point to the actual commit

**Comment by felix-hilden** [comment]
The link is now correct on both `latest` and `stable`. Should this issue be closed?

Besides links to elsewhere on the net, I found references to:
- `docs/compatible_configs`
- `plugin/black.vim`
- `pyproject.toml`
- Stable references to latest docs in "Contributing to Black"
- `src/black_primer/primer.json` and `docs/black_primer`

I'm not sure whether the stable version is intended to reference latest docs, but putting that aside: as all the links reference `master` instead of a single commit and surely the file locations can be assumed to be quite stable, is this situation now resolved?

**Comment by ichard26** [comment]
Well, even if the situation counts as resolved, I'm changing it up (sorry not sorry!) ... :yay:

This is my stance on this situation: 

- Stable docs should not reference latest content unless there's a good reason to (like if the content seen should be the newest possible and isn't dependent on using the latest version of Black, that's okay)
- Documentation should be designed for consumption on ReadTheDocs
  - ReadTheDocs is designed specifically for hosting documentation while GitHub is okay-ish as one. Documentation read on RTD can be a lot more expressive and comprehensive
  - This means that absolute links to GitHub when referencing something in the docs from the docs should be avoided, instead relative links should be used (maintains stable vs latest distinction).

**Comment by ichard26** [comment]
Jelle noticed this was resolved after #2174 landed :)
