### ISSUE TITLE
Support

### ISSUE THREAD

**Issue by tschaub** [psf/black#1481]
It looks like Black has a healthy base of contributors.  In addition to contributing code/docs, is there a way to support Black in being *the* way to (stop having to think about how to manually) format Python?

**Comment by williamfzc** [comment]
... maybe donate? 🤣  (no offense

**Comment by ichard26** [comment]
Given that this falls under the "how can I contribute?" category, something else that would be helpful to this project is **issue traiging**. _Black_ has almost 300 open issues and I bet that there are duplicates and already resolved issues within those three hundred. Or instead of marking issues to be closed, you can try to reproduce the many bug reports we have and add some helpful information. You don't even have to try to debug the issue, a simple "hey, I can repro this" is helpful. And along the way, you'll probably find resolved issues that should be closed.

Regardless, thanks for bringing up the other side of contributing to an open-source project, code and docs aren't everything :)

**Comment by cooperlees** [comment]
Thanks @ichard26 - Totally agree we'd love help getting our duplicate issues down. It would be nice to triage somehow the most seen bug so we can better allocate peoples limited time to fixing the bugs hitting most people. Maybe a known issue / bugs section of github could be handy for that and people could +1. Might be worth requesting that.

Long term tho, lib2to3, which blib2to3 is built on, which black is built on, is [now deprecated](https://bugs.python.org/issue40360). This means eventually black is not going to be able to parse new syntax in > ~3.9 ... So eventually we're going to need to port or rewrite black to "the new parsing library". I'm not 100% as to what that is, but that is going to be a lot of work. So possibly granting via the PSF to help fund that work would definitely help in the not so distant future.

**Comment by hugovk** [comment]
> Thanks @ichard26 - Totally agree we'd love help getting our duplicate issues down. It would be nice to triage somehow the most seen bug so we can better allocate peoples limited time to fixing the bugs hitting most people. Maybe a known issue / bugs section of GitHub could be handy for that and people could +1. Might be worth requesting that.

Perhaps pin the magic comma issue (https://github.com/psf/black/issues/1288), one of the many closed reports about slicing/PEP 8, and perhaps the release issue (https://github.com/psf/black/issues/517)? They come up quite often, and it could help reduce people opening new issues about them.

The slicing one could be mentioned in the bug report template, saying it's not a bug. Or even its own template to show up already at https://github.com/psf/black/issues/new/choose!

**Comment by kamahen** [comment]
> lib2to3

I've written up a proposal to replace lib2to3 with an augmented stdlib ast module:
https://mail.python.org/archives/list/python-ideas@python.org/thread/X2HJ6I6XLIGRZDB27HRHIVQC3RXNZAY4/

(No promises that I'll actually do the work, of course)

**Comment by cooperlees** [comment]
Thanks all for the efforts. We’re trying to cut down the number of open issues. Please comment on or open respective issues if you wish to help!
