### ISSUE TITLE
Matrices(list of lists) should have each row in a new line

### ISSUE THREAD

**Issue by komuw** [psf/black#1484]
**Describe the style change**    
In mathematics it is usual to represent matrices with each ROW in a new line
```
[
  2    1
  4    5
]
```
Python doesn't have a built-in type for matrices. We usually use list of a list as a matrix.   
It would thus be helpful if list of lists was formatted by black with each ROW in a new line.

**Examples in the current _Black_ style** 
```
matrix_A = [[2, 1], [4, 5]]
```

**Desired style (How do you think _Black_ should format the above snippets)**:
```
matrix_A = [
    [2, 1], 
    [4, 5]
]
```

**Additional context** Add any other context about the problem here.

**Comment by hugovk** [comment]
I think this will be covered by the magic comma:

* https://github.com/psf/black/issues/1288#issuecomment-616214207

**Comment by ichard26** [comment]
Closing since the "magic trailing comma" feature is generally usable in version `20.8b1` (i.e. issue #1288 was fixed). Using this feature the desired style can be achieved:

```console
(black) ichard26@acer-ubuntu:~/programming/oss/black$ cat temp.py
matrix_A = [
    [2, 1],
    [4, 5],
]
(black) ichard26@acer-ubuntu:~/programming/oss/black$ black temp.py --diff --color --config tests/empty.toml
All done! ✨ 🍰 ✨
1 file would be left unchanged.
```
<details>
<summary><b>Environment:</b></summary>

* Black version: `stable` (`20.8b1`)
* Python version: `CPython 3.8.5`
* OS version: `Ubuntu 20.04.01 LTS`

</details>
