### ISSUE TITLE
Bad URL String rewrite with many line breaks

### ISSUE THREAD

**Issue by rspadim** [psf/black#1494]
**Describe the style change** A clear and concise description of how the style can be
improved.

the current code is:
```python
url = (
            "https://www.bcb.gov.br/api/servico/sitebcb/bcdatasgs/?" +
            "tronco=estatisticas&" +
            "guidLista=323626f4-c92f-46d6-bac7-55bf88f6430b&" +
            "serie=" + serie_id + "&" +
            "dataInicial=" + start.strftime("%d/%m/%Y") + "&" +
            "dataFinal=" + end.strftime("%d/%m/%Y")
    )
```

**Examples in the current _Black_ style** Think of some short code snippets that show
how the current _Black_ style is not great:

the black version is:
```python
    url = (
        "https://www.bcb.gov.br/api/servico/sitebcb/bcdatasgs/?"
        + "tronco=estatisticas&"
        + "guidLista=323626f4-c92f-46d6-bac7-55bf88f6430b&"
        + "serie="
        + serie_id
        + "&"
        + "dataInicial="
        + start.strftime("%d/%m/%Y")
        + "&"
        + "dataFinal="
        + end.strftime("%d/%m/%Y")
    )
```

**Desired style** How do you think _Black_ should format the above snippets:

the ` + "&"` is too small, maybe concat strings based on a line length could help?
other point... why start line with + instead of use it at last line end?

v1:
```python
    url = (
        "https://www.bcb.gov.br/api/servico/sitebcb/bcdatasgs/?"
        + "tronco=estatisticas&"
        + "guidLista=323626f4-c92f-46d6-bac7-55bf88f6430b&"
        + "serie=" + serie_id + "&"
        + "dataInicial=" + start.strftime("%d/%m/%Y") + "&"
        + "dataFinal=" + end.strftime("%d/%m/%Y")
    )
```

v2:
```python
    url = (
        "https://www.bcb.gov.br/api/servico/sitebcb/bcdatasgs/?" +
        "tronco=estatisticas&" +
        "guidLista=323626f4-c92f-46d6-bac7-55bf88f6430b&" +
        "serie=" + serie_id + "&" +
        "dataInicial=" + start.strftime("%d/%m/%Y") + "&" +
        "dataFinal=" + end.strftime("%d/%m/%Y")
    )
```

**Additional context** Add any other context about the problem here.

when the line is too small maybe could be possible merge with the next line? or the previous one

thanks !

**Comment by ichard26** [comment]
Hi @rspadim! Thank you for bringing this up. 

The main reason why _Black_ breaks before operators is because of [PEP 8 suggests](https://www.python.org/dev/peps/pep-0008/#should-a-line-break-before-or-after-a-binary-operator) to do so.
> Following the tradition from mathematics usually results in more readable code:
>
> ```py3
> # Correct:
> # easy to match operators with operands
> income = (gross_wages
>          + taxable_interest
>          + (dividends - qualified_dividends)
>          - ira_deduction
>          - student_loan_interest)
> ```

As stated in PEP 8, this improves readability in two ways:
1. The operators are at consistent column value
2. Each operator is no longer moved away from its operand and onto the previous line

I agree that with your example the Blacken URL string isn't ideal since the different string literals don't match one-on-one with different URL sections. _Black_ actually already merges string literals that together fit the line length, but it only merges implicitly concatenated string literals and not explicitly concatenated strings. Implicitly concatenated string literals works like explicit concatenation (the add/plus operator). 

These two are equivalent:
1. `test = "hello" "world"`
2. `test2 = "hello" + "world"`

_Black_ can't merge explicitly concatenated strings since string objects (different from string literals - someone can @ me if I am using the wrong terminology) only support explicit concatenation. You can't do `test = string1 string2`. Python will throw a `SyntaxError` if you do try... and _Black_ can't be going breaking people's code ;) Admittedly, AFAIK it is safe to turn explicitly concatenated string literals to implicitly concatenated string literals without any breaking or performance changes, but _Black_ currently doesn't.

Also _Black_ doesn't touch manually split strings as long they don't violate the line length. Even if you remove the unnecessary operators you will get string literals that can be merged still:
```diff
(black) richard-26@ubuntu-laptop:~/programming/black$ black test.py --diff --color
--- test.py	2020-06-12 21:08:24.294936 +0000
+++ test.py	2020-06-12 21:08:27.447028 +0000
@@ -1,8 +1,11 @@
 url = (
-            "https://www.bcb.gov.br/api/servico/sitebcb/bcdatasgs/?"
-            "tronco=estatisticas&" 
-            "guidLista=323626f4-c92f-46d6-bac7-55bf88f6430b&"
-            "serie=" + serie_id + "&" 
-            "dataInicial=" + start.strftime("%d/%m/%Y") + "&" 
-            "dataFinal=" + end.strftime("%d/%m/%Y")
-    )
+    "https://www.bcb.gov.br/api/servico/sitebcb/bcdatasgs/?"
+    "tronco=estatisticas&"
+    "guidLista=323626f4-c92f-46d6-bac7-55bf88f6430b&"
+    "serie="
+    + serie_id
+    + "&dataInicial="
+    + start.strftime("%d/%m/%Y")
+    + "&dataFinal="
+    + end.strftime("%d/%m/%Y")
+)

```

---

Since _Black_ already merges string literals, that resolves your main feature request. For your situation and similar ones, I would recommend one of the following two different solutions:

1. Use `# fmt: on/off`. Instead of modifying your code, just tell _Black_ not to format that section of code. You can do it by:
```py3
# fmt: off
url = (
            "https://www.bcb.gov.br/api/servico/sitebcb/bcdatasgs/?" +
            "tronco=estatisticas&" +
            "guidLista=323626f4-c92f-46d6-bac7-55bf88f6430b&" +
            "serie=" + serie_id + "&" +
            "dataInicial=" + start.strftime("%d/%m/%Y") + "&" +
            "dataFinal=" + end.strftime("%d/%m/%Y")
    )
# fmt: on
``` 

2. Use f-strings. f-strings are the cool new way to mix string literals and string objects. They are fast and more readable IMO.
```py3
url = (
    f"https://www.bcb.gov.br/api/servico/sitebcb/bcdatasgs/?"
    f"tronco=estatisticas&"
    f"guidLista=323626f4-c92f-46d6-bac7-55bf88f6430b&"
    f"serie={serie_id}&"
    f"dataInicial={start.strftime('%d/%m/%Y')}&"
    f"dataFinal={end.strftime('%d/%m/%Y')}"
)
```

 And because _Black_ doesn't touch manually split string literals (or f-strings) (most of the time), you get to keep your code formatted as is :)

**Comment by rspadim** [comment]
wow! thanks a lot, i will test the fmt and f"", i think f"" is nice

i have one doubt about f, 

`f"dataInicial={start.strftime('%d/%m/%Y')}&"`

could it use " inside function? like

"f"dataInicial={start.strftime("%d/%m/%Y")}&""

sorry i didn't read the python docs about f, but i think i have the answer here :) , maybe the f"" doubt could help someone else

**Comment by rspadim** [comment]
found here, thanks!

https://www.python.org/dev/peps/pep-0498/

**Comment by ichard26** [comment]
You can use f-strings anywhere but with a few exceptions:
1. backslashes cannot be present in the f-string expressions... so inside of `{}`. You will have to  evaluate the expression beforehand and using the result in the f-string:
2. comments cannot be present in the f-string expressions
3. be careful not to use the same quotes to delimit your f-strings and inside your f-strings (this is also good advice for strings in general)

I would recommend this article to get up to speed using f-strings:
https://realpython.com/python-f-strings/
