### ISSUE TITLE
param for maximum allowed errors

### ISSUE THREAD

**Issue by BBurke16** [psf/black#1555]
We're late to implement black, but it'd be nice to enforce it at as part of a ci/cd process

Could something equivalent to maxViolations for checkstyle be added?

I did think through a work around that I could just filter on modified files only and not allow violations but it made there, but it'd be nice to streamline it with something cleaner like maxViolations

**Comment by ichard26** [comment]
The problem is that Black at its core isn't a linter. It's a formatter that has no true sense whether something is poorly formatted or well formatted. All it knows is how to turn code into well formatted code. The number of lines changed would probably be the best value you could get out of Black and given that Black can output a diff already, adding a new option for this seems a bit much.

**Comment by BBurke16** [comment]
Odd thing to respond to on Christmas ☃️🎄

But thanks all the same, was just a use case that seemed obvious to me.

If I could do black . Max=12 

It would be useful in my automation, it's be even more useful if editing files outside of my immediate teams editing ability

**Comment by JelleZijlstra** [comment]
I agree with @ichard26 that this doesn't really make sense for Black. It doesn't produce a set count of violations, it reformats the whole file.
