### ISSUE TITLE
Black under Windows

### ISSUE THREAD

**Issue by MartinThoma** [psf/black#1558]
**Describe the bug** After installing black, I couldn't run black. It says `'black' is not recognized as an internal or external command, operable program or batch file.`

**To Reproduce** Steps to reproduce the behavior:

1. Install Python 3.8.5 for Windows 10 via the Installer: https://www.python.org/downloads/ 
2. Run `python -m pip install black`
3. See error

**Expected behavior** Have the standard black output (e.g. "No Path provided. Nothing to do 😴 )
**Environment:**

- Version: 19.10b0 installed via pip
- OS and Python version: Windows 10 and Python 3.8.5

**Comment by MartinThoma** [comment]
I'm new to Windows and I don't have this problem on Ubuntu / the Linux subsystem for Windows. It might be that I do something wrong in the "native" Windows approach.

**Comment by cooperlees** [comment]
This definitely works in our CI on Windows. So please take a look there and compare how we run it to what you're doing: https://github.com/psf/black/runs/876191320.

**Comment by ichard26** [comment]
Here's a random guess. Thankfully on Windows, you should only have to deal with one Python version since there is no system Python so that makes it easier. Assuming that the console_script script created by setuptools is okay, the script is probably off user path. Let's try to fix that:

(**warning: I am primarily an Ubuntu user so these steps may not work**)

1. Open a CMD window
1.5 (I forgot a step and I don't want to redo the numbering) run `echo %path%`, remember the output, we will need to check if we messed up or not
2. Locate your Python installation with `where python`
3. Look at the path listed. If there's one with "Microsoft\WindowsApps", ignore that, you said you installed Python using the Python.org installer, not through the Windows Store. The other listing should be the one we will use, it should be something like 
`C:\Users\User\AppData\Local\Programs\Python\Python38\python.exe` with "user" replaced with your Windows username and "Python38" replaced with your installed Python version. If you don't see a path listing that is similar, then you either did a system install or installed to a custom path. In that case, my steps will probably not work.
4. After you have verified you have the right path. Copy it to your clipboard, removing the `\python.exe` part (don't forget the little backslash)
5. Run `dir your_copied_path` (Example: `dir C:\Users\User\AppData\Local\Programs\Python\Python38`)
6. In the output, check that there is a "Scripts" directory. If not, well skip the next step
7. Now knowing there is a "Scripts" directory present, let's add it your user PATH environment variable. Do `set path=%path%;your_copied_path` with `\Scripts` added to the end of your pasted path. (Example: `set path=%path%;C:\Users\User\AppData\Local\Programs\Python\Python38\Scripts`)
8. Run `dir your_copied_path` with "\Local\Programs\Python\Python38" removed at the end and then add `Roaming\Python\Python38` (`Python38` replaced with your Python version). Also copy this new path that you passed to `dir`
9. Like step 6, check if there's a `Scripts` directory, if not, skip the next step
10. Like step 7, add it to your user path using `set path=%path%;your_newly_copied_path` with "\Scripts" added to the end. (Example: `set path=%path%;C:\Users\User\AppData\Roaming\Python\Python38\Scripts`)
11. Try `black --version`
12. Compare the output of `echo %path%` to what you recorded in step 1.5, **if the newer output is smaller, well, stop doing these steps because we messed up.** (don't worry, just open a new CMD and everything will be reverted)
13. If everything is good, redo step 7 or/and 10 but with `setx` (you might need an elevated CMD prompt)
14. You're done, hooray

**Comment by ichard26** [comment]
Also, for the time being, just try `python -m black --version`, you can skip trying to fiddle around with PATH environment variables if you;re okay with `python -m [insert module]`.

**Comment by mcsitter** [comment]
You could also install python with the package manager [chocolatey](https://chocolatey.org). Quirks in installing programms are usually dealt with quite well! Python is one of the supported packages of course.

**Comment by felix-hilden** [comment]
As a Windows user I can confirm that there should be nothing inherently buggy about this. The "bug" label is a bit misleading. Perhaps "support" instead if this discussion still needs to continue! I'd say make sure your scripts directory is on PATH and you should be good to go. Any luck so far?

**Comment by MartinThoma** [comment]
As I typically don't work on Windows, this bug doesn't really affect me. I'd be ok if it was closed. I've supported a couple of students with this part.

> make sure your scripts directory is on PATH

Yes, that is the crucial point. Maybe less of a black topic and more of a general Python (or Python + Windows) topic :+1: 

## Work-Around

In general when you don't find scripts installed via `pip`, you typically can do this:

```
python -m black
```

It will look for the module black and execute the [`__main__.py`](https://github.com/psf/black/blob/main/src/black/__main__.py).
