### ISSUE TITLE
Prefer one line function definition even in the presence of a trailing comma

### ISSUE THREAD

**Issue by omry** [psf/black#1636]
**Is your feature request related to a problem? Please describe.** A clear and concise

20.8 changes the behavior of handling a trailing comma.

I somehow ended up with many trailing commas, I am not sure these were added by some previous version of Black.
for example:
```python
def foo(
    name="foo", node={"a": 10}, provider="this_test",
):
    ...
```
Black 19.10 did not touch this, but black 20.8 formats it to:
```python
def foo(
    name="foo",
    node={"a": 10},
    provider="this_test",
):
    ...
```
Looking at the formatting result for my project I would personally prefer buck to compact into a single line even in the presence of a trailing comma if it can fit in a single line.
In other words, I would prefer this as the formatting of the first code block:
```
def foo(name="foo", node={"a": 10}, provider="this_test"):
    ...
```

**Describe the solution you'd like** A clear and concise description of what you want to
happen.

Change Black to prefer one line if the function definition can fit in one line, even in the presence of a trailing comma in the last variable.

**Describe alternatives you've considered** A clear and concise description of any
alternative solutions or features you've considered.

I could incrementally remove all the trailing commas from my project.

**Additional context** Add any other context or screenshots about the feature request
here.

Example [PR](https://github.com/facebookresearch/hydra/pull/924/files#) upgrading to 20.8.
I spent about an hour manually removing trailing commas but I did finish the change.

I totally understand if this was considered and decided against, but I wanted to raise this preference.
Thanks.

**Comment by ambv** [comment]
Thanks for your report.

Black 19.10b0 added some extraneous trailing commas, yeah, sorry for that. But the current behavior is what was intended all along: when there is a trailing comma, explode the bracket pair. If you don't wish this behavior, remove trailing commas that would cause the lines to get split.

**Comment by tstraley** [comment]
@ambv based on https://black.readthedocs.io/en/stable/the_black_code_style.html#trailing-commas

> Unnecessary trailing commas are removed if an expression fits in one line.

So shouldn't black 20 be removing these rather than exploding when unnecessary?

**Comment by hugovk** [comment]
Black 20 doesn't know if they were added:

a) by Black 19 by mistake,

or 

b) by a human who intentionally put them there and is expecting their lists of params to grow.

**Comment by omry** [comment]
For people with a large code-base, it would help if Black was able to assist in cleaning up the mess created by Black 19.

A possible solution is a flag to force removal of ALL unnecessary trailing commas under the assumption they are all added by mistake.
People can just re-add the commas later in cases where it was intentional.
```
black --remove-unnecessary-trailing-commas
```

**Comment by tstraley** [comment]
I suppose I'm not clear on why this is the preferred behavior over what had been documented for previous versions. If it fits on one line, black could collapse it down to one line and remove the trailing comma, no? 

Now, I'm curious what happens if I add something that causes it to go beyond the line length limit. Does black expand onto multiple lines and ADD the trailing comma despite the user intentionally leaving it off?

What about if I remove several arguments and it now fits on a single line? I need to also remove the trailing comma in order for black to even try to fit that on a single line? It seems like in one workflow we expect black to manage the trailing comma, and in the other workflow we want the user to explicitly manage the trailing comma to tell black what to do, which is not intuitive.
