### ISSUE TITLE
"--diff" option doesn't add a newline at the end of the file using 20.8b1

### ISSUE THREAD

**Issue by kimadeline** [psf/black#1662]
**Describe the bug**

Running `black --diff` on a file without an ending newline will not add it to the diff when using 20.8b1.

**To Reproduce** Steps to reproduce the behavior:

1. Take this file:
```py
monday_temperatures = [9.1, 8.8, 7.5]
print(len(monday_temperatures))
```
2. Run `black --diff myfile.py`
3. Observed output:

```powershell
PS C:\Users\kimiguel\Documents\Sandbox\black-newline> black --diff .\myfile.py
would reformat myfile.py
All done! ✨ 🍰 ✨
1 file would be reformatted.
```

**Expected behavior**

For `black --diff` to add a newline at the end of the file in the diff, which was the behaviour in 19.10b0:

```powershell
PS C:\Users\kimiguel\Documents\Sandbox\black-newline> black --diff .\myfile.py
--- myfile.py   2020-08-31 22:20:31.166889 +0000
+++ myfile.py   2020-08-31 22:34:25.251541 +0000
@@ -1,2 +1,3 @@
 monday_temperatures = [9.1, 8.8, 7.5]
 print(len(monday_temperatures))
+
reformatted myfile.py
All done! ✨ 🍰 ✨
1 file reformatted.
```

**Environment (please complete the following information):**

- Version: black, version 20.8b1
- OS and Python version: Windows, Python 3.8.5

**Does this bug also happen on master?** 

This also happens on black, version 20.8b2.dev10+g1d2d726.

**Additional context** 

Running `black myfile.py` correctly without `--diff` adds a newline at the end of the file.

**Comment by ichard26** [comment]
Just dropping by to add some information (I honestly have no idea why this was changed and how to make everyone happy):
* Apparently including the newline causes the diff to be unusable for `git apply` and `patch`: #526 
* The following commit is responsible for this behaviour: 959848c17639bfc646128f6b582c5858164a5001

**Comment by TBBle** [comment]
Looking at #526, it seems to me that the diff format being generated for "add a final newline" was incorrect (it was somehow counting the final 0-byte additional line) but the applied solution just hid the problem by dropping the added newline entirely, invalidating the output of `--diff` against `black --check`.

The correct format (per the [Diffutils docs](https://www.gnu.org/software/diffutils/manual/html_node/Incomplete-Lines.html#Incomplete-Lines)) is that an incomplete line is followed by a line starting with `\`, e.g., comparing a file with a copy of itself after `black` is run on it...

```unidiff
$ diff -u file.py  file-fixed.py
--- file.py     2021-01-02 01:56:04.859518400 +1100
+++ file-fixed.py       2021-01-02 01:56:46.597961900 +1100
@@ -1 +1 @@
-# Comment without newline
\ No newline at end of file
+# Comment without newline
```

The fix *should* be as simple as making the call to `splitlines()` be `splitlines(keepends=True)`, since looking at the [difflib docs](https://docs.python.org/3/library/difflib.html#difflib.unified_diff), it expects the newlines in the strings, and hence should be able to report the difference correctly.

Sadly, `difflib.unified_diff` doesn't actually report incomplete lines in the documented format:
```
> py -3
Python 3.6.4 (v3.6.4:d48eceb, Dec 19 2017, 06:54:40) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import difflib
>>> list(difflib.unified_diff(["# Comment without newline"], ["# Comment with newline\n"]))
['--- \n', '+++ \n', '@@ -1 +1 @@\n', '-# Comment without newline', '+# Comment with newline\n']
```

That value needs to be
```
['--- \n', '+++ \n', '@@ -1 +1 @@\n', '-# Comment without newline\n', '\ No newline at end of file', '+# Comment with newline\n']
```

So as well as making it `splitlines(True)`, the result needs to be patched so that any line that doesn't end in `\n` has the `\n` added, and a new element inserted after it with `\ <Some optional text>`.

That should make `git apply` happy.
