### ISSUE TITLE
Reorganize documentation

### ISSUE THREAD

**Issue by JelleZijlstra** [psf/black#1759]
I feel like the current documentation isn't very well organized. It has a lot of pages and it's not obvious where to document things like `.gitignore` support (#1734). Here's the sections we have right now:

![Captura de Pantalla 2020-10-09 a la(s) 2 25 53 p  m](https://user-images.githubusercontent.com/906600/95632854-6348dd80-0a3b-11eb-9c32-7e914d7d28b0.png)

The line wrapping makes it hard to see individual sections, and a lot of them are about fairly minor issues.

Some ideas:
- "Editor integrations", "Version control integration" and "GitHub Actions" should all go into an "Integrations" section
- black-primer isn't really relevant to users (as opposed to developers), it can just be in "Contributing to Black"
- `pyproject.toml` should be renamed to "Configuration" and also cover other ways of configuring Black, like gitignore files and command-line options
- "Ignoring unmodified files" is all about an implementation detail. Maybe it should just go into the "Contributing" section.

Please comment if you have other ideas (or if you think I'm all wrong here and the current organization is fine).

**Comment by J-Exodus** [comment]
I tend to agree @JelleZijlstra. At a minimum, each section title should make it obvious to the reader what content is contained within that section. 
Perhaps a better layout could fall under a more simple structure.  Something such as:
- Overview/Introduction
- Installation
- Configuration
- Integration
- Contribution/Development
- Credits

Transferring to a structure like this should be relatively simple. A good starting point would be allocating all the current sections to one of the new section titles, and then collating those individual sections.

Just my ideas from what I've seen/read.  Thanks.

**Comment by ichard26** [comment]
Okay, I'm picking this up after what seems like *forever*. Apologies for sorta causing this mess in the first place, I didn't really think through what I was doing last time I reorganized the docs. Now it's time for me to fix my mistakes and do it right.

So, I like @J-Exodus's basic structure and I'll be working on transferring our docs to it. I'll post a draft PR when ready.

**Comment by ichard26** [comment]
This is the hierarchy I've been thinking about (**WARNING: IT WILL CHANGE AS I EDIT**) :

```
Overview
Getting Started
  - Installation
  - Usage
  - Using Black with other tools
  - Migrating your project to Black
Configuration
  - Controlling style
  - Controlling file discovery
  - Controlling writeback and reporting
  - Misc.
Integrations
  - GitHub Actions
  - Source Version Control
  - Editors
Development
  - Getting Started
  - Creating Issues
  - Creating Pull Requests
  - Testing
  - Linting
  - Documentation
  - Gauging Style Changes
  - Traiging
  - Reviewing
  - Publishing
Change Log
Credits
```

p.s. I suck at naming things so those section names are up for debate

**Comment by JelleZijlstra** [comment]
@ichard26 that sounds great!

**Comment by ichard26** [comment]
@cooperlees @zsol what do you two think of the general hierarchy I've laid down above? I want do this correctly this time :)

**Comment by cooperlees** [comment]
I like it. I would personally start explaining the "Black Style"
- Also in "Getting Started" I'd love a "Quick Start":
  - pip install black
  - black /path/to/files

**Comment by ichard26** [comment]
>  I would personally start explaining the "Black Style"

Do you mean 'start **by** explaining the "Black Style"' (i.e. move it up) or do you mean we should start justifying why the style is like how it is? (While our style docs are outdated and need some updating, I think they do a decent job at justifying the style choices)

> - Also in "Getting Started" I'd love a "Quick Start":
>   - pip install black
>   - black /path/to/files

I thought it was implied that `pip install black` and `black /path/to/files` are covered via the "covers **installation**, **basic usage**, and next steps" detail, no?

**Comment by cooperlees** [comment]
> > I would personally start explaining the "Black Style"
> 
> Do you mean 'start **by** explaining the "Black Style"' (i.e. move it up) or do you mean we should start justifying why the style is like how it is? (While our style docs are outdated and need some updating, I think they do a decent job at justifying the style choices)
> 

After the "quick start" go straight into explaining the "Black Style" as it's a great source of question / debate etc. etc.
- I'm a big believer in hitting the hot spots as early as possible in docs.

> > * Also in "Getting Started" I'd love a "Quick Start":
> >   
> >   * pip install black
> >   * black /path/to/files
> 
> I thought it was implied that `pip install black` and `black /path/to/files` are covered via the "covers **installation**, **basic usage**, and next steps" detail, no?

Yes - But I just wanted to emphasize that we keep a quick start. I personally dislike projects I have to go digging for the "Quick Start"

**Comment by ichard26** [comment]
I personally would like to keep the "Black Style" and "Getting Started" sections separated to some degree so would moving the "Black Style" section right after "Getting Started" be okay? I was planning to keep "Getting Started" tiny as a single page topic, so I'm struggling to find a place for a "quick start". I guess maybe a small section in the "Getting Started" page in the beginning for like "Hey are you a regular user of Black and want to get started quickly? If so, please read the following section, and if not, please skip." 

fyi, subsections denote whole files so that why "Getting Started" has zero children, it's intended to be single-paged.

**Comment by ichard26** [comment]
actually putting the "Black Style" section after the "Overview" section might make more sense since it's crucial to know how Black is going to format your file when deciding to use the tool or not.

**Comment by cooperlees** [comment]
I want to keep and like the sections. Was just talking about moving. I don't care if you don't to be honest. Lets not make this harder than it needs to be. The fact you're working on this is great.

In the end, do what ever you think is right. No matter what you do there will always be another way with documentation and people can comment and do PRs if they feel strongly moving forward.

**Comment by ichard26** [comment]
Well yeah I get that I can't organize the docs to be perfect for everyone, but you're giving feedback and I should try to incorporate it, especially as a fellow core team member :)

Apologies if my frustration with everything (IRL included) is showing through, I did not intend to brush off your feedback. I think putting some work into a draft then seeing if it reads well with how it's organized according the plan, and then iterating would be best. You are right about a lack of attention to the organization of the content for users. My perspective is from a core team member and maintenance type of guy view point, so thanks for the reminding who these docs are really for :)

**Comment by felix-hilden** [comment]
I don't know about the Sphinx template being used here, and how `.md` is compared to `.rst`, but sectioning the documentation further could also be beneficial. What I mean is dividing the sections themselves into groups. Not clickable documents, but simply sections in the toc tree. For example:

![sections](https://user-images.githubusercontent.com/25202257/113670720-22feab00-96be-11eb-953b-2aa94844eb40.png)

The proposed sections could be divided into:

- Package
  - Overview
  - The Black Code Style
  - Change Log
- Guide
  - Getting Started
  - Usage and Configuration
  - Integrations
  - Common Issues and FAQ
  - Using Black with other tools (or under some common title with "Introducing Black to your project" as originally)
  - Introducing Black to your project (or under some common title with "Using Black with other tools" as originally)
- Development
  - Contributing 
  - Maintenance
  - Credits

Another way of pointing out hotspots could be a kind of introductory paragraph on the home page. Maybe something like:

"The Black code style is described `here`. For dealing with common issues see `FAQ`."

And so on, you get the point. It could mirror the section division, but more verbosely so that the reader doesn't have to guess as much as to where everything is located. Though the proposed structure is very much an improvement! And if there are just a handful of things that you'd like to direct attention to, the paragraph needn't reference every single section.

But I see this has been worked on for quite a while now, so perhaps it would be best to introduce these separately if you decide they're worth doing. How's the reorganizing going?

**Comment by ichard26** [comment]
> How's the reorganizing going?

It's going fine, slow progress but going well. I've been working on and off on for a quite a while as my time is limited and my attention gets pulled to more interesting things. This is how the sidebar looks right now from the local branch right now:

![Screenshot from 2021-04-06 18-02-22](https://user-images.githubusercontent.com/63936253/113783857-67ac3580-9702-11eb-91c9-1152294bedc9.png)

> but sectioning the documentation further could also be beneficial

Unfortunately for the TOC section titles, they IMO look horrible with the theme we have right now:
![Screenshot from 2021-04-06 18-08-11](https://user-images.githubusercontent.com/63936253/113784225-118bc200-9703-11eb-8697-ccb06196c348.png)

I was considering moving the documentation to another theme, like the RtD one or Furo (which handle TOC section titles in a decent way), but given that influences the project's branding, I wasn't looking forward to the discussion needed by that with the rest of the core team. Honestly felt easier to just ignore that debate and work on less controversial changes. Also the spacing between the untitled sections felt like a decent compromise anyway.

In general, I like my structure, although the fact the changelog is at the bottom does rub me in the wrong way. I tried to order the sections to most important to the least important. Users (which make up the biggest reader chunk) will need to know Black's style (especially if they are considering to adopt Black for their project!), then how to use Black is also vital, and so on. After that we have the contributors and core team which is way smaller, so that's why their content is lower. 

While I like your idea to move the changelog up, I don't like your package section. It's not clear to me what such a section would be about. I'll look into the getting started set up you got, I was 50-50 on the "one super duper simple getting started document which is followed by a much more complete document" idea I've got going on. But like other than that, we decided on pretty much the same structure ahaha

> Another way of pointing out hotspots could be a kind of introductory paragraph on the home page. Maybe something like:

:+1: 

In general, thanks @felix-hilden for the feedback and ideas! I'll definitely take them into account if possible.

**Comment by felix-hilden** [comment]
Honestly, that tree looks *so much cleaner* even without section titles. And I agree, they do look horrible in the theme. Combined with the branding argument I don't think it's worth it to start chasing a different theme just for them. The RTD theme has the mobile user friendliness which I don't know how this theme handles, but that also feels minor.

I feel the same about the change log, but if it's not a good fit right at the top with Code Style, then I think down there is the place. I intended the Package section to be all about raw information and no tutorials, other sections then being more verbose in their explanations. But it is quite vague. And yeah that seems like the way to organise it so I'm not surprised that you came up with it as well 😅

Looking good already! [Get that awesome documentation!](https://www.youtube.com/watch?v=UEhr7zL1iWg)

**Comment by ichard26** [comment]
**Status update (to both prove I'm actually going to finish this and also provide some context):**

So far I got all of the content moved over to the new structure, which is the majority of the needed work.

Although there's still a bunch to do:

- Rewrite the README, CONTRIBUTING.md, also the documentation landing page
- Clean up and redo the configuration to use MyST-Parser
- A bunch of tiny todos I littered while I worked:
  - fix broken markup since the move from MD to RST
  - make "Black" \*ed\* since I'm a forgetful monkey
  - check captialization of titles and headings
  - check links (relative vs absolute)
  - finish up my sloppy move to MyST
  - address warnings during build  
- Address ALL OF THE MERGE CONFLICTS (I'm certainly looking forward to this one ... /s)
- Redo the commit history because it's a mess
- Submit a PR and get feedback
- Convince someone to press the green merge buttom :)
- Bask in the glory of better documentation (nah I'm just kidding, I've already got other tasks planned once I am done with this)

**Comment by JelleZijlstra** [comment]
Thanks so much for all your work @ichard26!

**Comment by ichard26** [comment]
If anyone is subscribed to this issue for some reason: I got my PR up now: GH-2174. Go have a look and provide any sort of constructive feedback if you can! Thanks in advance.
