### ISSUE TITLE
Black produced code that is not equivalent to the source

### ISSUE THREAD

**Issue by bjin2364** [psf/black#1844]
**Describe the bug** A clear and concise description of what the bug is.

**To Reproduce** Steps to reproduce the behavior:

1. Down file: [test.py.txt](https://github.com/psf/black/files/5611061/test.py.txt)
2. `black test.py`
3. Fails to format docstring
```
error: cannot format test.py: INTERNAL ERROR: Black produced code that is not equivalent to the source.  Please report
 a bug on https://github.com/psf/black/issues.  This diff might be helpful: /tmp/blk_8rv9ecj9.log
Oh no! 💥 💔 💥
1 file failed to reformat.
```
Error log: [blk_8rv9ecj9.log](https://github.com/psf/black/files/5611063/blk_8rv9ecj9.log)

**Expected behavior**
Successful formatting of docstring

**Environment (please complete the following information):**

- Version: 20.8b1
- OS and Python version: Ubuntu 18.04/Python 2.7

**Does this bug also happen on master?** 
yes

**Comment by komuw** [comment]
I'm able to reproduce this bug with this code;
```python
def my_fxn(id):
    """
    my_fxn does something important.

    id	             string [Optional]	id for ecommerce
    """
    return None
```

**Comment by CiderMan** [comment]
Running `black` on a load of legacy code, I hit this too so I dug into it and have figured out what is wrong and produced a workaround. However, given that I am unfamiliar with `black`, I don't know whether the workaround is OK (if a unit-test were added) of not.

This minimal example that I was able to produce was:
```python
print "Something"

def bar():
    """Testing
    Testing """
    pass
```

The issue seems to be that, when parsing Python 2 (caused, I think, by the use of the `print` statement), the docstring node value ends up being a `bytes` rather than a `str` -- which results in the string normalization not being performed. As the docstring in the example has a trailing space that `black` removes, the equivalence check fails as a result.

Changing the normalization to operate on `bytes` as well as `str`s works around the problem:

```python
            # Constant strings may be indented across newlines, if they are
            # docstrings; fold spaces after newlines when comparing. Similarly,
            # trailing and leading space may be removed.
            if (
                isinstance(node, ast.Constant)
                and field == "value"
                and isinstance(value, (str, bytes))
            ):
                regex = r" *\n[ \t]*"
                replacement = "\n"

                if isinstance(value, bytes):
                    regex = regex.encode()
                    replacement = replacement.encode()

                normalized = re.sub(regex, replacement, value).strip()
            else:
```
However, I'm not convinced that this is the best option - ideally the value should be a `str` for both Python 2 and Python 3 parsing...
I'll let someone who knows `black` better decide the best way forward - though I'm happy to convert this into a PR, if it should be the right thing to do...

**Comment by CiderMan** [comment]
By the way, I wonder if this would now be clearer:

```python
            # Constant strings may be indented across newlines, if they are
            # docstrings; fold spaces after newlines when comparing. Similarly,
            # trailing and leading space may be removed.
            if (
                isinstance(node, ast.Constant)
                and field == "value"
                and isinstance(value, (str, bytes))
            ):
                lineend = "\n" if isinstance(value, str) else b"\n"
                normalized = lineend.join([line.strip() for line in value.splitlines()])
            else:
```

Running timeit suggests that it is about 2.5x quicker too - though this is likely irrelevant since this isn't going to be run too many times...

**Comment by JelleZijlstra** [comment]
Hm, why does Black turn it from bytes to str? That seems itself like a bug.

**Comment by CiderMan** [comment]
> Hm, why does Black turn it from bytes to str? That seems itself like a bug.

Actually, from my reading of the code, I think that it is the other way around. The file being formatted is decoded when it is loaded so I would have expected the docstring to be a str... and this is the case when formatting Python 3 but not when formatting Python 2, it seems. In the latter case, blib2to3 is used to do the parsing so I don't know whether it is a bug in that library or in the way that black is using it...

**Comment by oxr463** [comment]
I used `2to3` to update a file from Python2 to Python3, but it had mixed white space afterwards, which black choked on. I ran the file through the Python interpreter which allowed me to discover the issue. Once I fixed the white space, then I re-ran black and it was happy.
