### ISSUE TITLE
Inconsistent line splitting for long string assignments

### ISSUE THREAD

**Issue by utkarshgupta137** [psf/black#1868]
**Describe the bug** Long string assignments are being split inconsistently

**To Reproduce**
```
>> Input
dummy = "dummydummydummydummydummydummydummydummydummydummydummydummydummydummydummydummydummy"
dummy = "dummydummydummydummydummydummydummydummydummydummydummydummydummydummydummydummy"
```

```
>> Output
dummy = "dummydummydummydummydummydummydummydummydummydummydummydummydummydummydummydummydummy"
dummy = (
    "dummydummydummydummydummydummydummydummydummydummydummydummydummydummydummydummy"
)
```

**Expected behavior**
```
>> Expected
dummy = (
    "dummydummydummydummydummydummydummydummydummydummydummydummydummydummydummydummydummy"
)
dummy = (
    "dummydummydummydummydummydummydummydummydummydummydummydummydummydummydummydummy"
)
```

**Environment:** `black.now.sh/?version=stable` (v20.8b1)

**Does this bug also happen on master?** `Yes, with black.now.sh/?version=master`

**Comment by JelleZijlstra** [comment]
I guess this is because the longer line still exceeds the line limit even if we put it between parentheses, so we don't bother. The `--experimental-string-processing` flag should split up the long string instead. I'm not sure there's anything to do here other than turning on the experimental flag, so I'm closing this issue.
