### ISSUE TITLE
Allow picking a specific black version in the github action

### ISSUE THREAD

**Issue by stefanfoulis** [psf/black#1939]
Sometimes we want to stick with the formatting rules of a specific black version for a little while until we've concluded large PRs to avoid merge conflicts.
The Github action currently does not support picking a specific version of black though.

Suggested solution: Add a parameter for the github action to pick a specific black version.

**Comment by JelleZijlstra** [comment]
Sounds good, a PR would be welcome.

**Comment by youngmit** [comment]
I spent some time trying to figure this out, and largely due to my lack of docker experience am kind of hitting a wall. Has anyone looked into this? It seems that this is caused by the fact that the Dockerfile is just doing `pip install black`, which will fetch whatever is the latest `black` version on pypi, rather than whatever version is being called out in the GitHub action.

This is pretty surprising as it will cause GH actions to just start failing all of a sudden under the same code base whenever Black changes it's rules. Seems like the action should install whichever version is checked out, rather than whatever the latest happens to be.

**Comment by ichard26** [comment]
@youngmit 

There is an open PR fixing this, I have no idea whether it's ready (technically it's still a draft although that might be a holdover from finished development) and I still need to review it: GH-1940.
