### ISSUE TITLE
Black runs from command line but fails when run via pre-commit

### ISSUE THREAD

**Issue by nathanjwtx** [psf/black#1977]
**Describe the bug** A clear and concise description of what the bug is.
When I combine black with pre-commit I receive the error: `Error: Config key target-version must be a list`. However, I can run black directly from the command line with no issue so I'm not sure if this is a problem with black or pre-commit.

**To Reproduce** Steps to reproduce the behavior:

Install pre-commit and black. Add the example `pyproject.toml` file from this repo and a `.pre-commit-config.yaml` file with the following code to a Python project.

```
repos:
-   repo: https://github.com/ambv/black
    rev: stable
    hooks:
    - id: black
      language_version: python3.6
```

Make a commit.

I have tried variations of where to specify the Python version all resulting in the same error.

**Expected behavior** A clear and concise description of what you expected to happen.
Output would match that of the black command run from the command line.

**Environment (please complete the following information):**

- Version: [e.g. master] Master
- OS and Python version: [e.g. Linux/Python 3.7.4rc1]
- Windows 10, Python 3.6.8 (installed with pyenv-win in case that's helpful)

**Does this bug also happen on master?** To answer this, you have two options:
Yes it seems to. (I followed option 2 below)

1. Use the online formatter at https://black.now.sh/?version=master, which will use the
   latest master branch.
2. Or run _Black_ on your machine:
   - create a new virtualenv (make sure it's the same Python version);
   - clone this repository;
   - run `pip install -e .`;
   - make sure it's sane by running `python -m unittest`; and
   - run `black` like you did last time.

**Additional context** Add any other context about the problem here.
For reference I was following this article/tutorial:
https://ljvmiranda921.github.io/notebook/2018/06/21/precommits-using-black-and-flake8/

Edit:
I tried a different version tag, 19.10b0, and I get a different error message:
`Error: Invalid value for '-t' / '--target-version': invalid choice: p. (choose from py27, py33, py34, py35, py36, py37, py38)`

**Comment by ichard26** [comment]
Yeah, the UI ain't great here, target_versions is actually a list of all the Python versions you are looking to support (so if you suppport CPython 3.6 to CPython 3.8 you would denote py36, py37, and py38. I think, there's unfortunately no clear information on how target version ranges work so I could be very wrong!) In your case, your configuration should be something like(I can't find your `pyproject.toml` configuration):

```yaml
[tool.black]
target_versions = ["py36"]
```

Also note that you need a "py" prefix instead of a "python" prefix. The reason why it works on the command line is that our UI code automatically converts a single value into a list (You can actually do something like this `black myfile.py -t py36 -t py37 -t py38`!).

It would probably be better if we also allow a single string value in a configuration file, so I'll open an issue for that (eventually I'm slow and lazy) to gather some more feedback.

Once again, apologies for the terrible UX here, I hope this helps!

**Comment by nathanjwtx** [comment]
I was using the `pyproject.toml` example file from your repo, with just `['py36']` in case I was typing it out incorrectly.

You might not be able to answer this, but if I specify a target Python version in the `pre-commit` hook setup for Black, do I also need to specify it in the `.toml` file?

**Comment by nathanjwtx** [comment]
Oh, also, I was trying to run this via `pre-commit` rather than directly from the CLI. The CLI works as expected.

**Comment by ichard26** [comment]
> You might not be able to answer this, but if I specify a target Python version in the pre-commit hook setup for Black, do I also need to specify it in the .toml file?

No, but I would recommend using the .toml file over the pre-commit hook setup file because the .toml configuration will be used for all usages of Black, not just when Black runs via pre-commit.

Also, `language_version` is a pre-commit configuration, it's not used by Black at all so you'll need to add argument configuration:
```yaml
repos:
-   repo: https://github.com/ambv/black
    rev: stable
    hooks:
    - id: black
      language_version: python3.6
      args: [-t, py36]
```

**Comment by nathanjwtx** [comment]
awesome! thank you for your help. the `args: [-t, py36]` was what did the trick!
