### ISSUE TITLE
Inconsistent across OS

### ISSUE THREAD

**Issue by ishandutta2007** [psf/black#2051]
When I run ```black -t py38 .``` on mac there is nothing to be formatted but the same repo when pulled on windows and ran ```black -t py38 .``` it formats many files.

**Comment by ichard26** [comment]
Hey thanks for the bug report, but we are going to need a lot more information to figure out what is going on:

1. The full output of `black -t py38 . -v`
  Just contains many helpful details like what files are being formatted, skipped, what config is being used, etc. 

2. The contents (or at least the Black-related content) of the configuration file used by the run of Black from the step before.
  The right file can be located using the path provided in the blue line printed at the start of the run: `Using configuration from {PATH}.`. **If there's no blue line, then skip this step since Black isn't using any external configuration.**

3. The tree of the relevant files and directories. 
   With the configuration Black is using, this will let us discover whether it's a file discovery issue (probably different --exclude configurations) or it's something more sinister.

**Comment by ichard26** [comment]
Closing since there hasn't any response from OP for over two weeks. I'm happy to reopen if someone (or the OP) comes with more information.
