### ISSUE TITLE
Two magic commas in one statement don't work as expected

### ISSUE THREAD

**Issue by WhyNotHugo** [psf/black#2083]
This statement should be left as-is (due to magic commands):

```python
        receipts = Receipt.objects.select_related(
            "point_of_sales__owner",
        ).filter(
            receiptpdf__isnull=False,
        )
```

However, black will reformat it to:

```python
        receipts = Receipt.objects.select_related("point_of_sales__owner",).filter(
            receiptpdf__isnull=False,
        )
```

~~I tried the playground, but it fails to parse no matter how I re-write this.~~  Looks like it just didn't like the extra indentation that resulted from copy-pasting out-of-context; it actually reproduces the same issue.

**Comment by ichard26** [comment]
/cc @ambv the magic trailing comma implementation still needs more work :(

Here's the case on master via the [Black Playground](https://black.now.sh/?version=master&state=_Td6WFoAAATm1rRGAgAhARYAAAB0L-Wj4AEEAJxdAD2IimZxl1N_Wlws4TBexXdmg613D2cFOnhBke7afaO_mYNcNSi4eIu9qTaGL1FtL-v5AOrSl1bUMtpShDDmTAfyy6rM2LCQmvuq5gXMmK3Wd4vHIq6Zx3wtMhxPbVp9i3bXN7sTaW-HBvzIx0ZlpHChvzuhpY0DA4fMb36ZWS1tfneuPLYQmTKaHzBdGUnOE_KcTCu5nUSLNPgcuwDRMrva-ADH4gABuAGFAgAAEv6v0bHEZ_sCAAAAAARZWg==).

**Comment by dpalmasan** [comment]
I have been looking into this

```python
receipts = Receipt.objects.select_related(
    "point_of_sales__owner",
)
```

This works fine, but when adding that method call:

```python
receipts = Receipt.objects.select_related(
    "point_of_sales__owner",
).filter(
    receiptpdf__isnull=False,
)
```

We get into the problem of the trailing comma. I also noticed that the line generated and processed by `right_hand_split` is:

`receipts = Receipt.objects.select_related("point_of_sales__owner",).filter(receiptpdf__isnull=False,)`

And thus, due to the parenthesis, the head after the splits is: 

`receipts = Receipt.objects.select_related("point_of_sales__owner",).filter(`

But to get the correct result, maybe for such cases we need to split into two lines, something like:

### Line 1
`receipts = Receipt.objects.select_related("point_of_sales__owner",)`

### Line 2
`.filter(receiptpdf__isnull=False,)`

In that case the parenthesis will be broken correctly for all sentences. I am still getting familiar with the code, so maybe my analysis is not the best. I am trying to create a fix, but not sure when I could be able to do it.

**Comment by WhyNotHugo** [comment]
Is it possible that it's the same issue as  #1795 ?

**Comment by ichard26** [comment]
Yeah after looking at this situation a bit more, my conclusion is that this is just another case of GH-1795. Therefore I'll be closing this as a duplicate. Thanks for noticing, it's hard remembering all of the different issues well enough to be able to tell duplicates at a  glance!

**Comment by WhyNotHugo** [comment]
Thanks for confirming that!
