### ISSUE TITLE
Safety checks are disabled when passing in code using `-c` / `--code`

### ISSUE THREAD

**Issue by ichard26** [psf/black#2104]
I've been writing some docs during my documentation reorganization effort, and I've found myself writing this warning:

> --check, --diff, and --safe / --fast have no effect when using -c / --code. Safety checks normally turned on by default that verify Black's output are disabled as well.

~Is this by design? IMO it seems like an oversight / bug that should fixed.~

edit: yep this is in fact a bug, [thanks Jelle](https://github.com/psf/black/issues/2104#issuecomment-818302531)!

cc @JelleZijlstra @cooperlees

**Comment by JelleZijlstra** [comment]
Seems like a bug to me. I added `-c` to make it easy to test Black's behavior without having to write a file, and testing is harder if it behaves differently from using a file.

**Comment by HassanAbouelela** [comment]
I had a look over this. The code responsible for the `-c` behavior is:
https://github.com/psf/black/blob/b2ee211b5ad84b62738ac0997b73bf6ee9a74d06/src/black/__init__.py#L380-L382

Compared to standard formatting which does:
https://github.com/psf/black/blob/b2ee211b5ad84b62738ac0997b73bf6ee9a74d06/src/black/__init__.py#L406-L412

`write_back` and `fast` are notably missing and causing this bug. They are available at that point in the code, so they could be passed into the function.

The best way to handle this, which minimizes changes and code_repetition is to call `format_file_contents` instead of `format_str`, and add in the logic for write_back.

A sample implementation follows:
```py
    if code is not None:
        then = datetime.utcnow()
        formatted = format_file_contents(code, fast=fast, mode=mode)

        if write_back is WriteBack.CHECK:
            ctx.exit(0 if code == formatted else 1)
        elif write_back in (WriteBack.DIFF, WriteBack.COLOR_DIFF):
            now = datetime.utcnow()
            src_name = f"STDIN\t{then} +0000"
            dst_name = f"STDOUT\t{now} +0000"

            diff_contents = output.diff(code, formatted, src_name, dst_name)
            if write_back == WriteBack.COLOR_DIFF:
                diff_contents = color_diff(diff_contents)
            print(diff_contents)
        else:
            print(formatted)

        ctx.exit(0)
```

I'd like to make a PR for this if this fix seems reasonable.

**Comment by JelleZijlstra** [comment]
Yes, that looks right. A PR would be welcome!
