### ISSUE TITLE
21.4b0 doesn't appear in docs changelog

### ISSUE THREAD

**Issue by adamchainz** [psf/black#2145]
**Describe the bug** 21.4b0 and corresponding changes are missing from https://black.readthedocs.io/en/stable/change_log.html

It seems there are two changelog files, out of sync

https://github.com/psf/black/blob/master/CHANGES.md
https://github.com/psf/black/blob/master/docs/change_log.md

**Comment by cooperlees** [comment]
@ichard26 - Can we delete the read the docs change log for now until you land your refactored docs please?

**Comment by ichard26** [comment]
Sure, I can submit a PR

**Comment by ichard26** [comment]
Well the problem here is two fold:
1. the stable tag is still pointing to 20.8b1
2. `docs/change_log.md` is out of date with the authoritative `CHANGES.md`

The out of date problem doesn't show up on RTD since the generated copies are rebuilt during documentation building, but anyone reading on GitHub will get outdated versions.

I guess deleting the generated changelog isn't too bad of a stopgap anyway.
