### ISSUE TITLE
Question: Should I not be using Mode (FileMode)?

### ISSUE THREAD

**Issue by haxsaw** [psf/black#2256]
It's been suggested to me that Mode (FileMode) is not for 'real world' use for formatting code fragments in memory prior to writing to a file. Besides FileMode being legacy and probably should be replaced with just Mode, is there any reason not to use it in a system where I want to format in memory?

**Comment by felix-hilden** [comment]
If you're referring to the classes inside Black's source, the answer is: you should probably not be using them for formatting of any sort because their implementation (or existence) may change at any time. A public api outside the command line interface is being planned in #779. It would most likely introduce a single function for formatting code as strings.

**Comment by haxsaw** [comment]
That's a shame, but I get it. I'm generating code dynamically and have been using black to format each class as I go (I can see from 779 that I have company). I'll consider my options. Thanks for the swift reply.

**Comment by felix-hilden** [comment]
You're most welcome! Yeah let's hope that the API is introduced soon 😃 until then, I'd not *expect* the implementation to change drastically, but you might want to be careful as always, that's all.

**Comment by JelleZijlstra** [comment]
However, the public API is quite likely to look like `black.format_str(mode=Mode())`. `FileMode` is a deprecated alias for `Mode` I believe (might be the other way around). If I were you, I'd use `format_str()` and be careful the next few times Black makes a release.
