### ISSUE TITLE
INTERNAL ERROR: Black produced different code on the second pass of the formatter.  Please report a bug on https://github.com/psf/black/issues.

### ISSUE THREAD

**Issue by vijayant296** [psf/black#2265]
Can you please suggest on below error while running black:
error: cannot format /home/vijayant/Desktop/phoenix2/phoenix/src/device/deviceconfigserver/deviceconfigsdk_py3/device_sdk.py: INTERNAL ERROR: Black produced different code on the second pass of the formatter.  Please report a bug on https://github.com/psf/black/issues.  This diff might be helpful: /tmp/blk_c0tsf65p.log
Oh no! 💥 💔 💥
1 file failed to reformat.

**Comment by felix-hilden** [comment]
It would be very helpful if you provided some context for the error!

**Comment by vijayant296** [comment]
I am using black to format the python modules. It was working fine. But when i am trying to run black on one of my modules called device_sdk.py, it throwing above error. I have tried several times and also i restarted my IDE but still facing this error. I use below command to run black:
black <path of the file>
Can you please suggest.

**Comment by felix-hilden** [comment]
Black still has some issues in certain formatting cases. This is a generic error that is raised whenever a problem is encountered. If you could look at the diff file (mentioned in the error message) or try to narrow the problem down by editing the file, it would be awesome! Otherwise, just paste the file here if it's not too long.

**Comment by vijayant296** [comment]
ok...will check.
thanks
