### ISSUE TITLE
Blank line after docstring... or not.

### ISSUE THREAD

**Issue by PabloLec** [psf/black#2370]
**Describe the style change**

Currently, black does not check blank lines between functions docstring and body. 
That means both these options are valid:
``` python
def foo():
    """docstring"""
    
   return 0
```

``` python
def foo():
    """docstring"""
   return 0
```

As black is `uncompromising` and `opinionated`, I guess this should be taken into account.

Personally I tend to put a blank line but looking at the only potential reference [PEP 257](https://www.python.org/dev/peps/pep-0257/#one-line-docstrings), there is no blank lines in given examples.

Whether we enforce the blank line or not, black should take care of this as this results in easy style inconsistency.

I'd say we should follow PEP 257 no blank line example.
**Comment your opinion so that this issue can be refered to in a PR fixing this.**

If there is no consensus, we could organize a jousting match to settle this. :goberserk:

**Comment by hukkin** [comment]
Isn't this a case of (referring the docs):
> Black will allow single empty lines inside functions, and single and double empty lines on module level left by the original editors, except when they’re within parenthesized expressions.

So working as intended and documented.

> we could organize a jousting match to settle this

Reasonable proposal, I like this!

**Comment by PabloLec** [comment]
Well, indeed the doc describes this behavior, but I think this should be treated separately.
As on module level, black does not allow beginning blank lines and enforce a final blank line, this same logic should apply at function level.

e.g. this code looks inconsistent and should be reformatted:
``` python
def foo():
    """docstring"""
   return 0

def bar():
    """docstring"""

   return 0

def baz():
    """docstring"""
   return 0
```

**Comment by tolomea** [comment]
I agree and would also like to see Black have an opinion in the case where there is no docstring, my personal preference is no line between function def and first line of the body, but having it take a position one way or the other matters more to me than which position.

echoing @PabloLec this code looks inconsistent and should be reformatted.

```python
def foo():
   return 0

def bar():

   return 0

def baz():
   return 0
```

**Comment by stinos** [comment]
Also: https://github.com/psf/black/issues/1872

**Comment by felix-hilden** [comment]
@tolomea Your suggestion (without the docstrings) is being tracked in #902.

**Comment by PabloLec** [comment]
Just a quick bump, I tried reaching out  and offer help on main communication means a few times within the past months but no response so, yeah.
I guess there are more important matters and blocking issues to consider first but this one seems close to black main purpose to me.
Again, whatever the formatting will be, there need to be some.

**Comment by felix-hilden** [comment]
Module docstrings are already being handled by #2996. It's not a big stretch to start applying that elsewhere as well. We'll just have to agree to do it. And us (potentially) removing the lines in module docstrings would be in line with my preference above.

**Comment by mcnoat** [comment]
I vote for no blank line after the docstring. I discovered this issue, because I was rewriting a file so that it complied with `pydocstyle`'s standards. No matter which docstring style you use (PEP 257, numpydoc or Google), according to `pydocstyle` you should never have a blank line after a docstring. (source: http://www.pydocstyle.org/en/stable/error_codes.html: "No blank lines [...] after function docstring" is error code D202 and it's included in all three style conventions).
I had to manually delete the trailing line for each function and would have loved it if `black` had taken care of it already.

**Comment by YodaEmbedding** [comment]
I know some tools will enforce PEP 257, but for non-tiny functions, it just looks weird to have no blank line, e.g.:

```python
@torch.no_grad()
def inference(
    model: CompressionModel,
    x: torch.Tensor,
    skip_compress: bool = False,
    skip_decompress: bool = False,
    criterion: Optional[TCriterion] = None,
    min_div: int = 64,
    *,
    lmbda_idx: int = None,
    lmbda: float = None,
) -> dict[str, Any]:
    """Run compression model on image batch."""
    if lmbda_idx is not None:
        assert lmbda is None
        lmbda = model.lambdas[lmbda_idx]

    ...
```

versus:


```python
@torch.no_grad()
def inference(
    model: CompressionModel,
    x: torch.Tensor,
    skip_compress: bool = False,
    skip_decompress: bool = False,
    criterion: Optional[TCriterion] = None,
    min_div: int = 64,
    *,
    lmbda_idx: int = None,
    lmbda: float = None,
) -> dict[str, Any]:
    """Run compression model on image batch."""

    if lmbda_idx is not None:
        assert lmbda is None
        lmbda = model.lambdas[lmbda_idx]

    ...
```

**Comment by hauntsaninja** [comment]
As mentioned in https://github.com/psf/black/issues/4043, I lean towards not doing anything here.

I feel that if we do something here, it should definitely not be to always strip blank lines. Doing so would be inconsistent with how Black treats module and class docstrings. It would run in to the same readability issues that has made previous blank line changes controversial (see the comment above, #4043, etc).

**Comment by LLyaudet** [comment]
Since Black has the goal of not allowing too much customization to avoid too many variations out in the nature,
I think the original suggestion to not allow an empty line after function doc string is better:

- it corresponds to PEP257 (DocString)
- I would allow doc strings with either
"""BlaBla"""
or
"""
Blabla
Blabla
"""
In both cases, the separation with code below is clear.
https://github.com/psf/black/issues/2370#issuecomment-1585971000
seems invalid to me.
Because if you have a big function and a small docstring on only one line,
the problem is in your too short docstring.
I would imagine a big function would have some big parts,
each part being synthetized in the docstring like:

"""
My function:
- part 1: blabla
- part 2: blabla
- part 3: blabla
"""

And inside function body:
# Part 1 : Blabla
# Blabla
# Blabla
bla = blabla(x,y,z)
...
# Part 2 : Blabla
# Blabla
# Blabla
bla = blabla(x,y,z)
...

etc.

**Comment by JelleZijlstra** [comment]
I agree with @hauntsaninja above; we'll leave this unchanged.
