### ISSUE TITLE
Format lists as tables

### ISSUE THREAD

**Issue by ee987** [psf/black#2385]
**Describe the style change**

Today with black, lists are either formatted as all elements on one single line, or all elements on a line each. Within the array, no room for alignment is allowed.
I think there are many cases where a middle ground makes more sense, where the data is more tabular or have other useful context. I have two examples where alignment would help readability of both 1D-lists and 2D tables/matrices.

Example 1 is a pattern we see a lot in our code base. From a readability point of view the hand-formatted version is obviously a lot easier to read. Implementation-wise i can foresee it's a bit special in it might require contextual knowledge that elements starting with `"--` are the delimiter for when to word break, or that the parser should pay attention to handmade word-wraps before doing some final formatting-touchup. There are also more edge cases here where some arguments take in several parameters so breaking every second element is not an option.

About example2, one could argue it should be loaded from CSV or a database but i often find occasions where just a small 5-line table in the code could benefit from this style. Maybe that particular example scenario isn't that realistic so focus on the style and not what it does :)

**Examples in the current _Black_ style**

```python
def example1():
    subprocess.check_output(
        [
            "build.sh",
            "--product",
            product,
            "--variant",
            variant,
            "--branch",
            branch,
            "--build_type",
            "release",
        ]
    )

def example2():
    users = [
        UserConfig("User1 Super Root admin", 6, True, "admin", "2021-07-20"),
        UserConfig("User2345fds", 3, True, "user", "2021-07-20"),
        UserConfig("User3", 9, False, "banned", "2021-07-20"),
        UserConfig("User 4 John Doe", 9, False, "user", "2021-07-20"),
    ]
```

**Desired style**

```python
def example1():
    subprocess.check_output([
        "build.sh",
        "--product",     product,
        "--variant",     variant,
        "--branch",      branch,
        "--build_type", "release",
    ])

def example2():
    users = [
        UserConfig("User1 Super Root admin", 6, True,  "admin",  "2021-07-20"),
        UserConfig("User2345fds",            3, True,  "user",   "2021-07-20"),
        UserConfig("User3",                  9, False, "banned", "2021-07-20"),
        UserConfig("User 4 John Doe",        9, False, "user",   "2021-07-20"),
    ]
```

**Comment by felix-hilden** [comment]
Hi, thanks for the suggestion and your interest! I hope you'll be satisfied with the current formatting decisions, because although your examples do read nicer with the formatting you provided, this is not the case with lists and calls in general. Combined with the fact that _Black_ is opinionated and minimally configurable, I don't think this would ever be accepted.

Perhaps, if you're after readability, you could at least use nested lists in the first case and flatten them when making the call. But making such changes just for formatting is up to you 😅 I personally wouldn't bother.

```python
def example1():
    args = [
        ["build.sh"],
        ["--product", product],
        ["--variant", variant],
        ["--branch", branch],
        ["--build_type", "release"],
    ]
    check_output(flatten(args))
```

**Comment by felix-hilden** [comment]
Oh, and you can use `# fmt: off` [comments](https://black.readthedocs.io/en/stable/the_black_code_style/current_style.html?highlight=fmt%20off#code-style) too!

**Comment by ee987** [comment]
Thank you for the response. Just for me to understand, is the decision based on: Opinion that style is not much better?  Style already frozen and minimize diff to existing code bases? Implementation effort would be too big? Or that there are potentially too many edge cases to cover?  If any of the latter, opening up a bit for constructive suggestions of potential ways forward would be nice.
I'm not asking for anything configurable here so minimally configurable and opinionated is perfectly fine.

**Comment by felix-hilden** [comment]
Sure!

Precisely because of the minimal configuration, we need to provide a reasonable style for general use cases. At least I wouldn't be comfortable assuming that when entries like `"--xxxx"` are found that they invariably constitute some sort of argument list. That alone is enough for me, but I bet there would be a *bunch* of edge cases and other opinions we should adopt if this were to be implemented. Additionally, _Black_ does not take previous formatting into account by design.

I hope that seems reasonable to you.

**Comment by ee987** [comment]
Thanks, now also found https://github.com/psf/black/pull/1904 about aligning comments, closed with similar rationale. Understood.
