### ISSUE TITLE
two newlines not added before function definition when there's a comment above it

### ISSUE THREAD

**Issue by DetachHead** [psf/black#2420]
**Describe the bug**

black does not add the two newlines between these two definitions when there's a comment in the way
```py
a = 1
# adsf
def bar() -> None:
    ...
```

this causes the following error in flake8:
```
E302 expected 2 blank lines, found 0
```

**Expected behavior**

```py
a = 1


# adsf
def bar() -> None:
    ...
```

**Environment (please complete the following information):**

- Version: 21.7b0
- OS and Python version: macos 11.4, python 3.10.0b4

**Does this bug also happen on main?**
yes

**Comment by ichard26** [comment]
Hey thank you for the bug report. I see that this has been reported before and is actually a very old bug: GH-246. Looking at the issue, it sounds like it will require complicating the line generation logic a fair bit unfortunately. Anyway since this already has a report, I'll be closing this as a duplicate.

My apologies that this broke for you!
