### ISSUE TITLE
Dockerhub does not have the most recent version

### ISSUE THREAD

**Issue by onerandomusername** [psf/black#2463]
**Describe the bug**

Dockerhub does not have the most recent version, 21.8b0.
**To Reproduce**
View https://hub.docker.com/r/pyfound/black/tags?page=1&ordering=last_updated, notice it is not there.
**Expected behavior**
21.8b0 is on dockerhub

**Environment (please complete the following information):**
N/A
- Version: 
- OS and Python version: 

**Does this bug also happen on main?**
N/A

**Comment by WhyNotHugo** [comment]
Might make sense to add a GH action to publish this, triggered by:

```yaml
on:
  release:
    types: [published]
```

And just rebuild and push the image. However, the current `Dockerfile` uses the latest version from PyPI, and there's not guarantee it will be published first, so it's likely best to use the version in-repo.

**Comment by ichard26** [comment]
This was manually resolved by @cooperlees (thanks!). The underlying problem here was that the workflow trigger event was misconfigured so when I went create-draft-release -> publish-release the workflow didn't trigger. "Created" events from draft releases don't count (that's good!) but unfortunately that means publishing a draft release will never trigger the workflow. This was eventually fixed by GH-2461.
