### ISSUE TITLE
isort removes newlines before standalone comments if the following line is an import of the same group

### ISSUE THREAD

**Issue by gaborbernat** [psf/black#251]
Operating system: Arch Linux
Python version: Python 3.6.6
Black version: 18.5b0
Does also happen on master: yes

Given: 

``` python
import a
# noinspection PyProtectedMember
import _a
```

Black formats this to (note the introduced empty line):

``` python
import a
# noinspection PyProtectedMember

import _a
```

However isort correctly (in the recommended mode 3) formats it to:
``` python
import a
# noinspection PyProtectedMember
import _a
```

**Comment by ambv** [comment]
Black puts an empty line after every group of imports. A standalone comment signifies an end of a group of imports for it.

So, your example is wrong, Black will do this instead with the original file:
```diff
--- /tmp/asd.py  (original)
+++ /tmp/asd.py  (formatted)
@@ -1,4 +1,5 @@
 import a
+
 # noinspection PyProtectedMember
 import _a
```

The behavior between isort and Black is indeed different here. I haven't decided yet how to resolve this.

**Comment by gaborbernat** [comment]
Thanks for the explanation, would be nice to somehow support this use case though.

**Comment by skorokithakis** [comment]
I am affected by this as well :/ Just to clarify, what is the problem here? Is Black wrong, or is isort? Is the newline supposed to be there?

**Comment by tibz7** [comment]
I'm also affected. what is the current status about this bug?

**Comment by thisfred** [comment]
I think black is being too prescriptive here: yes comments between imports can be used as headers, but they can also be things like: 

`# XXX: unused import, that however shouldn't be removed because our noddy framework depends on it`

**Comment by Sharadh** [comment]
Hello @ambv ! Do you have an update on this?
> The behavior between isort and Black is indeed different here. I haven't decided yet how to resolve this.

Perhaps you can talk through your thoughts so we understand if a fix is likely?

Also, re:
> Black puts an empty line after every group of imports. A standalone comment signifies an end of a group of imports before it.

Is there some documentation that describes this behavior? I couldn't find it in [the code style](https://black.readthedocs.io/en/stable/the_black_code_style.html) - I ask because without knowing the reasoning behind this behavior, I find it hard to suggest a way forward. I do find the rest of the decisions well documented, and do a great job of answering my questions and feature requests before I make them ;)

**Comment by Sharadh** [comment]
Does anyone know what the best way to get a contributor's attention here is? I'm happy to submit a proposal + fix, it's just that the radio silence makes me nervous about investing time :)

**Comment by roushan05** [comment]
Any update on this ? What is the current status of this issue ?

**Comment by hugovk** [comment]
This is now fixed in isort by adding a new `ensure_newline_before_comments` option, but it's not yet released: 

* https://github.com/timothycrosley/isort/pull/1000

If you use pre-commit, you can pin to the latest isort commit, like this:

* https://github.com/ibis-project/ibis/commit/ae71b3a96a514ab599d92382bb55fd247803deac#diff-82c3b36709926de3a1b27bea0d8258cc

**Comment by hugovk** [comment]
> This is now fixed in isort by adding a new `ensure_newline_before_comments` option, but it's not yet released: 
>
> * https://github.com/timothycrosley/isort/pull/1000

Looks like isort 5.0.0 is scheduled for tomorrow!

* https://github.com/timothycrosley/isort/commit/2ea917e8dad7116584c0c5927b43f25ca300f819

**Comment by skorokithakis** [comment]
By the way, I have switched to https://github.com/asottile/reorder_python_imports, which doesn't have this problem and runs statically without isort's troubles when the sorted packages aren't installed.

**Comment by ichard26** [comment]
Closing as isort 5 has been released. 

Either use isort 5's profiles of which one is built for Black, or manually configure `ensure_newline_before_comments` to true, although it only works with isort 5 and higher. For more information please [read the documentation for isort + Black compatiblity](https://github.com/psf/black/blob/master/docs/compatible_configs.md#isort).
