### ISSUE TITLE
Crash on fmt:skip with comment inside argument list

### ISSUE THREAD

**Issue by AaronDMarasco** [psf/black#2540]
**Describe the bug**

Crashes on MWE below.

**To Reproduce**

```python
class myclass:
    def run(self):
        while True:
            if True:
                a = something(
                    [],
                    [],  # very important that comment stays here
                    []
                )  # fmt: skip
```

Example at https://black.vercel.app/?version=main&state=_Td6WFoAAATm1rRGAgAhARYAAAB0L-Wj4AFUAK5dAD2IimZxl1N_Wk6rkWpnygC1UpzRuCJHtF5SWbQHSgQi3V5OExVRf3x4qhfiDbRhToSQgYaSdPEqg591IJHGKQ94j-jI1z9atMn-2lC0ezzZHVkKMDn8IDLNWBBU0AwpiQ969gTRFS0VXdA4XUD0YIRpWAoCG6HHgI2E2Vmb1SZ9nrSkJUjG2YUHHsqsbFFj_NP8Wxzqz85nfhZVtvx_7xS0wvq71buOx9qwan9UFgAAANcU4bp3_YmWAAHKAdUCAAB6XUhcscRn-wIAAAAABFla

**Expected behavior**

Formatting should be left alone. At a minimum, it shouldn't crash.

**Environment (please complete the following information):**

- Version: 21.5b2
- OS and Python version: Linux / 3.9

**Does this bug also happen on main?**

Yes

**Additional context**

 * Removing `# fmt: skip` doesn't crash, but moves the comment to end of statement
 * "Skip temporary sanity checks" option with online version **does not crash**
   * Code matches 100% what went in
 * "Stable" online (21.9b0) **does not crash**
   * Bug fixed after 21.5b2 but then reintroduced since stable? Unlikely...
 * Crash dump:
```diff
--- source
+++ first pass
@@ -1,11 +1,9 @@
-
 class myclass:
     def run(self):
         while True:
             if True:
-                a = something(
+                    a = something(
                     [],
                     [],  # very important that comment stays here
                     []
                 )  # fmt: skip
-
--- first pass
+++ second pass
@@ -1,9 +1,9 @@
 class myclass:
     def run(self):
         while True:
             if True:
-                    a = something(
+                      a = something(
                     [],
                     [],  # very important that comment stays here
                     []
                 )  # fmt: skip
```

**Comment by HassanAbouelela** [comment]
Could not reproduce on main or stable, but I did reproduce in 21.5, as you have. I believe this issue is solved, and the only reason you're still experiencing it in the playground is an unrelated playground bug when it comes to main. [Setting the playground to stable produces no errors](https://black.vercel.app/?version=stable&state=_Td6WFoAAATm1rRGAgAhARYAAAB0L-Wj4AFSAKxdAD2IimZxl1N_Wk6rkWpnygC1UpzRuCJHtF5SWbQHSgQi3V5OExVRf3x4qhfiDbRhToSQgYaSdPEqg591IJHGKQ94j-jI1z9atMn-2lC0ezzZHVkKMDn8IDLNWBBU0AwpiQ969gTRFS0VXdA4XUD0YIRpWAoCG6HHgI2E2Vmb1SZ9nrSkJUjCmI5kDnBJy33ufM-gOajBgMEQgeHM0u55YbGHeRw18scLRjcYPuoANy7j6QfogLkAAcgB0wIAAK2j6zSxxGf7AgAAAAAEWVo=).

I'll continue investigating what's up with playground, but for now I'd suggest you update to the latest stable and see if that works.
