### ISSUE TITLE
Unnecessary line breaks in method call on multiline string

### ISSUE THREAD

**Issue by lubomir** [psf/black#256]
This is possibly not a bug, but the results are unexpected and don't really seem to improve readability. However feel free to close if this is actually correct.

Operating system: Fedora 28
Python version: 3.6.5
Black version: 18.5b0
Does also happen on master: yes

Formatting this file uses some extra unexpected new lines:

```python
MULTILINE = """
foo
""".replace("\n", "")
```

```diff
@@ -1,4 +1,6 @@
 MULTILINE = """
 foo
-""".replace("\n", "")
+""".replace(
+    "\n", ""
+)
```

**Comment by ambv** [comment]
Black considers multiline strings as always not fitting a single line (per definition), so it tries to break the line if possible. I agree that in this case the result is sub-optimal. I'll see what I can do to improve this.

**Comment by zsol** [comment]
@AvdN points out another effect of how black treats multiline strings that are styled like this in #426 (in the case when the string is a parameter to a function call)

**Comment by ambv** [comment]
A related case is:
```
textwrap.dedent("""\
    Hello, I am
    a multiline string used with
    a common idiom
""")
```

We need to fix that, too.

**Comment by OJFord** [comment]
That related case is how I got here. For clarity here, the above:
```python
textwrap.dedent("""\
    Hello, I am
    a multiline string used with
    a common idiom
""")
```
becomes:
```python
textwrap.dedent(
    """\
    Hello, I am
    a multiline string used with
    a common idiom
"""
)
```

Amusingly you can instead change it to:
```python
s = """\
    Hello, I am
    a multiline string used with
    a common idiom
"""
s = textwrap.dedent(s)
```
in one fewer lines and which `black` will accept (and won't churn when this is resolved) - or do the `dedent` call at the point of use.

**Comment by brupelo** [comment]
I love black... I really do... but this issue is really nasty... not just because black will breaks code folding completely but also because the output produced by black doesn't make any sense in comparison the original clean version. I find myself adding clauses `# fmt: off` & `# fmt: on` more than I should when that shouldn't be case.

I understand none of the maintainers is interested on this issue? I've see both this one and other related ones have been opened for years... question for people who've submitted patches to black before, do you what's the place in the codebase where this is handled? 

Thanks.

Ps. Why this important issue hasn't been fixed already? Has it been considered a non-go? Too difficult to handle? I'd like to understand... :)

**Comment by FlipperPA** [comment]
This is a big pet peeve for me too. There's information about contributing here, if you're interested, @brupelo:

https://github.com/psf/black/blob/master/CONTRIBUTING.md

**Comment by FlipperPA** [comment]
Some quick questions:

- would the preferred behavior be to leave the original code intact?
- would the preferred behavior be to format all docstrings within parentheses the shorter, more beautiful way?

I'd be happy to take a stab if someone would be willing to do some hand holding along the way, as I'd be a brand new contributor.

**Comment by merwok** [comment]
The point about «liking» is dismissive of more serious concerns.  Single vs double quotes is an annoying change but mostly irrelevant (it was nice to match the style that the Python REPL outputs, but quote style doesn’t matter and there is a point that it’s common to have apostrophe in a string, so :shrug:).  But people care about diffs and history, and the developer is the person best situated to decide if this is an extensible list/dict/set that is multiline from the start, or something that can be rewritten by a style program.  (One of the worst cases is parameters to the pytest.parametrize decorator that are rewritten to waste screen space without benefit.)

**Comment by aneeshusa** [comment]
I kept running into this so I decided to spend some time figuring how to fix it. Happy to say I have a branch that should do just that! It's got a new 316 line test file with a bunch of cases (including the ones reported in this and linked issues). However, the code is still messy as I haven't yet taken the time to clean it up: right now it's ~100 new lines dumped into the `is_line_short_enough` function.  I'll post a draft PR in the next day or two after some basic cleanup, just wanted to comment to let others know if they had been thinking of spending time on this.

FWIW, the branch is more of a POC right now and requires more work before it could be mergeable. I have some hacked-together code for bracket tracking, trailing comma handling, etc., which will require some refactoring so I can reuse the existing functions for that (will need help from the black folks on the best approach). There's also more work to do like finishing up draft changes to the black style guide docs & CHANGES.rst looking through the black-primer output to verify the changes and work with the relevant upstreams.

**Comment by aneeshusa** [comment]
Opened https://github.com/psf/black/pull/1879 with my prototype fix! Would love feedback from folks on the new tests I added and whether the formatting I chose makes sense (AFAIK I included all the examples from this and linked issues).

**Comment by arogozhnikov** [comment]
Just want to bring this up if it is forgotten. 

I think it's the only annoying (and undoubtedly annoying) part of black formatting to me,
specifically examples provided by @ambv and @OJFord : https://github.com/psf/black/issues/256#issuecomment-424790041

Maybe a heuristic like this would work: combinations like `("""` and `""")` shouldn't be split by formatting (if they stick, just don't split them).

**Comment by aneeshusa** [comment]
Some context from me:
- I'm planning to roll out black across all repos at my company (I'm on the languages team at Lyft). Similar to you, this is the only piece of black formatting that I've found annoying enough to consider a blocker since we have a number of repos that use multi-line strings heavily.
- I haven't forgotten about the PR, but unfortunately it has been put on the backburner due to other internal priorities.
I would like to get back to the PR later this year but can't give any guarantees as to when that'll be. In the meantime, I welcome anyone to take over the work and make their own PR!

**Comment by ichard26** [comment]
Worst case scenario is that I take over the PR and try to push it to completion but unfortunately I've been extremely busy lately too so it'll have to wait at least more week before I have time (and even then the core team is busy figuring out the stable release).

**Comment by FlipperPA** [comment]
@ichard26 @aneeshusa Any idea how much more code work the PR needs? Or is it more of someone to shepherd it across the finish line?

**Comment by aneeshusa** [comment]
https://github.com/psf/black/pull/1879#issue-773197836 is still pretty accurate. Here's my take on action items, though I haven't looked at this code or black internals since I opened that PR.
- Looks like there is general consensus on the new formatting style, so checkboxes 1 & 2 are done.
- The code needs to be moved around a bit now that black's source code has been split into multiple files and isn't one giant file - I suspect this would be pretty straightforward to do.
- The current PR adds a bunch of extra work into `is_line_short_enough`, though it's a no-op when not looking at a MLS-containing line. I suspect it'll need to be reworked to use BracketTracker for speed (or at the very least pick up some of the bugfixes it has https://github.com/psf/black/pull/1879/files#diff-d23a6917d7262ca9815093bffb7148299e516575251959ed9b405b648e76aa29R6480 for correctness), but I hadn't gotten far enough to understand what exactly this could/would look like. It's also possible that refactor is is an optimization we could make later - some profiling data would confirm how this affects the performance. This is the biggest open AI as I see it. Advice from maintainers would be very helpful here as well (this is checkboxes 3 and 4).
- Checkbox 5 - adding docs - might require a few iterations to make it clear but should be straightforward.

If, based on profiling and maintainer feedback, the current approach in the PR is mostly acceptable, then it's more of a "take it across the finish". If the approach needs some rework then it'll require more investment depending on what changes are needed.

**Comment by JelleZijlstra** [comment]
Also, with the new stability policy, this change would need to go only into the `--preview` style.

**Comment by aneeshusa** [comment]
Quick update: @olivia-hong who works with me on the Backend Language Tooling team at Lyft is going to be picking this work up again!

**Comment by FlipperPA** [comment]
Thank you @aneeshusa and @olivia-hong! Lyft was the go-to ride of choice for us in San Diego at DjangoCon US a few weeks ago. 😀

**Comment by olivia-hong** [comment]
Posting an update here for visibility as well: I've updated the PR Aneesh originally put up and it's now fully ready for review https://github.com/psf/black/pull/1879#issuecomment-1292668826! Comments/feedback are much appreciated.

Since the issue is a few years old at this point, tagging some of the original reviewers @JelleZijlstra @ichard26 as an FYI. Apologies for any noise.
