### ISSUE TITLE
Docker upload CI is broken

### ISSUE THREAD

**Issue by cooperlees** [psf/black#2568]
Haven't debugged yet but seems a build level bug inside the container. Need to see if it can be reproduced locally.

```
error: failed to solve: process "/bin/sh -c pip install --no-cache-dir --upgrade pip setuptools wheel     && apt update && apt install -y git     && cd /src     && pip install --no-cache-dir .[colorama,d]     && rm -rf /src     && apt remove -y git     && apt autoremove -y     && rm -rf /var/lib/apt/lists/*" did not complete successfully: exit code: 1
Error: buildx failed with: error: failed to solve: process "/bin/sh -c pip install --no-cache-dir --upgrade pip setuptools wheel     && apt update && apt install -y git     && cd /src     && pip install --no-cache-dir .[colorama,d]     && rm -rf /src     && apt remove -y git     && apt autoremove -y     && rm -rf /var/lib/apt/lists/*" did not complete successfully: exit code: 1
```

Example fail: https://github.com/psf/black/actions/runs/1391464711

**Comment by vbarbaresi** [comment]
I opened this issue on regex project: https://bitbucket.org/mrabarnett/mrab-regex/issues/434/aarch64-build-is-failing
I didn't find the Travis build logs last time, but now I finally found them: https://app.travis-ci.com/bitbucket/mrabarnett/mrab-regex/builds
Now that I see the logs I guess that it's probably a fluke in the build

I saw that you pinned `regex` and that it solved the issue for now.

I tried to build after installing `build-essential` and that was enough to solve the issue:

https://github.com/vbarbaresi/black/compare/7bf233a..bb86cd#diff-dd2c0eb6ea5cfc6c4bd4eac30934e2d5746747af48fef6da689e85b752f39557

https://github.com/vbarbaresi/black/runs/4061992219?check_suite_focus=true
Though it took ~12 min to build instead of 4 min, so I don't think it's a good solution.
It would be good as a workaround in case some dependency is missing wheels again

**Comment by cooperlees** [comment]
Thanks for trying this. I think long term we should definitely support building from source but will probably need a multi stage build so we can keep the image size around the current ~50MB ... 

If you/anyone have cycles I'd totally take a PR making us able to build from source via a multi stage build to keep our image size low.

**Comment by vbarbaresi** [comment]
I took a stab at it https://github.com/psf/black/pull/2582
