### ISSUE TITLE
give us tab support, still.

### ISSUE THREAD

**Issue by onlycs** [psf/black#2584]
Look, implementing tabs support is pretty simple and you don't have to make it default. You _literally_ just have to add an option like `--use-tabs` and implement tabs in the code. Prettier does it, pretty much every other code formatted I use at _least_ has an option to use tabs. you can't say that you are "LisTeNinG tO tHe CoMmUNity" when there are **FOUR** issues or pull requests relating to using tabs, and all of them have been rejected. You **CAN'T** ignore that there are _some_ people who like to use tabs! So just suck up and give us tab support!

#2122 
#513
#640
#47

**Comment by TheAlphaReturns** [comment]
No, not rejected. Give me _one good reason_ why you won't add tab support. Don't say "no eww tabs are gross and everyone who uses black automatically has to hate tabs" or "no it will go against our DeSiGN LaNGuAgE." It's **_literally_** just a TAB instead of spaces!

**Comment by JelleZijlstra** [comment]
The reason is that our goal is to pick one style and use it. We could choose either tabs or spaces, and we chose spaces (probably because that's the most common style in Python, but the decision predates me).

**Comment by TheAlphaReturns** [comment]
You *DON'T NEED* consistency between the hundreds of thousands of people and projects that use Black.

If your point is "when people see code, and it's well-formatted with spaces, black is for *sure* the formatter. If we give an option for tabs, then no one will know," then you are wrong! In a text editor, no one can tell between tabs and spaces without highlighting over them. There is NO POINT to your argument! There *can* and *should* be multiple styles!

**Comment by sciyoshi** [comment]
I have been maintaining the patch required for adding support for tabs in my fork (based off of the work done by @jleclanche). You can see the extent of the changes needed here: https://github.com/sciyoshi/black/commit/faddb504b395c71a92e6a9ffadaafcc9413ecd88. With the recent refactoring in black, the patch is now just a few lines of code.

@JelleZijlstra I agree in general on the principle of avoiding adding more options. Unfortunately, for us changing would be prohibitively difficult given the need to preserve authorship info in our VCS. I would implore you to empathize in this case with the needs of many of the users of black as seen by the number of tickets that have been opened. The work has been done already and I'd be happy to open a PR or assist in any other way to have this change accepted upstream.

**Comment by jleclanche** [comment]
@JelleZijlstra There are many codebases that require tabs and that is that, black is unusable for those. I've had to fork black into tan for them.

As sciyoshi said, the current patch is just a few lines, it's not a significant maintenance burden, the work is done, and this is a highly requested feature which makes black inaccessible for a portion of the Python community which uses tabs.

It's very depressing to see it rejected again and again.

**Comment by JelleZijlstra** [comment]
Could you clarify why tab support is different from all the other reformatting that Black does? Introducing Black in a new codebase is inevitably going to lead to a lot of reformatting, and we have documentation on how to preserve `git blame` data (https://black.readthedocs.io/en/stable/guides/introducing_black_to_your_project.html#avoiding-ruining-git-blame).

**Comment by jleclanche** [comment]
I’ve written about this quite a bit in the original PR for it. Tabs are used as an accessibility feature in some codebases / by some developers (myself included), as variable indent width puts readability controls in the users hands, just like font size.

to put it another way, imagine if using Black were forcing an 11pt font size in your editor just because pep8 said that’s a good font size.

I used to care about this for the sake of others. But I’ve been coding for twenty years now and it’s my eyesight’s turn to start failing. I wonder how bad it will be by the time this gets merged :)

**Comment by sciyoshi** [comment]
@JelleZijlstra certainly - that's a great question. In addition to the accessibility issue that @jleclanche raises, I would argue the following:

* Tabs are compliant with PEP-8. From [the source](https://www.python.org/dev/peps/pep-0008/#tabs-or-spaces):

    > Spaces are the preferred indentation method.
    > Tabs should be used solely to remain consistent with code that is already indented with tabs.

  By my reading, that means PEP-8 allows tabs if working on a codebase that already has them. Thus a fully PEP-8 compliant project that wants to adopt black could have the only reformatting be the indentation. And from your link, while I'm aware that it is possible to ignore those changes in git, tools like GitHub and GitLab don't yet support this.

* Empirically, the tab issue is different than the other reformatting black does because having an option has been asked for numerous times, and at least two people are willing to invest the time to maintain a fork solely for that purpose. As another example, the recent addition of the `--skip-magic-trailing-comma` option seems similar in that the behavior is important enough to people to warrant its inclusion.

In keeping with the analogical Henry Ford quote that is the namesake for this project (and ignoring for a moment the [veracity and applicability of the quote](https://www.quora.com/Why-did-Henry-Ford-say-%E2%80%9CA-customer-can-have-a-car-painted-any-color-he-wants-as-long-as-it%E2%80%99s-black%E2%80%9D)) - I'm not asking for a purple car, I'm asking to have the steering wheel on the right side so that people in the UK and Japan can legally drive them, whereas I feel you're arguing that the whole country should just switch which side they drive on (which maybe they should, like Sweden did 😄)
