### ISSUE TITLE
Long calculation statement with function

### ISSUE THREAD

**Issue by Vincent0706** [psf/black#2587]
**Describe the style change**

**Examples in the current _Black_ style**

```python
len_x1y1 = math.pow(rec_po[0].x - rec_po[1].x, 2) + math.pow(
        rec_po[0].y - rec_po[1].y, 2
    )
```

**Desired style**

```python
len_x1y1 = math.pow(rec_po[0].x - rec_po[1].x, 2) + math.pow(rec_po[0].y - rec_po[1].y, 2)
# or
len_x1y1 = ( math.pow(rec_po[0].x - rec_po[1].x, 2) 
             +math.pow(rec_po[0].y - rec_po[1].y, 2))
```

**Additional context**

**Comment by felix-hilden** [comment]
Hi, due to our [line wrapping rules](https://black.readthedocs.io/en/stable/the_black_code_style/current_style.html#how-black-wraps-lines), we'll not be supporting this style. I do agree that exploding the parens here is the wrong option, and that is being discussed in #2156 and the various linked issues. I'll close this and let's continue discussion there.
