### ISSUE TITLE
Black --exclude option does not work together with wildcard path

### ISSUE THREAD

**Issue by trickleup** [psf/black#2600]
**Describe the bug**

Thanks for a great library. When running the following command, black excludes the folders in the regex as expected:

```
black . --check --exclude 'build'
```

However, when running this, the exclude pattern is ignored:

```
black **/*.py --check --exclude 'build'
```

**To Reproduce**

In an empty folder:

```python
echo 'print(  1)' >> test.py
mkdir build
echo 'print(  1)' >> build/foo.py
```

Then running black, gives this output:

```
# black-test black . --check --exclude 'build'
would reformat test.py
Oh no! 💥 💔 💥
1 file would be reformatted.
# black-test black **/*.py --check --exclude 'build'
would reformat build/foo.py
would reformat test.py
Oh no! 💥 💔 💥
2 files would be reformatted.
```

I was expecting the `build/foo.py` to be excluded in both scenarios.

**Environment**

- Black's version: 21.10b0
- OS and Python version: python 3.10.0, MacOS 11.6

**Comment by ichard26** [comment]
Thanks for the compliment![^1]

The issue you're facing here is that **/*.py is expanded by your shell into a list of files _before_ Black is run[^3]. Exclude and include regexes are ignored for files that were directly given at the command line. Black can't tell whether paths passed on the command line were explicitly given by the user or were the result of a glob expansion, so it goes with the option of ignoring --exclude for directly given files as chances are the user really does want Black to reformat them[^2]. Although it should be noted any recursive search is still subjected to --exclude, ex. passing a directory directly would cause the discovered files be checked against the regexes (hence explaining why your first command behaves as expected).

FWIW this has been a big enough problem that we've added the `--force-exclude` option as an alternative to --exclude which **always** applies. The only way to override it is to redefine the option. The context behind it is that the very popular pre-commit framework and devtool passes files directly at the command instead of letting the tools do their own discovery (which makes sense as not every tool would such capabilities).

Hopefully that clears things up!

[^1]: although I find it interesting how much Black is referred to as a library when we don't offer any officially supported APIs. Yes there's kinda an unofficial one but that's more due to backwards compatibility reasons really :)
[^2]: could call it erring on the side of safety
[^3]: try running `python -c "import sys; print(*sys.argv)" *.py` in any directory with some Python files, you should see that Python receives the files directly
