### ISSUE TITLE
breaking change in 22.1.0 `TypeError: set object expected; got list`

### ISSUE THREAD

**Issue by asottile** [psf/black#2829]
this worked fine in previous versions but was broken with the most recently release

here's the calling code: https://github.com/asottile/blacken-docs/blob/fb39015204c88c8f4f7365d7b4ac049ea8cb6450/blacken_docs.py#L237-L241

**Describe the bug**

`FileMode` changed in a backward incompatible way in 22.1.0

**To Reproduce**

here is the minimal reproduction

```bash
python3 -c 'import black; black.FileMode([])'
```
```console
$ python3 -c 'import black; black.FileMode([])'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "<string>", line 3, in __init__
TypeError: set object expected; got list
```

**Expected behavior**

this used to work

**Environment**

- Black's version: 22.1.0
- OS and Python version: 3.8.10 on ubuntu 20.04

**Additional context**

this is breaking blacken-docs: https://github.com/asottile/blacken-docs/issues/141

**Comment by JelleZijlstra** [comment]
This is a consequence of mypyc, which adds strict runtime type checks as the price for improved performance. The first argument to Mode is a set: https://github.com/psf/black/blob/main/src/black/mode.py#L139.

I am not inclined to change this back. We don't have a publicly documented API, and to the extent we do, the type annotations already say you need to pass a set, not a list.

**Comment by asottile** [comment]
there seems to at least be an intent that this is public -- given the comment here: https://github.com/psf/black/blob/d038a24ca200da9dacc1dcb05090c9e5b45b7869/src/black/__init__.py#L102-L103

and when the code was written `FileMode` utilized `attrs.Factory` to convert to a set -- 36d3c516d3c09fc5f05c420900dd6b854e3c8bbd

**Comment by asottile** [comment]
it looks like it was unintentionally changed to disallow iterables here: f2ea461e9e9fa5c47bb61fd72d512c748928badc  (a confusion between `default_factory` and `Factory`)

**Comment by JelleZijlstra** [comment]
The history here isn't really relevant. Even if we made some half-hearted backward compatibility hacks in the past, this was never a documented public API, and we can and do change it in incompatible ways without warning. That will continue to be the case until #779 is resolved. One API-like structure we have are the type annotations, and those already said `Set` in the previous release.

We could probably fix your use case by using an annotation like `Collection` instead of `Set`, but at the moment this doesn't feel like it's worth a hotfix release. It's obviously also very easy to fix on your side.

**Comment by asottile** [comment]
I think I would prefer black fix the regression rather than having to adjust my code

**Comment by felix-hilden** [comment]
I'll have to agree with Jelle here. Additionally:

- `Set` is a *better* type hint, we wouldn't want lists of duplicate target versions
- We were in beta for the longest time so things are bound to change. Pinning a beta package is advisable, especially if one is using undocumented APIs, stable as they may seem
- We still supply a source distribution for which this works just fine: `pip install black --no-binary :all:`

I feel for you because of the breakage, but I'll echo Jelle: I'm not inclined to change anything here. But we'll continue discussing the public API! Personally, I'm interested in taking care of it pretty soon so people can start using Black within Python as well 👍

**Comment by asottile** [comment]
I'm a bit disappointed in the choice, this feels very much like a "we're a bigger project so do what we say" decision rather than one which is helpful for the community and integrations
