### ISSUE TITLE
fmt on/off raises internal error when fmt: off in multi-level intended code block

### ISSUE THREAD

**Issue by izikeros** [psf/black#2842]
**Description**

Black raises error when formatting code that includes specific combination of `fmt: off` and `fmt: on` commands. The bug occurs when `fmt: off` is before intended block and `fmt: on` inside intended block. Bug occurs only in multi-level indentation (see: examples below)

**To Reproduce**
Try to format file with the code:
```python
for i in range(2):
    # fmt: off
    for j in range(2):
        # fmt: on
        pass
```
Note: similar code but with single-level of indent not raises any error:
```python
# fmt: off
for j in range(2):
    # fmt: on
    pass
```
And run it with these arguments:

```sh
$ black file.py
```

The resulting error is:

> error: cannot format file.py: INTERNAL ERROR: Black produced code that is not equivalent to the source on pass 1.  Please report a bug on https://github.com/psf/black/issues.  This diff might be helpful: /var/folders/97/sr1jt8qx6b90q4hqfsv06qbc0000gq/T/blk_0vp6bvi8.log

**Expected behavior**

Black should format file without raising error.

**Environment**

- Black's version: 22.1.0
- OS and Python version: macOS 12.2 (21D49), Python 3.9.10

**Comment by felix-hilden** [comment]
Hi! As [documented](https://black.readthedocs.io/en/stable/the_black_code_style/current_style.html#code-style), `# fmt: off / on` have to be on the same level of indentation. We have discussed fixing this in #2140 (#569 also related), so I'll close this as a duplicate.

**Comment by Shivansh-007** [comment]
The error is not because of the indentation difference between fmt on/off, it's something else. Your code example is formatted successfully (no internal error raised) in [black playground](https://black.vercel.app/?version=main&state=_Td6WFoAAATm1rRGAgAhARYAAAB0L-Wj4ACoAGFdAD2IimZxl1N_WlkNxQPWyzxoH1G8HXXX_1CdlvelvarQW5k507KZuTsn396qcrvd-D8ry2tlZu8D7Nfa06TFACSLpRv0a1DWVsJlLlNTdk23bIHoKDJHyEzXGH18hVm5HAAAAAAApGyJ3B9H-9gAAX2pAQAAAEBQYrGxxGf7AgAAAAAEWVo=).

![Screenshot from 2022-01-31 13-47-40](https://user-images.githubusercontent.com/69356296/151759940-dd122088-9076-4667-afad-76c60947e0ed.png)

**Comment by felix-hilden** [comment]
Verified that this doesn't happen on the compiled version either. @izikeros If this is indeed the case, please submit another issue detailing the problem!
