### ISSUE TITLE
Add option to automatically check if running the latest black version 

### ISSUE THREAD

**Issue by ucfbrd** [psf/black#2849]
**Context**

Most of the time when running a local version of `black` , we are running an old version of black, However when running `CI`, one rebuild black with latest version, this creates discrepency.

**Proposal**

One would add either a configuration in `pyproject.toml` or directly in the command line to first trigger a `pip install -U black`, or at least warn user the version used might not be latest

**Comment by felix-hilden** [comment]
Hi! We do have an option for requiring a known version to be running. Additionally, now that we're stable, these discrepancies should not happen. So is that option enough, or are you especially asking for the version to be latest?

How would the latest version be determined? I'm not so sure if we want to go into web crawling or something. Pip has `pip list --outdated`, which could be used instead of a CLI option in Black. Second opinions?

**Comment by JelleZijlstra** [comment]
We shouldn't be making network requests to determine whether there's a new version. The existing `--required-version` option covers the OP's use case.

**Comment by ucfbrd** [comment]
Hey, thank you for the quick reply

Yes workaround was to set a specific version in the requirement of the project

I was thinking about something along the line of what pip does indeed, when running pip, we get a warning such as 
```
WARNING: You are using pip version 20.2.4; however, version 21.3.1 is available.
You should consider upgrading via the `--upgrade pip' command.
```
but can see this to require network requests which might not be necessarily desired in all cases

**Comment by felix-hilden** [comment]
So maybe you'd want to specify the required version, but install packages in CI without pinning so that you can see Black fail and upgrade your configuration when a new version is released. If you really want to both require a version and have it always be the latest one, that is. A bit more work for sure, but if you really want the latest goodness with `--preview` you should be reviewing the changes anyway. Without that, changing configuration once a year doesn't seem like a big issue.

I was overly careful with my wording above, I meant to say that I wouldn't really want us having any web dependencies.

**Comment by ucfbrd** [comment]
yes that is clear, agree with the `Stability Policy` that would be happening once a year ( let's all hope :) ), I am fine going with that solution for now ;)
