### ISSUE TITLE
Does flake8 still ignore W503 by default?

### ISSUE THREAD

**Issue by ichard26** [psf/black#2925]
Suspect regression. Using v 4.0.1 (Gentoo X86_64). Having just installed black (v22.1.0), reformatting produced multiple W503 messages. Attempted to utilize extended-ignore and reloaded/rescanned project. Warnings persisted. I ensured no W503/W504 ignores were present in code or configuration. Only after adding explicitly W503 to extended-ignore would flake8 be satisfied.

_Originally posted by @scottfurry in https://github.com/psf/black/issues/1661#issuecomment-1048462407_

**Comment by ichard26** [comment]
I can't reproduce this behaviour but I'm no flake8 pro. If it turns out flake8 requires ignoring `W503 line break before binary operator` then let's add it back to the [compatible configuration docs](https://black.readthedocs.io/en/latest/guides/using_black_with_other_tools.html) (don't forget to explain why it should be ignored like the others!)

**Comment by JelleZijlstra** [comment]
I feel like it's better to err on the side of listing more codes in our docs, just in case people explicitly turn on the code or flake8 changes its mind about defaults.

**Comment by jpy-git** [comment]
it's still in the default ignores for the latest flake8 (`flake8 --help`)
<img width="753" alt="image" src="https://user-images.githubusercontent.com/80432516/158575604-415ac5a1-795f-4c82-a525-cb9336caffd0.png">

my guess is they might have used `--ignore` in one of their configs to try and ignore another error rather than `--extend-ignore` and overwritten the default list, hence why they then need to re-add it in.
<img width="625" alt="image" src="https://user-images.githubusercontent.com/80432516/158576525-86d66088-014c-4d34-bb13-b2ffc523f285.png">

The black docs already have a [warning](https://black.readthedocs.io/en/stable/guides/using_black_with_other_tools.html#:~:text=When%20breaking%20a,in%20your%20configuration.) against enabling `W503` and the above flake8 behaviour is in their documentation

**Comment by mmdbalkhi** [comment]
I've also a problem with this, Unfortunately problem from flake8 when fixing W503 we see W504!

**Comment by HamishPoole** [comment]
Hey all, is this issue still available to take up?

**Comment by ArjunYaduvanshi02** [comment]
can i claim this issue?

**Comment by hauntsaninja** [comment]
jpy-git's comment is correct. I'm not sure I see anything additional for us to do.
