### ISSUE TITLE
Remove underscores in numeric literals

### ISSUE THREAD

**Issue by jpy-git** [psf/black#2957]
**Is your feature request related to a problem? Please describe.**

I've just learned that this
```python
a = 1_2_3_4_5.6_7_8_9
```
is a valid alternative way of writing
```python
a = 12345.6789
```

I think the intention is to let people break up large numbers if they want i.e. `1_000_000` instead of `1000000`

**Describe the solution you'd like**

Should we decide on a consistent format for `black` and remove these underscores?

**Describe alternatives you've considered**

I've double checked and the AST is the same regardless of the presence of the underscores so we should be able to fix them without changing the AST
```python
import ast
import astpretty

tree = ast.parse("a = 1_2_3_4_5.6_7_8_9")
astpretty.pprint(tree)
```
```
Module(
    body=[
        Assign(
            lineno=1,
            col_offset=0,
            end_lineno=1,
            end_col_offset=21,
            targets=[Name(lineno=1, col_offset=0, end_lineno=1, end_col_offset=1, id='a', ctx=Store())],
            value=Constant(lineno=1, col_offset=4, end_lineno=1, end_col_offset=21, value=12345.6789, kind=None),
            type_comment=None,
        ),
    ],
    type_ignores=[],
)
```

**Comment by JelleZijlstra** [comment]
We previously did this (inserting underscores every third digit only), but undid it because it was causing issues when we inserted underscores into numeric ids, making them harder to grep.

I suppose we could remove extra underscores in cases like your first example, but I'm not sure that's really worth the complexity.

**Comment by jpy-git** [comment]
I agree it would be a hassle to try and handle the every third digit logic.

My suggestion was actually just remove all underscores since that's consistent/simple.

Although, if it turns out using these underscores is a common occurrence then I'd be happy to leave this as out of scope for black 👍

**Comment by JelleZijlstra** [comment]
Well, I'd feel bad about making Black totally remove all usage of a language feature :) 

The place where the underscores shine is if you have `ONE_MILLION = 1_000_000`, because `1000000` makes it really hard to verify the number of zeros is right. I wouldn't want Black to remove underscores in that case.

For reference: #696, #549, #467, #454, #452.

**Comment by jpy-git** [comment]
haha that's a fair point, in that case I understand why we leave it the users to handle these! Thanks 😄

**Comment by rsb-23** [comment]
> We previously did this (inserting underscores every third digit only), but undid it because it was causing issues when we inserted underscores into numeric ids, making them harder to grep.
> 

Does this happen even if, I already have 1_000 in my code? 
If No, 
Is it feasible to enable this feature to run at start or end? 

I am open to other workaround too.

**Comment by rsb-23** [comment]
> Is it feasible to enable this feature to run at start or end?
> 
NO
I have read similar issues and understood why its not feasible.
