### ISSUE TITLE
Use PEP 621's [project.requires-python] field to automatically set --target-version

### ISSUE THREAD

**Issue by GamePad64** [psf/black#3124]
PEP 621 provides `project.requires-python` field in pyproject.toml. I expect, that most of the tools will support this field eventually.
Each code-related linter and formatter has a setting for supported python version.

Using this field would be good for tool interoperability in the future.

Related: https://github.com/psf/black/issues/751#issuecomment-778441893

**Comment by ichard26** [comment]
I'm in favour.

**Comment by cooperlees** [comment]
When it makes sense, I'm in favor of moving everything we can to pyproject.toml long as it does not break mypyc etc. etc.

**Comment by stinodego** [comment]
I looked into this. It should be easy enough to augment the [`parse_pyproject_toml` function](https://github.com/psf/black/blob/eaa048925e4443cc0e2b57b795f2852bedb4287f/src/black/files.py#L105) to also read the `project.requires-python` field.

However, parsing that field is another matter. We would probably have to rely on a third party library if we really want to do this properly. And I'm not sure it's worth introducing a dependency in order to be able to automatically infer the target version.

Input is appreciated!

**Comment by kdeldycke** [comment]
FWIW, I [hacked something similiar in my GitHub workflow](https://github.com/kdeldycke/workflows/blob/97dd3ac5fd18e6e1964dd32034dce83ffd2e183a/.github/workflows/autofix.yaml#L61-L89) to feed [`pyupgrade`](https://github.com/asottile/pyupgrade) with the appropriate `--py3-plus` /  `--py36-plus` / `(...)` / `--py311-plus` option flags.

**Comment by SamirPS** [comment]
@kdeldycke If a new version of python is out you will need to modify the file no ? Can we erase the check <= 11

**Comment by stinodego** [comment]
I indeed looked at poetry-core for the version parsing. But if you wanted to use their version parser (it's quite extensive), you'd have to add it as a dependency, which feels quite bad.

**Comment by ssbarnea** [comment]
I hope to see this feature being added and maybe in a way that it would make it easy to reuse in other tools as updating min-python in so many tools is a PITA and almost a guarantee that you will forget to update one of them.

**Comment by ichard26** [comment]
We could also probably use [`packaging.specifiers.SpecifierSet`](https://packaging.pypa.io/en/latest/specifiers.html#packaging.specifiers.SpecifierSet) to parse `[project].python-requires`. Not sure whether to hard depend on `packaging` or add it as an extra since it's not core Black functionality.

**Comment by stinodego** [comment]
> We could also probably use [`packaging.specifiers.SpecifierSet`](https://packaging.pypa.io/en/latest/specifiers.html#packaging.specifiers.SpecifierSet) to parse `[project].python-requires`. Not sure whether to hard depend on `packaging` or add it as an extra since it's not core Black functionality.

`packaging` was a great suggestion - it does exactly what we need. I have a working implementation now; will open a PR when I have added tests.

I'll first add it as a hard dependency - we can adjust in code review if required.

**Comment by ichard26** [comment]
That's great, thank you for looking into this! I look forward to the PR :)

**Comment by hugovk** [comment]
The Requires-Python metadata can be in `pyproject.toml`, `setup.cfg` or `setup.py`.

Would Black only support reading from `pyproject.toml`?

I usually put it in `setup.cfg`, but am fine if Black only wants to read `pyproject.toml`, because it's already doing so for other config. (And it may also drive further `pyproject.toml` adoption.)

**Comment by JelleZijlstra** [comment]
I wouldn't want Black to read other config files than `pyproject.toml`; that's asking for a lot of additional complexity.

**Comment by kdeldycke** [comment]
> @kdeldycke If a new version of python is out you will need to modify the file no ? Can we erase the check <= 11

Hey @SamirPS, just noticed your comment. Since then I indeed removed the hard-coded check on `Python <= 3.11`. My [code to produce Black's `--target-version` parameters](https://github.com/kdeldycke/workflows/blob/main/.github/metadata.py#L338-L384) is now future-proof.

Since [#3219](https://github.com/psf/black/pull/3219) has been released upstream in `v23.1.0`, we still need my custom code for Poetry-based projects. Black [only looks](https://github.com/psf/black/blob/b0d1fba/src/black/files.py#L141-L142) for the [PEP-621's `requires-python` marker](https://peps.python.org/pep-0621/#requires-python) in the `pyproject.toml` file. Not Poetry's `[tool.poetry.dependencies]` > `python = "^3.7"` specifiers.

**Comment by kdeldycke** [comment]
> I hope to see this feature being added and maybe in a way that it would make it easy to reuse in other tools as updating min-python in so many tools is a PITA and almost a guarantee that you will forget to update one of them.

Agreed @ssbarnea. I had to write some [code to produce consistent Python target parameters for Black, Mypy and Pyupgrade](https://github.com/kdeldycke/workflows/blob/92b9bd1e6257e146c0c5f859a3b20c3d7ccd3251/.github/metadata.py#L29-L31).

For more details, see [my `metadata.py` script](https://github.com/kdeldycke/workflows/blob/main/.github/metadata.py#L29-L31)  in [my reuseable workflows](https://github.com/kdeldycke/workflows) that I try to use everywhere in my Python projects.
