### ISSUE TITLE
https://black.readthedocs.io/en/stable/ should be referencing 22.6.0 but references 22.3.0

### ISSUE THREAD

**Issue by kenhowardpdx** [psf/black#3147]
**Is this related to a problem? Please describe.**

Wrong version on https://black.readthedocs.io/en/stable/

**Describe the solution you'd like**

Publish docs for 22.6.0

**Comment by ichard26** [comment]
It is now policy to update the stable branch after the release automation upload the sdist and wheels to PyPI. This is automated so this shouldn't be an issue anymore. It might be a good decision to not wait for the mypyc wheels to build and upload though since that can take a while (up to 30 minutes).

I'll break out the last documentation suggestion into its own issue later.

**Comment by JelleZijlstra** [comment]
> It might be a good decision to not wait for the mypyc wheels to build and upload though since that can take a while (up to 30 minutes).

Waiting seems reasonable since arguably it's not "stable" until we have the mypyc wheels that most users will use. But I don't think it really matters, let's just stick with what's easiest.

**Comment by ichard26** [comment]
I agree, unless people get confused by the delay, it's probably best to leave it be for now :+1:
