### ISSUE TITLE
comments removed by black in case the following line has a fmt skip

### ISSUE THREAD

**Issue by LuisBL** [psf/black#3225]
**Describe the bug**

comments removed by black in case the following line has a fmt skip

**To Reproduce**

```python
# black_rm_com.py
def myfun():
    "docstring"
    # some text here this comment will be removed by black !$
    # removed by black in case the following line has a fmt skip

    auto = ['AEDAT', 'AWKEY', 'AWTYP', 'BKTXT', 'BSTAT', 'GRPID', 'HWAER', 'LDGRP',
            'TCODE', 'UPDDT', 'WAERS', 'WWERT', 'XBLNR', 'KURSF']  # fmt: skip
    return auto
```
if we run it

```sh
$ black --diff black_rm_com.py 
--- black_rm_com.py	2022-08-15 15:31:28.925867 +0000
+++ black_rm_com.py	2022-08-15 15:33:30.751457 +0000
@@ -1,8 +1,5 @@
 def myfun():
     "docstring"
-    # some text here this comment will be removed by black !$
-    # removed by black in case the following line has a fmt skip
-
     auto = ['AEDAT', 'AWKEY', 'AWTYP', 'BKTXT', 'BSTAT', 'GRPID', 'HWAER', 'LDGRP',
             'TCODE', 'UPDDT', 'WAERS', 'WWERT', 'XBLNR', 'KURSF']  # fmt: skip
     return auto
would reformat black_rm_com.py

All done! ✨ 🍰 ✨
1 file would be reformatted.
```

The resulting error is:

black should not remove this comments

**Expected behavior**

keep the comments

**Environment**

- Black's version: with black 22.6.0:

```
$ pip show black
Name: black
Version: 22.6.0
```
- OS and Python version: 

```
$ python --version
Python 3.8.10
$ cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Ubuntu 20.04.4 LTS"
$ 
```

**Comment by felix-hilden** [comment]
This has been fixed in main ([playground](https://black.vercel.app/?version=main&state=_Td6WFoAAATm1rRGAgAhARYAAAB0L-Wj4AG_ARldAD2IimZxl1N_WlbvK5V-ga_a-s_1uAoO8hDc-6_7fjVlho4ZlUJn6TkaBXjUy22A8cUg3QxFTdD83pTG-aj5KkIAjcP-C3zC1-0K7EMuGCSRvuQ2Uhwh37EPDPNSNMbQ0209zOoLxAOzH9KofnLcPGNRgzwJAkplxxWgxZoqFUfl75fbO0v7Z2lcURO6twLEOpSpywlKe4r2DmkwFcWytV3yAaSNBUQ8tN0HrmA0TEu2-R65pI7AavCXnMW-Q6O8aYl4mca0hc02MOBE4vXn_WIa4n1IBSMQm8sYryiJlRlXqTLh9JDLg_FFPJkU1zdClmaP7jfXIQRqAVWo7AwYR-mJrzbe1ThwR0-_bWSU3TxqXu-c37Biy-ghAAAAAKGWg6q4ljMqAAG1AsADAAAkVZmHscRn-wIAAAAABFla)) via #2339
