### ISSUE TITLE
Complete 3.11 Support

### ISSUE THREAD

**Issue by cooperlees** [psf/black#3230]
Some dependencies are blocking us testing black to make sure we're 100% 3.11 ready. Let work with/around them for now to at least get partial testing into CI.

This issue to to track all the needed fixes to get us there. Will get more detail here are we learn.

## Known Issues

- aiohttp for blackd
  - Will look at skipping blackd tests for now for 3.11
- mypyc compiling

Step 1: Get partial 3.11 CI running
Step 2: work with dependency projects
Step X: Add back parts to get to full test suite

**Comment by ichard26** [comment]
Regarding aiohttp there's two main problems that make testing 3.11 a bit of a pain:

- aiohttp's `AioHTTPTestCase` class seems to be completely broken on 3.11 ([here's an example pytest run showing it blow up](https://paste.pythondiscord.com/bilicumawi.py))
  - https://github.com/aio-libs/aiohttp/issues/6757
- aiohttp is still uninstallable on 3.11 as their Cython sources have not been regenerated with a new enough Cython that supports 3.11 
  - We'll have to set the `AIOHTTP_NO_EXTENSIONS environment variable to `1` to skip Cython entirely so aiohttp can be installed (from a sdist, ugh)
  
---

Regarding mypyc, mypyc already supports 3.11 AFAIK. The problem is on our end. Linux is unsupported since I'm still using this really old manylinux image to work around the weird linker error. https://github.com/psf/black/blob/4ebf14d17ed544be893be5706c02116fd8b83b4c/pyproject.toml#L64-L65

macOS/Windows are raising new type errors (about tomllib out of all things)

```
  + python -m pip wheel 'D:\a\black-mypyc-wheels\black-mypyc-wheels' '--wheel-dir=C:\Users\runneradmin\AppData\Local\Temp\cibw-run-swrchwj1\cp311-win_amd64\built_wheel' --no-deps -v
  Processing d:\a\black-mypyc-wheels\black-mypyc-wheels
    Preparing metadata (pyproject.toml): started
    Running command Preparing metadata (pyproject.toml)
    Parsed and typechecked in 14.773s
    Compiled to C in 0.000s
    src\black\files.py:29:9: error: Name "tomllib" already defined (by an import)
```
https://github.com/ichard26/black-mypyc-wheels/runs/7842350331?check_suite_focus=true#step:5:3585

macOS/Windows should be an easy fix assuming the one type error is all.

**Comment by kjyv** [comment]
I looks like aihttp 3.8.3 installs fine with Python 3.11 (just tested it). See also https://github.com/aio-libs/aiohttp/issues/6600

**Comment by cooperlees** [comment]
O cool - Thanks for the update - I'll see what hacks I can undo!
