### ISSUE TITLE
Convert lists to tuples when safe

### ISSUE THREAD

**Issue by TomFryers** [psf/black#3241]
**Describe the style change**

There are some situations in which lists and tuples have equivalent semantics, which presents an opportunity for standardisation. Tuples should be marginally faster.

**Examples in the current _Black_ style**

```python
for p in [2, 3, 5]:
    ...
[f(x) for x in [1, 4, 3]]
if size in ["med", "big"]:
    ...
for p in (2, 3, 5):
    ...
[f(x) for x in (1, 4, 3)]
if size in ("med", "big"):
    ...
```

**Desired style**

```python
for p in (2, 3, 5):
    ...
[f(x) for x in (1, 4, 3)]
if size in ("med", "big"):
    ...
for p in (2, 3, 5):
    ...
[f(x) for x in (1, 4, 3)]
if size in ("med", "big"):
    ...
```

There may be more cases I have missed. (Star unpacking? But why would one do that with a list/tuple literal?)

**Additional context**

This changes the AST. It also may make programs marginally faster. I don't think it can change behaviour in any other way, unless doing some AST tricks. Perhaps this would be something to put in a dark shade of Black, if that proposal is accepted.

In the `in` example, often a set would be preferable, but that's not a safe transformation.

**Comment by hauntsaninja** [comment]
Not a maintainer, but this feels like the kind of thing that would be surprising for black to do. Note that CPython will literally make this kind of transformation for you (run `dis.dis` to see the bytecode), so there will not be any performance benefit.

**Comment by cooperlees** [comment]
I am also not a fan of Black, a formatter, changing a mutable sequence into an immutable sequence.

I feel this is more something like [flake8-comprehensions](https://pypi.org/project/flake8-comprehensions/) should warn on / suggest maybe ... I don't know of an auto-corrector tool that will change the AST.

Black tries very hard not to alter the AST. I'll leave this up for more debate, but I don't think we'll accept this proposal.

**Comment by jsal13** [comment]
Agreed with the previous two comments --- this is a fundamental change from mutable to immutable objs which can potentially create confusion for the coder in larger code-bases where this change is not obvious.

It would be tricky to check something like this:

```python
from typing import List

def print_out_list_items(items: List[str]) -> None:
    for item in items:
        print(item)

my_cool_list = ["apple", "banana", "grape"]
print_out_list_items(my_cool_list)
```

Since if this were to change `my_cool_list` to a tuple, mypy would report the warning `Argument 1 to "print_out_list_items" has incompatible type "Tuple[str, str, str]"; expected "List[str]"mypy(error)`.  The user now has a mypy error when all they did was format.  Black _could_ try to go around and try to see where every list is being used and if that is typed, but it seems excessive at that point.

It might be worth it in some very, very specific cases, but I cannot think of any where the speed you gain is worth the confusion of auto-changing types of a variable.

**Comment by TomFryers** [comment]
@hauntsaninja You are correct. The iteration versions have had the same bytecode since 3.6, and the containment check optimisation is older still. So for all supported versions of Python, the performance will remain unaffected.

@cooperlees It would only be making mutable sequences immutable in situations where there's not way to mutate them anyway, so that shouldn't matter. I understand if it's considered out of scope, however.

@jsal13 I'm not suggesting Black changes `my_cool_list` to a tuple or that Black does any complex static analysis to determine which variables can semi-safely be transformed. My suggestion was limited to situations in which there is a clear, local guarantee that the behaviour will be the same, barring extreme introspection or peculiar performance-based behaviour.
