### ISSUE TITLE
Inconsistent parsing error when using dictionary and f-string

### ISSUE THREAD

**Issue by lb-desupervised** [psf/black#3269]
It seems that a combination of incorrect formatting and the presence of an incomplete f-string produces a parsing error. The interesting issue is that the error is not raised when the formatting is correct.

I think this is best explained by an example.

This raises a parsing error ("cannot use --safe with this file; failed to parse source file."):

```py
non_capitalised = {
    c: lowercase_map[c]
    for c in columns if (c.lower() in lowercase_map and c not in expected_cases)
}
if non_capitalised:
    return f"Unexpected columns '{}' (did you mean '{}'?)"
```

This does not (file would be left unchanged):

```py
non_capitalised = {
    c: lowercase_map[c]
    for c in columns
    if (c.lower() in lowercase_map and c not in expected_cases)
}
if non_capitalised:
    return f"Unexpected columns '{}' (did you mean '{}'?)"
```

It appears to be related to using an f-string in the statement that follows the dictionary comprehension. This does not raise an error either (note the missing `f` in the return statement):

```py
non_capitalised = {
    c: lowercase_map[c]
    for c in columns if (c.lower() in lowercase_map and c not in expected_cases)
}
if non_capitalised:
    return "Unexpected columns '{}' (did you mean '{}'?)"
```

Observed in versions `21.12b0` and `22.8.0` (more detail error in this version).

**Comment by hauntsaninja** [comment]
I can't repro, I get errors in both your f-string cases.

For what it's worth, see https://black.readthedocs.io/en/stable/faq.html#why-does-black-not-detect-syntax-errors-in-my-code

**Comment by lb-desupervised** [comment]
Ah okay. Then I think we can assume this is a syntax error which is occasionally caught by black. Odd that it behaves differently on different machines though.. :thinking:

**Comment by ichard26** [comment]
I can reproduce FYI.

OK, so what's going on here is that Black doesn't check for AST equivalence when no changes are made. The AST equivalence check is a safety feature that verifies we didn't just change the code's functionality, so if no changes were made, there's not really any point to running it (and we don't run it).

Black's parser, `blib2to3` is pretty lax and often doesn't catch syntax errors as we prioritize being looser to achieve full syntax support over being strict so we match CPython's parser one-to-one. I'm not surprised it doesn't complain about empty expressions in f-strings. Anyway, Python's parser considers f-strings with expressions as invalid:

```python
Python 3.8.5 (default, Sep  9 2020, 23:45:44) 
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> s = f"hello {}"
  File "<stdin>", line 1
SyntaxError: f-string: empty expression not allowed
``` 

The core piece of the puzzle here is that the safety check uses the built-in AST parser[^1] instead of Black's CST parser since CST by their very nature encode too much cosmetic differences. That's why the error message says "cannot use --safe with this file" -- Black reformatted the file just fine, but it can't verify it didn't just make unsafe modifications since the code is failing to parse during the safety check (disabling it via `--fast` would work around this[^2])

I hope that clarifies things.

[^1]: OK, actually if you're on Python 3.7 or below, we use [`typed-ast`](https://pypi.org/project/typed-ast/) instead of the built-in `ast` module, but it's pretty similar and this difference doesn't matter in this specific case

[^2]: I don't encourage using `--fast` in general though

**Comment by lb-desupervised** [comment]
Great explanation @ichard26. Thanks :slightly_smiling_face:
