### ISSUE TITLE
A solution to the obnoxious emojis problem.

### ISSUE THREAD

**Issue by yuvallangerontheroad** [psf/black#3359]
Hello! :heart: :rofl: :rofl: :rofl: :rofl: :rofl: :rofl: :rofl: :rofl: :rofl:

First :one: of all, thank you :bow: for an amazing tool. :lollipop: I use it all the time. :watch:

I wrote a tool :wrench: which cleans :soap: :bath: :shower: all(:question:) emojis :hankey: from Black's :black_flag: output:

<https://codeberg.org/yuvallangerontheroad/exorcise-fun>

`pip install .` installs an executable script named `black`. Whenever you run it, it will run the next-in-line executable named `black` in your `which -a black`, and filter both stdout and stderr through a regular expression matching emojis.

Patches welcome!

From the `README.md` file:

> Exorcise Fun - Remove cutesy foul symbols from your commandline tools
>
> Is your bitter old blackened lump of coal of an heart cannot stand seeing all these festive symbols? Those cakes? Those party poppers? People smiling and having a good time? Are you suffering from excessive eye rolling? Do your office mates suffer from your constant groaning?
>
> Behold! The tool for you!
>
> It will filter out all so-called emojis and leave your terminal a colourless dark and dead place, just like you like it.

**Comment by JelleZijlstra** [comment]
Have a great day.

It doesn't appear that you're requesting any change to Black.

**Comment by kakafarm** [comment]
> Thanks for the wonderful initiative @kakafarm!

I've been writing GNU Guile recently, not Python, so maybe you could send patches if need be?  I have also been thinking of renaming it to `pitch-black`.  Again, patches welcome!

Oh, and I thought it is just the blood pressure raising annoyance of having cutesy forking icons sprinkled on my screen.  Turns out many other people have actual legitimate technical reasons for asking a `--no-emoji` flag, and the PSF/Black team disregards them all, like in #223 #1031 #1255 #1270 #3501 .

The Black team's non-handling of this genuine technical problem is off putting and bewildering, to say the least.

@martingalvan-volue @fredrgrs @cladmi @swills1
