### ISSUE TITLE
Feature request: add option to specify number of spaces around `=` in keyword arguments

### ISSUE THREAD

**Issue by hacker-DOM** [psf/black#3402]
So I love named (keyword) arguments, I use them even when they're not required, I think it improves code readability.

```python
def randint(min, max):
    return random.randint(min, max)

randint(
    min = 0,
    max = 2**256 - 1
)
```

The issue is black removes the whitespace around `=`, which hinders readability.

In the ideal world, `black` would offer several options:
- `remove whitespace for named arguments` (current)
- `num spaces for named arguments` (specify a number)
- align (with a number of spaces), e.g.

```
randint(
    lower_bound = 0,
    max         = 2**256 - 1,
)
```

I guess it could all be summarized as `dont_align(number_of_spaces)` and `align(number_of_spaces_on_right_hand_side)`

If this is off the table - would it be possible to develop a plugin for the above, or is there another tool that accomplishes this ([x-y problem](https://www.wikiwand.com/en/XY_problem))? Thank you!

**Comment by JelleZijlstra** [comment]
Black intentionally has very few configuration switches. It's our job to make all the boring little formatting choices, so that users can focus on what matters: the meaning of the code they are writing. If you want precise control over formatting, Black isn't the tool for you.

In this case, our formatting style (no spaces around `=`) is a core, well-established part of our style. Changing it would be very disruptive.
