### ISSUE TITLE
A single conditional expression inside a list is unnecessarily parenthesized

### ISSUE THREAD

**Issue by yilei** [psf/black#3545]
**Describe the style change**

**Examples in the current _Black_ _future_ style**

```python
items = [
    (
        {"key1": "val1", "key2": "val2", "key3": "val3"}
        if some_var == "longstring"
        else {"key": "val"}
    )
]
```

**Desired style**

```python
items = [
    {'key1': 'val1', 'key2': 'val2', 'key3': 'val3'}
    if some_var == 'longstring'
    else {'key': 'val'}
]
```

**Additional context**

This is a change from https://github.com/psf/black/pull/2278.

I think for this edge case, it shouldn't be parenthesized which also adds an extra indentation level.

Playground link: https://black.vercel.app/?version=stable&state=_Td6WFoAAATm1rRGAgAhARYAAAB0L-Wj4ADgAI9dAD2IimZxl1N_Wlw1a7WWyFbt4o765uThnUap6YXDKg-y2hZjBQk1tHkIJUmRf3ubZW6qh6rwYiTz123BJex-bSSddR0SO6n6vZGd9BpWqXFwR2_6FGijjM_Dne5AzdiE1FlCq8_2Dsx5LlvLchM8KOQsFr8WMFH9R1i7Ks2Es0D6bZmm7Cl6fnGsY_a6uEkAAACpTN_YLIf7gwABqwHhAQAAKlDv4rHEZ_sCAAAAAARZWg==

**Comment by ichard26** [comment]
I agree.

**Comment by RedGuy12** [comment]
@yilei I've opened #4312 that fixes this issue. I added it under the `--unstable` style (at least for now) due to #4036.



It's also worth noting that the current `--unstable` style already formats your example as:
```python
items = [(
    {'key1': 'val1', 'key2': 'val2', 'key3': 'val3'}
    if some_var == 'longstring'
    else {'key': 'val'}
)]
```
which is better than the stable style, but could still be improved.


I took a look at the examples @mariuswallraff provided, but I believe that change was the intention of #2278 in the first place, based off the test cases it adds.

**Comment by mariuswallraff** [comment]
Thank you for the fix and for having a look at my post. After reading the other pull request and issue again, I have to agree with you, that change was intentional for the cases I posted. I'll have to get used to the extra indent. 😄
