### ISSUE TITLE
 Black should have an opinion about empty line after functions doc string

### ISSUE THREAD

**Issue by erdnaxeli** [psf/black#355]
Currently Black forces an empty line after a class docstring, but it does not do it for functions.

This code will be left unchanged by Black:
```Python
def lol():
    """
    mdr
    """

    lol


def lol():
    """
    mdr
    """
    lol

```

Black should have an opinion about that. I don't really care about the choice.

**Comment by lithammer** [comment]
My gut feeling is the second approach (i.e. no blank line) is the most common style (even Black itself is using it). All examples in [PEP 257](https://www.python.org/dev/peps/pep-0257/) use it as well, this is also mentioned under ["One-line Docstrings"](https://www.python.org/dev/peps/pep-0257/#one-line-docstrings):

>There's no blank line either before or after the docstring.

**Comment by cas--** [comment]
Just to add, this [SO answer](https://stackoverflow.com/a/34818759/175584) referencing PEP 257 convinced me that there should be no space after docstring, except for class docstrings:
 
> As pointed out by @moliware, the Docstring Conventions state, under One-line Docstrings:
> 
>     There's no blank line either before or after the docstring.
> 
> HOWEVER, it also says (under Multi-line Docstrings):
> 
>     Insert a blank line after all docstrings (one-line or multi-line) that document a class -- generally speaking, the class's methods are separated from each other by a single blank line, and the docstring needs to be offset from the first method by a blank line.
> 
> My interpretation of all this: blank lines should never precede any docstring, and should only follow a docstring when it is for a class.

So black should care about spaces after a docstring...

**Comment by wbolster** [comment]
to add to this, `black` currently adds a blank line below a class docstring, which i don't really care about in general, but for _intentionally empty_ classes such as custom exceptions, it is good practice to add an explicit `pass` statement as the class method. this is not strictly needed from a syntactical point of view since the docstring itself is considered part of the class body by the python grammar, but it is a good idea to add it anyway to explicitly signal that this class is empty (as opposed to forgotten).

the problem is that `black` formats this as follows:

``` python
class MyCustomError(Exception):
    """My custom error."""

    pass
```

while it is arguably better to format it as

``` python
class MyCustomError(Exception):
    """My custom error."""
    pass
```

**Comment by JeremyLoy** [comment]
To track this issue against `master`, [here is a link to the Black playground configured for this issue.](https://black.now.sh/?version=master&state=_Td6WFoAAATm1rRGAgAhARYAAAB0L-Wj4AC2AFxdAD2IimZxl1N_WlbvK5V9KEd0suDTtKdXyRPNp3_8ytr_UTIjSrVkw-yB5mbUVKDxE8rULKG_rSf2jqJaD9L_r2-k8lYS9LOCoOqmbUnoayW90k2kF_N2BNb19JIYAFe693tHP4xBAAF4twEAAAAQ6H8-scRn-wIAAAAABFla)

**Comment by ambv** [comment]
We will be tracking this in #450.
