### ISSUE TITLE
exponentiation/power (`**`) operator should always have spaces on either side like all (?) other operators

### ISSUE THREAD

**Issue by admackin** [psf/black#3707]
**Describe the style change**

put a single space around exponentiation (`**`) operator.

**Examples in the current _Black_ style**

```python
def f(a, b):
    # GOOD
    a + b
    a **= b
    a ** (-b)
    (-a) ** b
    # NOT GOOD
    a**b
    a**-b
```

**Desired style**

```python
def f(a, b):
    # UNCHANGED
    a + b
    a **= b
    a ** (-b)
    (-a) ** b
    # NOW GOOD
    a ** b
    a ** -b
```

**Additional context**

This seems weirdly inconsistent with literally every other arithmetic operator I've tried in not putting spaces around the operators. Note that you *do* get spaces if there are parentheses around either operand, as shown in the example. This is also inconsistent. I've verified this against `main`.

**Comment by ichard26** [comment]
Hey,

So originally Black treated power operators just like any other operator, padding it with a space on each side. However, enough people complained that we decided to change it (PR https://github.com/psf/black/pull/2726). You can read this issue: https://github.com/psf/black/issues/538, but the crux is that since power operators have such high precedence, they should hug their operands to avoid ambiguity. In fact, this is allowed by PEP 8, [under "Other Recommendations"](https://peps.python.org/pep-0008/#other-recommendations) ...

> **If operators with different priorities are used, consider adding whitespace around the operators with the lowest priority(ies).** Use your own judgment; however, never use more than one space, and always have the same amount of whitespace on both sides of a binary operator.

The inconsistency in regards to the operands was simply a decision we made when we first changed. I honestly don't really remember why. Please read the original issue if you're curious. 

Anyway, given this is the first complaint IIRC post-change, it's unlikely we'll rollback on this.

I hope that clears things up!

**Comment by admackin** [comment]
Thanks @ichard26  – I tried so many issue searches and that one still didn't come up. if the ship has sailed, it's sailed. Good to have this one for extra searchability at least. (For my part I'm finding the `a**b` so jarring that I've switched to `math.pow`). 

I am saddened that this [proposal](https://github.com/psf/black/issues/538#issuecomment-593957202) to add spaces when there are only two expressions (so `a ** b` but `a**b * c` didn't seem to make it in to the final PR).

**Comment by chebee7i** [comment]
Is there a way to configure it?  Count me as a second complainer.  I think the non-uniform treatment causes more confusion than the visual benefit.

**Comment by JelleZijlstra** [comment]
@chebee7i for stability, note our stability policy in https://black.readthedocs.io/en/stable/the_black_code_style/index.html#stability-policy (in short, we'll only change the style once a year).

**Comment by chebee7i** [comment]
Btw, is it expected that this should qualify as "simple"?

```
-maxIntFloat = 2 ** sys.float_info.mant_dig         
+maxIntFloat = 2**sys.float_info.mant_dig           
```

The original is certainly easier to read over the new.
