### ISSUE TITLE
Undesired line breaks when using multiple assignments

### ISSUE THREAD

**Issue by yilei** [psf/black#3854]
Black currently formats

```python
zzzzzzzzzzzzzzzzzzzzzzzzzzz = zzzzzzzzzzzzzzzzzzzz = zzzzzzzzzzzzzzz = (
    "zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz"
)
```

to:

```python
zzzzzzzzzzzzzzzzzzzzzzzzzzz = (
    zzzzzzzzzzzzzzzzzzzz
) = zzzzzzzzzzzzzzz = "zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz"
```

**Expected behavior**

Black should favor using parenthesis and break on the right most side:

```python
zzzzzzzzzzzzzzzzzzzzzzzzzzz = zzzzzzzzzzzzzzzzzzzz = zzzzzzzzzzzzzzz = (
    "zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz"
)
```

[Playground link](https://black.vercel.app/?version=stable&state=_Td6WFoAAATm1rRGAgAhARYAAAB0L-Wj4ADyAFVdAD2IimZxl1N_Wm-RlLU-sWOF1KatQTWqkL89ybThPE7758v1LCyyefcFRUYLeFOr8gshchgUztN0geqlUdqRulqSrS1uvxxOJfVXolQbyMQezR-HrAAAAAAADnQwHJyP4E8AAXHzAQAAAFFHA7SxxGf7AgAAAAAEWVo=)

**Comment by MeGaGiGaGon** [comment]
This has been fixed and now formats correctly [playground link](https://black.vercel.app/?version=stable&state=_Td6WFoAAATm1rRGAgAhARYAAAB0L-Wj4AEVAGJdAD2IimZxl1N_Wm-RlLU-sKhXLTCZnXT5VggbKcvAisXs9bLPyNuglB6KeD20FGczYvbExrH4CQPfWeBmOcASCScZ4Q0e0G1VDYs25ZqYzUSXwLI7hw59k8kK9L7fl5J0KGMAAAAAWR8TwiQEDRkAAX6WAgAAAFeiMgaxxGf7AgAAAAAEWVo=). The fix was put into preview by #4010 and later stabilized in version 2024 as part of #3368. #4010 also added some roughly equivalent test cases [here](https://github.com/psf/black/blob/0aabac4fe0895af788ac73c548f0b7c7e7ed56be/tests/data/cases/prefer_rhs_split.py#L87-L106), so this should be good to close.
