### ISSUE TITLE
Add release.py automation for release commits

### ISSUE THREAD

**Issue by cooperlees** [psf/black#3970]
Add a python script to run at release time to generate as much of the commit as we can. This will help the life of black maintainers releasing.

## The script will

- Take two args:
  - old_release
  - new_release
- It will then edit hard coded list of files we know have version strings in them to update the strings - i.e.
  - docs/integrations/source_version_control.md
  - docs/usage_and_configuration/the_basics.md
- It will best effort cleanup CHANGES.md
- It will also have a --generate-changelog-template
  -  This will add the change log template for a commit post release

I will also write manually executable tests as I don't trust myself and need tests to confirm it works.
- I'll somehow get CI to run them

## Update docs
- Document new script existing + how to drive in release docs
- Ensure there is a second post successful release commit adding the CHANGES.md template

**Comment by JelleZijlstra** [comment]
The script might even be able to infer the latest release (so you don't have to pass it in): it can do some git call to find the most recent tag.

**Comment by Benfinch1** [comment]
WHAT TO DO IF YOUR CRYPTOCURRENCY IS LOST OR STOLEN?


If you’ve been duped, there may be little you can do to make things right. You have no other choice except to contact a recovery company. I am aware of numerous trustworthy recovery organizations, but LOST RECOVERY MASTERS are my top option due to how swiftly they assisted me in recovering my lost bitcoins that I had placed with a negligent broker. Contact Lost Recovery Masters. There will surely be steps taken to assist you in locating your misplaced cryptocurrency. They give top agents that are highly qualified and trained to assist you in recovering your stolen or lost cryptocurrencies. Based on my own findings, I wholeheartedly support this healing organization. contact them through

Website https://lostrecoverymasters.com/  
Support team Mail   [Support@lostrecoverymasters.com](mailto:Support@lostrecoverymasters.com)
WhatsApp: +1(204)819-5505.

**Comment by cooperlees** [comment]
I did this and forgot to close. All enhancements welcome.
