### ISSUE TITLE
Make blackd + CI work in 3.12

### ISSUE THREAD

**Issue by cooperlees** [psf/black#3983]
**Describe the bug**

Our CI needs [d] extra install which brings in aiohttp. Due to this we don't work in 3.12

aiohtp are working on their 3.12 release: https://github.com/aio-libs/aiohttp/issues/7675
- They have found bugs due to things being fixed in 3.12 ans a regression in one of their deps

**To Reproduce**

Install black[d] in python 3.12

**Expected behavior**

We install and CI passes

**Environment**

- Black's version: main
- OS and Python version: Any OS + 3.12

This will then unblock us to completely work with 3.12

**Comment by Benfinch1** [comment]
WHAT TO DO IF YOUR CRYPTOCURRENCY IS LOST OR STOLEN?


If you’ve been duped, there may be little you can do to make things right. You have no other choice except to contact a recovery company. I am aware of numerous trustworthy recovery organizations, but LOST RECOVERY MASTERS are my top option due to how swiftly they assisted me in recovering my lost bitcoins that I had placed with a negligent broker. Contact Lost Recovery Masters. There will surely be steps taken to assist you in locating your misplaced cryptocurrency. They give top agents that are highly qualified and trained to assist you in recovering your stolen or lost cryptocurrencies. Based on my own findings, I wholeheartedly support this healing organization. contact them through

Website https://lostrecoverymasters.com/  
Support team Mail   [Support@lostrecoverymasters.com](mailto:Support@lostrecoverymasters.com)
WhatsApp: +1(204)819-5505.

**Comment by cooperlees** [comment]
We have everything but lint ...
