### ISSUE TITLE
crash with the wrong number of spaces before a type-comment for a typed-function

### ISSUE THREAD

**Issue by 15r10nk** [psf/black#3986]
**Black https://github.com/psf/black/commit/f7174b**

[Playground link](https://black.vercel.app/?version=main&state=_Td6WFoAAATm1rRGAgAhARYAAAB0L-Wj4ACdAGxdAD2IimZxl1N_WlPS-KmmddHYvuhXNtRv5dwOg3GUupkfc3rwac9qBQJGzgiXZYTgcZzPRVXH3xgTnwp8UZIGUeHjAjVmolGHHvd1WexIPwRgDQzchjApB4ERadtzHyn7nKccvpqMVcnLzG-rAAACaz19BpoKIwABiAGeAQAAeJeLULHEZ_sCAAAAAARZWg==)

## Options

`--line-length=88`
`--safe`

## Input

```python
def name_4[**name_0](): # type: ignore
    pass

```

## Output

```python
cannot use --safe with this file; failed to parse source file AST: invalid syntax (<unknown>, line 1)
This could be caused by running Black with an older Python version that does not support new syntax used in your source file.
```

## Expected

black should be able to format the code.
The problem is the number of spaces before the `#`. 
There is no problem with two spaces before `#` or if `--fast` is used.

This works:
```python
def name_4[**name_0]():  # type: ignore
    pass
```

**Comment by JelleZijlstra** [comment]
I can't reproduce this locally running Black with Python 3.12. The `--safe` check relies on `ast.parse` and therefore only works with syntax understood by the host Python, even if Black's parser can understand the syntax.

When you run this code on Black running on Python < 3.12, you'll see that it succeeds only if Black won't make any changes to the code:

```
% python -m black --version
python -m black, 23.10.1 (compiled: no)
Python (CPython) 3.11.1
% python -m black -c '''def name_4[**name_0]():               
    pass
'''
def name_4[**name_0]():
    pass
```

But fails if Black does change the code:
```
% python -m black -c '''def name_4[**name_0]( ):
    pass
'''
def name_4[**name_0]( ):
    pass
error: cannot format <string>: cannot use --safe with this file; failed to parse source file AST: expected '(' (<unknown>, line 1)
This could be caused by running Black with an older Python version that does not support new syntax used in your source file.
```

That's because Black skips the safety check if it didn't change anything, on the assumption that its input code is already safe.

**Comment by 15r10nk** [comment]
Yes you are right. I used locally black which was installed with pipx on 3.11.

I believed that it was a bug because I could reproduce it in the online playground.
