### ISSUE TITLE
When and which preview styles will be promoted to stable?

### ISSUE THREAD

**Issue by konstin** [psf/black#3989]
Hi! I'm working on the [ruff formatter](https://github.com/astral-sh/ruff), a fast black compatible formatter.

There are a lot of impactful style improvements that are currently in preview style, which we are working to support, currently also gated behind a `--preview` flag. Do you already have a rough date in mind when you want to promote the preview style to stable, and do you know if you'll promote all rules or keep some of them in preview for another year (e.g. the new string wrapping)? I'm asking because we'd love stay compatible with black stable style and it'd be super helpful to have a rough timeline what we need to support.

**Comment by JelleZijlstra** [comment]
This is documented at https://black.readthedocs.io/en/stable/the_black_code_style/index.html#stability-policy. In short, the intention is that preview style features get promoted to stable once a year in our January release.

I expect to use a similar procedure this year as last:

- In late November/early December, open an issue with a list of all preview features and a tentative decision on whether to include them
- Release a `24.1a1` that implements the proposed new stable style
- Publicize it to get feedback
- In January, release `24.1.0` with the new stable style for 2024

Last year I feel we may not have gotten enough feedback during this period, leading to some controversy over certain decisions, so I hope we'll be able to get more early feedback this year. If Ruff or its users could provide feedback on any preview-style features, I'd be happy.

I don't know yet which preview style features will be made stable. The general hope is that all of them will be moved, but I'm not sure about the string formatting change, which may end up making too many controversial changes in formatting.

**Comment by Benfinch1** [comment]
WHAT TO DO IF YOUR CRYPTOCURRENCY IS LOST OR STOLEN?


If you’ve been duped, there may be little you can do to make things right. You have no other choice except to contact a recovery company. I am aware of numerous trustworthy recovery organizations, but LOST RECOVERY MASTERS are my top option due to how swiftly they assisted me in recovering my lost bitcoins that I had placed with a negligent broker. Contact Lost Recovery Masters. There will surely be steps taken to assist you in locating your misplaced cryptocurrency. They give top agents that are highly qualified and trained to assist you in recovering your stolen or lost cryptocurrencies. Based on my own findings, I wholeheartedly support this healing organization. contact them through

Website https://lostrecoverymasters.com/  
Support team Mail   [Support@lostrecoverymasters.com](mailto:Support@lostrecoverymasters.com)
WhatsApp: +1(204)819-5505.

**Comment by hauntsaninja** [comment]
See now https://github.com/psf/black/issues/4042 :-)

**Comment by konstin** [comment]
Thank you for the comprehensive list! I started tracking ruff's progress on this in https://github.com/astral-sh/ruff/issues/8678
