### ISSUE TITLE
SyntaxWarning on regexp on first run of black

### ISSUE THREAD

**Issue by Julien-Elie** [psf/black#4188]
When running `black` on the following code:

```
text = re.sub(
    "([_a-zA-Z0-9-+]+)(\.[_a-zA-Z0-9-+]+)*"
    "@([a-zA-Z0-9-]+)(\.[a-zA-Z0-9-]+)*(\.[a-zA-Z]{2,4})",
    '<a href="mailto:\g<0>">\g<0></a>',
    text,
)
text = re.sub(
    "(ftp|http|https):\/\/(\w+:{0,1}\w*@)?"
    "(\S+)(:[0-9]+)?(\/|\/([\w#!:.?+=&%@!\-\/]))?",
    '<a href="\g<0>">\g<0></a>',
    text,
)
```

I get the following warnings (written twice):

```
<unknown>:2: SyntaxWarning: invalid escape sequence '\.'
<unknown>:3: SyntaxWarning: invalid escape sequence '\.'
<unknown>:4: SyntaxWarning: invalid escape sequence '\g'
<unknown>:8: SyntaxWarning: invalid escape sequence '\/'
<unknown>:9: SyntaxWarning: invalid escape sequence '\S'
<unknown>:10: SyntaxWarning: invalid escape sequence '\g'
<unknown>:2: SyntaxWarning: invalid escape sequence '\.'
<unknown>:3: SyntaxWarning: invalid escape sequence '\.'
<unknown>:4: SyntaxWarning: invalid escape sequence '\g'
<unknown>:8: SyntaxWarning: invalid escape sequence '\/'
<unknown>:9: SyntaxWarning: invalid escape sequence '\S'
<unknown>:10: SyntaxWarning: invalid escape sequence '\g'
```

When re-running `black` on the same file, the warnings are not shown again.  I have to modify the lines (adding a space for instance) to see the warnings again.

Are these warnings normal?  (The syntax is normally correct according to the documentation of the `re` module.)
If they are normal, should they really appear twice in the output?  And why don't they appear again when running a second time `black`?

**Comment by hauntsaninja** [comment]
Thanks for the issue. First, some background on these warnings... The issue has little to do with `re`, the issue is with the use of any invalid escape sequence in any Python string — it just comes up with `re` because people use a lot of backslashes in regular expressions.

See https://docs.python.org/3/reference/lexical_analysis.html#escape-sequences , in particular:
> Changed in version 3.6: Unrecognized escape sequences produce a [DeprecationWarning](https://docs.python.org/3/library/exceptions.html#DeprecationWarning).
> Changed in version 3.12: Unrecognized escape sequences produce a [SyntaxWarning](https://docs.python.org/3/library/exceptions.html#SyntaxWarning). In a future Python version they will be eventually a [SyntaxError](https://docs.python.org/3/library/exceptions.html#SyntaxError).

If you run your code with `PYTHONWARNINGS=error`, it will actually raise an Exception today (and as above, will raise `SyntaxError` in some future version of Python).

Anyway, with that said, your code is legal today (if deprecated) and your use of deprecated invalid escape sequences isn't really part of Black's business, so Black should probably swallow these warnings.

**Comment by Julien-Elie** [comment]
Thanks for your valuable response.  I had never noticed that the uses I did of the backslash were invalid escape sequences for Python (contrary to the same uses in some other languages).  I wrote them long time ago with Python 2, and it worked (though invalid, but the syntax error was not raised).
I've fixed them now.  Thanks a lot, I've learnt something today :)

I agree these warnings should not pop up when using Black.  (Seems like it's time for me to also integrate Pyflakes and Pylint to improve the quality of my scripts.)
