### ISSUE TITLE
Fails to parse backslash on line by itself

### ISSUE THREAD

**Issue by JelleZijlstra** [psf/black#4261]
```
% cat parse.py 
class Plotter:
\
    pass
% black parse.py 
error: cannot format parse.py: Cannot parse: 3:4:     pass

Oh no! 💥 💔 💥
1 file failed to reformat.
% black --version
black, 24.2.0 (compiled: yes)
Python (CPython) 3.12.0
% python parse.py
% 
```

Saw this in astral-sh/ruff#10099; the example is minified from the repro case in that issue.

**Comment by sumezulike** [comment]
So I looked into it and the issue seems to lie here:

The tokenizer tracks backslash-escaped newlines by setting the `continued` flag on the line ending with `\`, then skips checking for indentation on the next line.
https://github.com/psf/black/blob/e4bfedbec2e8b10cc6b7b31442478f05db0ce06d/src/blib2to3/pgen2/tokenize.py#L494-L559

That means that the input
```py
class Plotter:
\
    pass
```
generates these tokens:
```
NAME "class"
NAME "Plotter"
OP ":"
NEWLINE "\n"
NL "\\\n"
NAME "pass"
NEWLINE "\n"
```
whereas 
```py
class Plotter:
    pass
```
generates these:
```
NAME "class"
NAME "Plotter"
OP ":"
NEWLINE "\n"
INDENT
NAME "pass"
NEWLINE "\n"
DEDENT
```

But the grammar always expects an indent after the newline:
https://github.com/psf/black/blob/e4bfedbec2e8b10cc6b7b31442478f05db0ce06d/src/blib2to3/Grammar.txt#L127

So [add_token](https://github.com/psf/black/blob/f03ee113c9f3dfeb477f2d4247bfb7de2e5f465c/src/blib2to3/pgen2/parse.py#L242) doesn't find any valid state and raises an error.
https://github.com/psf/black/blob/f03ee113c9f3dfeb477f2d4247bfb7de2e5f465c/src/blib2to3/pgen2/parse.py#L333-L334

I feel like it would make more sense to add special handling in the tokenizer than to change the grammar. 

Anyone have a suggestion?

**Comment by JelleZijlstra** [comment]
I agree this should probably be fixed in the tokenizer. I don't have strong feelings on what the fix should look like, but presumably we should try to match what the CPython tokenizer does.

**Comment by JelleZijlstra** [comment]
Fun fact, this was illegal in earlier versions of Python. I guess the new parser must have somehow made this allowed:

```
% ~/.pyenv/versions/3.7.16/bin/python -c '''class Plotter:
\
    pass
'''
  File "<string>", line 3
    pass
       ^
IndentationError: expected an indented block
% ~/.pyenv/versions/3.9.16/bin/python -c '''class Plotter:
\
    pass
'''
  File "<string>", line 3
        pass
      ^
IndentationError: expected an indented block
% ~/.pyenv/versions/3.10.9/bin/python -c '''class Plotter:
\
    pass
'''
%
```

**Comment by sumezulike** [comment]
Oh, haha! My first thought was even "That doesn't look allowed" but then it just ran. 

I'll take a look at how this is handled in CPython and try to write a fix!

**Comment by Frenchcoder294** [comment]
can't we modify the [add_token](https://github.com/psf/black/blob/f03ee113c9f3dfeb477f2d4247bfb7de2e5f465c/src/blib2to3/pgen2/parse.py#L242) function to do so:
```
def _addtoken(self, ilabel: int, type: int, value: str, context: Context) -> bool:
    # Detect backslash-escaped newlines
    if value == '\\\n':
        # Special handling for backslash-escaped newlines
        # Perform token shifting or processing specific to this case
        # (e.g, continue the line without shifting tokens)
        # we may need to adjust the control flow or introduce additional checks here
        pass
    else:
        # Original token processing logic
```

**Comment by JelleZijlstra** [comment]
Feel free to submit a PR with test cases if your proposed change fixes this issue.

**Comment by tusharsadhwani** [comment]
@JelleZijlstra I have proposed a fix, but I feel it will require extensive testing as well. I've tried running it on a few open source projects and haven't seen any unexpected crashes etc.

**Comment by Frenchcoder294** [comment]
> @JelleZijlstra I have proposed a fix, but I feel it will require extensive testing as well. I've tried running it on a few open source projects and haven't seen any unexpected crashes etc.

THANKS!!!🏋️‍♂️
