### ISSUE TITLE
`MemoryError` when formatting Jupyter notebook

### ISSUE THREAD

**Issue by sam-xif** [psf/black#4400]
Hello Black team,

I am working as part of a research team developing a code analysis tool for Python. One of the issues the tool discovered in black's codebase is a `MemoryError` when formatting some Jupyter notebooks. In this case, the cause is due to a stack overflow in the Python parser. Attached is an ipynb file that reproduces the error on the latest version of black.

If you are interested in learning more about the tool and how it found this issue, let me know down in the comments, or you can contact me at [xifaras.s@northeastern.edu](mailto:xifaras.s@northeastern.edu). **We are primarily curious about whether you find that this issue is legitimate and worth reporting and fixing. If not, we would be interested in understanding why.**

Thank you for your consideration!

-Sam

**Describe the bug**

During the `replace_magics` operation when formatting a jupyter notebook, it is possible that a `MemoryError` gets thrown if there is a stack overflow in the `ast.parse` call. Here is the stack trace from `replace_magics`:

```
  File ".../black/src/black/handle_ipynb_magics.py", line 240, in replace_magics
    magic_finder.visit(ast.parse(src))
  File ".../lib/python3.8/ast.py", line 47, in parse
    return compile(source, filename, mode, flags,
MemoryError
```

**To Reproduce**

With the attached `memoryerror.ipynb`, run: `black --ipynb memoryerror.ipynb`.

Here is the output:
```
s_push: parser stack overflow
error: cannot format memoryerror.ipynb: 

Oh no! 💥 💔 💥
1 file failed to reformat.
```

**Expected behavior**

The exception seems to be handled gracefully by black, so perhaps this is an indication that no change needs to be made. 

**Environment**

- Black's version: 24.4.2
- OS and Python version: macOS/Python 3.8.3

**Additional context**

N/A

**Comment by JelleZijlstra** [comment]
You haven't attached a file, but I don't think there's anything we can reasonably fix about a file that is so big it overflows the Python parser.

**Comment by sam-xif** [comment]
@JelleZijlstra Sorry, I forgot to attach the file. The file is actually not that big:

```
{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [
    {
     "ename": "MemoryError",
     "evalue": "",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31mMemoryError\u001b[0m\n"
     ]
    }
   ],
   "source": [
    "(((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((t)))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.8.3"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 4
}

```

**Comment by MeGaGiGaGon** [comment]
I’m not familiar with the `ipynb` format, but I assume the code is the string in `source`, the `(((…(((t)))…)))`. If so, then it makes sense that it would fail, since that is causing a bunch of expressions, though you probably have a low memory allocation to whatever is running black. The playground formats that many just fine, and copy pasting more eventually gives a too many parenthesis for safe mode error.

If someone did encounter this in actual code, I’d recommend allocating more memory, splitting the expression up, or skipping that line with `# fmt: skip` / `off` and `on`.

I can’t speak for all of black’s dev team, I just lurk in the issues, but that many nested parenthesis looks to me like enough of an edge case that reducing the memory used isn’t a pressing concern, given that it requires both an obscene amount and low memory availability.

**Comment by sam-xif** [comment]
@MeGaGiGaGon Thank you, that is useful. Would you mind if I quote your comment in the writeup for this project?

**Comment by MeGaGiGaGon** [comment]
@sam-xif I would not mind, quote away
