### ISSUE TITLE
Don't use subscription brackets to break long lines?

### ISSUE THREAD

**Issue by yurkobb** [psf/black#951]
Consider this input:
```python
class Test:
    def method(self):
        ctx = super().get_context_data(**kwargs)
        ctx["shipping_methods"] = list(
            ShippingMethod.objects.all().values("id", "labels__identifier")
        )
        ctx["shipping_method_fields"] = (
            MyCheckoutForm.Meta.shipping_required_fields
        )
        return ctx
```
And output:

```python
class Test:
    def method(self):
        ctx = super().get_context_data(**kwargs)
        ctx["shipping_methods"] = list(
            ShippingMethod.objects.all().values("id", "labels__identifier")
        )
        ctx[
            "shipping_method_fields"
        ] = MyCheckoutForm.Meta.shipping_required_fields
        return ctx
```

I would (subjectively) expect the third assignment to stay the way it was.

~~Do "a[...]" often contain more than 1 element between the brackets?~~ (Ignore this argument please; of course they do if it's something other than a string literal)

----
Operating system:
Python version: 3.7.3
*Black* version: 19.3b0
Does also happen on master: yes

**Comment by JelleZijlstra** [comment]
I agree that this looks pretty weird. If we can find a way to fix this issue without affecting other existing formatting too much, I'd be supportive of changing it.

**Comment by zsol** [comment]
IMO the reason this looks weird is because the line break is on the LHS of an assignment statement *and* the indented line has a single, trivial expression.

```
(
    shipping_method_fields
) = MyCheckoutForm.Meta.shipping_required_fields
```

Looks the same kind of weird to me.

**Comment by alexanderGerbik** [comment]
Breaking lines on subscription brackets is quite confusing, it makes it look like list literal (I don't know the better way of formatting this though):
```python
        return self.client.post(url_for("auth.obtain_token"), json=credentials).json[
            "token"
        ]
```
#500 #1048

**Comment by yurkobb** [comment]
Maybe something like this?
 
```python
        return (
            self.client.post(url_for("auth.obtain_token"), json=credentials)
            .json["token"]
        )
```

**Comment by remytms** [comment]
I would even propose :
```python
        return (
            self.client
            .post(url_for("auth.obtain_token"), json=credentials)
            .json["token"]
        )
```
Following the same rule as parameters of a function, if it fits on one line keep it on one line. If not, split in multiline. Here instead of splitting on commas, it splits on dots.

**Comment by ttilberg** [comment]
I found this issue while trying to find community comments on code that I wondered "Is this formatted intentional? Is this a bug? Should I train myself to accept this?"

Here is the example I was reviewing:

```python
# ...
                yield {
                    # ...
                    "isAvailable": result["stock"]["relativeInventoryForSets"][
                        "isAvailable"
                    ],
                    "appointmentLeadTimeDays": result["stock"][
                        "appointmentLeadTimeDays"
                    ],
                    "stockLevel": result["stock"]["stockLevel"],
                    "zip_code": response.meta["item"]["zip_code"],
                }

```

It gets weirder if there's even longer keys to dig into:

```py
                {   # ...
                    "isAvailable": result["stock"]["relativeInventoryForSets"][
                        "isAvailable"
                    ]["isLong"]["isQuiteLong"],
                }
```

In this specific case, refactoring to a local `stock`, or moving some extraction code directly to an instance method could probably improve the situation, but I wanted to bring this example to the table for debate and potential refinement. I think it's reasonable to dig into JSON keys, and I think the way it gets formatted if the json keys are long is hard to interpret.

**Comment by yilei** [comment]
The OP issue was fixed in https://github.com/psf/black/pull/3368.

https://black.vercel.app/?version=stable&state=_Td6WFoAAATm1rRGAgAhARYAAAB0L-Wj4AHFAQJdAD2IimZxl1N_WlXnON2nzOXxnCQIxzIqQZbS3zQT4pbIpIKiARgUJdI2EJawz7lo-KXqAEThZwGjYfMtmysNajrmEFzhlDQ3vau23tNriEFqwUSFmear6RftHzwTia_pxZTFrKbIoy2g0u4PJQKggexVYAwjpLjNRRFNDi1IBgxuXR2_figpxYz8SlNc7NlscpvARFjA8URLNI-QdCK8GaTMGHgLYxEl0k9u8WmmUn_RuN2Xc_F_x8KOeqVoP5nSfgJF4UfhoK0VVzjn_O0HjfgOq8FnjkiIJvQ4GApDYWH_xpxg5rSdVAC_eD4QTCODaZsEiVjey-n8oM0kpkHBq7lZAAAAACST-Q800PumAAGeAsYDAAAN_5nPscRn-wIAAAAABFla

(The other examples are different than OP, I think they are related to https://github.com/psf/black/issues/2156)
